---
title: "anova"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=F}
library(here)

source(here("base","src.R"))
```


```{r}
foraging <- readRDS(here("processed_data", "foraging_raw.rds"))
mort <- readRDS(here("raw_data/main_mort_edit.rds"))

```

```{r}
mort %<>% filter(exposed==1 & temp %in% const_temp)
foraging %<>% mutate(temp = as.factor(temp),
                     resource = as.factor(resource))
```



# body size ANOVA
```{r}
size_aov <- aov(mm ~ resource + temp, data = foraging)
size_aov_int <- aov(mm ~ resource * temp, data = foraging) #interaction not significant

```

```{r}
summary(size_aov)
summary(size_aov_int)

```

```{r}
TukeyHSD(size_aov, which = "temp")
TukeyHSD(size_aov, which = "resource")
```

# body size lm
```{r}
size_lm <- lm(mm ~ as.numeric(resource) + as.numeric(temp), data = foraging)
size_lm_int <- lm(mm ~ as.numeric(resource) * as.numeric(temp), data = foraging) #interaction not significant
```

```{r}
summary(size_lm)
```


```{r}
summary(size_lm_int) #interaction not significant
```

```{r}
size_lm_15 <- lm(mm ~ as.numeric(resource), data = foraging %>% filter(temp == 15))
size_lm_20 <- lm(mm ~ as.numeric(resource), data = foraging %>% filter(temp == 20))
size_lm_25 <- lm(mm ~ as.numeric(resource), data = foraging %>% filter(temp == 25))
```

```{r}
summary(size_lm_15)
summary(size_lm_20)
summary(size_lm_25)
```





# amt_consumed ANOVA
```{r}
#amt_aov <- aov(amt_consumed ~ resource + temp, data = foraging)
amt_aov_int <- aov(amt_consumed ~ resource * temp, data = foraging)
```

```{r}
#summary(amt_aov)
summary(amt_aov_int)
```

```{r}
TukeyHSD(amt_aov_int, which = "temp")
TukeyHSD(amt_aov_int, which = "resource")
```

# linear models for amount consumed
```{r}
amt_lm <- lm(amt_consumed ~ as.numeric(resource) + as.numeric(temp), data = foraging)
amt_lm_int <- lm(amt_consumed ~ as.numeric(resource) * as.numeric(temp), data = foraging)
```

```{r}
summary(amt_lm)
```


```{r}
summary(amt_lm_int)
```






# prob infection glm
```{r}
#inf_glm <- glm(inf ~ as.numeric(temp) + as.numeric(resource), family = binomial, data = mort)
#inf_glm <- glm(inf ~ as.factor(temp) + as.factor(resource), family = binomial, data = mort)
inf_glm_int <- glm(inf ~ as.numeric(temp) * as.numeric(resource), family = binomial, data = mort)
#inf_glm_int <- glm(inf ~ as.factor(temp) * as.factor(resource), family = binomial, data = mort)
```

```{r}
#summary(inf_glm)
summary(inf_glm_int)
```








