---
title: "dynamic u"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = F}
library(here)
source(here("base","src.R"))

library(ggnewscale)
```


# Notes

Need to change resource-dependent term so that u can increase with resources. Right now resources can only diminish u but it should enhance it.


```{r}
fitness <- read.csv(here("raw_data/main_fitness_edit.csv")) #must be read.csv
fitness %<>% dplyr::select(tube, temp_id, REMOVED, KBP, final_date)
mort <-  read_csv(here("raw_data/main_mort_edit.csv"))
lengths <- read_csv(here("raw_data", "day5_length.csv"))
lengths %<>% filter(temp_id %in% c(15,20,25))


dataset <- left_join(mort,fitness)

data <- readRDS(here("processed_data","foraging_raw.rds"))
data_summ <- readRDS(here("processed_data", "foraging.rds"))

data %<>% mutate(treatment_ID = paste(temp, resource, sep = "_"))

data %<>% mutate(resource_tot = resource*vol) #resource_tot is the total amount of resources in our tube. resource concentration * total volume of tube 

treatment_IDs <- unique(data$treatment_ID)
resource_IDs <- unique(data$resource)
temp_IDs <- unique(data$temp)


fora_vol <- 15 #mL
life_vol <- 50 #mL
spore_conc <- 200 #spores/mL
gamma <- 2 
ref_t <- 15 #celsius

```

```{r}
dataset %<>% filter(species == "D") %>% #only daphnia for this analysis
  filter(temp %in% const_temp) #only constant temp for this analysis

dataset %<>% mutate(birthdate = ifelse(species == "daphnia", "4/5/22", "4/6/22"), 
                    lifespan = as.numeric(mdy(final_date) - mdy(birthdate)),
                    temp = as.numeric(temp),
                    treatment = paste(temp, resource, sep = "_")) %>% 
  filter(is.na(male)) %>% #remove males
  filter(is.na(missing)) %>% #remove missing
  filter(!is.na(inf)) #remove NAs for inf for estimating beta. sometimes they died too young to tell

dataset %<>% mutate(inf_status = inf, dead = ifelse(is.na(REMOVED) & is.na(KBP), 1, 0))


dataset %<>% mutate(spore_exposure = 200, #spores/mL
                    uninf = 1-inf_status,
                    time = 1, #duration of exposure in days
                    trt = paste(temp, resource, species, sep = "_"))
```

```{r}
lengths %<>% mutate(mm = raw_meas*17.86/1000)
#at default magnification (5.6x), 1 unit is equal to 17.86 micron

length_summ <- lengths %>% 
  group_by(temp_id, resource) %>% 
  summarize(life_mm = mean(mm),
            var = var(mm),
            sd = sd(mm),
            se = sd(mm)/sqrt(n())) %>%
  ungroup() %>%
  dplyr::select(temp_id, resource, life_mm)

length_summ %<>% add_row(temp_id=as.character(25), resource=as.numeric(0.5), life_mm=1.16) #midpoint between 1.0 and 0.1

dataset %<>% left_join(length_summ)
```




```{r}
mean_length_summ <- data_summ %>% dplyr::select(temp, resource, mm_mean)
data %<>% left_join(., mean_length_summ)
data %<>% mutate(mm = if_else(!is.na(mm), mm, mm_mean))

mean_length_summ %<>% rename(fora_mm = "mm_mean")
dataset %<>% left_join(., mean_length_summ)
```

$$
\frac{dR}{dt} = -L^{\gamma} fRS\\
$$

```{r, m1_num_sol}
m1_num_sol <- function(t, x, params){
  R <- x[1]
  S <- x[2]
  I <- x[3]
  Z <- x[4]
  with(as.list(params),{
    dR <- -f*R*(S+I)
    dS <- -u*f*Z*S
    dI <- u*f*Z*S
    dZ <- -f*Z*(S+I)
    res <- c(dR, dS, dI, dZ)
    list(res)}
    )
}

```

```{r, m1_sim}
m1_sim <- function(R, time, f, u, length, gamma, Z){
  times <- seq(0, time, by=0.01)
  xstart <- c(R=R,
              S=1,
              I=0,
              Z=Z)
  params <- c(f=f*(length^gamma),
              u=u)
  output <- as.data.frame(lsoda(y=xstart, times, m1_num_sol, params))
  if(Z == 0) {
  end_data <- slice_max(output, time)[,2]
  }
  else {
  end_data <- slice_max(output, time)[,4]  
  }
  
  # r_end <- ifelse(r_end<0, 0, r_end) #ensure that final resource concentration is never negative
  #probably unnecessary
  return(end_data)
}
```

```{r, m1_ll}
m1_ll <- function(f, u){
  data <- tmp
  R_end <- as.data.frame(mapply(m1_sim, R=data$amt_init*fora_vol/1000, time=data$time/60/24, f=f/fora_vol,
                                 u = 0, #u actually not important for this part. just wanted to use a single deSolve function for both
                                 length=data$mm, gamma=gamma, Z=0))
  colnames(R_end) <- "R_end"
  data$end <- R_end$R_end
  data %<>% mutate(resid = log(end) - log(amt_rem*fora_vol/1000))
  
    nll <- dnorm(data$resid, 
                 mean = 0, 
                 sd = sd(data$resid, na.rm = T), 
                 log = T)
    nll_sum <- -sum(nll, na.rm = T)
  

#  exp_data <- dataset %>% filter(exposed==TRUE)
  exp_data <- dataset_tmp %>% filter(exposed==TRUE)

  
  I_end <- as.data.frame(mapply(m1_sim, R=exp_data$resource*life_vol/1000, time=exp_data$time, f=f/life_vol, u=u, length = exp_data$life_mm, gamma=gamma, Z=spore_conc*life_vol))

  colnames(I_end) <- "I_end"
  
  exp_data %<>% cbind(I_end)
  
    inf_out <- function(inf_status, I_end){
    dbinom(x = inf_status, size = 1, prob=I_end, log=T)
  }
  
  exp_data %<>% 
    mutate(ll = mapply(inf_out, inf_status = inf_status, I_end=I_end))
  nll_sum <- nll_sum + -sum(exp_data$ll)
  return(nll_sum)
}
```


Now we use the optimizer
# ```{r, m1_mle}
# start_time <- Sys.time()
# tmp <- data
# m1_u_f_fit <- mle2(m1_ll, start=list(u = 0.0001, f=1), 
#                      control=list(parscale = c(u = 0.0001, f=1)),
#                      skip.hessian=F, method="L-BFGS-B", lower=c(u = 0, f = 0), upper=c(u = 1, f = Inf))
# end_time <- Sys.time()
# m1_runtime <- end_time - start_time
# m1_runtime
# 
# coef(m1_u_f_fit)
# 
# saveRDS(m1_u_f_fit, file = here("mle","update","m1_fit.rds"))
# ```

```{r, m1_mle_fits, eval=FALSE}
start_time <- Sys.time()
data %<>% mutate(treatment_ID = paste(temp, resource, sep = "_"))
dataset %<>% mutate(treatment_ID = paste(temp, resource, sep = "_"))

m1_fits <- list()
```


```{r}
for(i in 1:length(treatment_IDs)){

tmp <- data %>% filter(treatment_ID == treatment_IDs[i])
dataset_tmp <- dataset %>% filter(treatment_ID == treatment_IDs[i])

u_vec <- c(0.00001,#pass
           0.1,#
           0.2,#
           0.001,#
           0.0001,#
           0.001,#pass
           0.001,#
           0.001,#
           0.001)#

f_vec <- c(10,
           1,
           1,
           10,
           10,
           10,
           10,
           10,
           1)

m1_fits[i] <- mle2(m1_ll, start=list(u = u_vec[i], f=f_vec[i]),
                     control=list(parscale = c(u = u_vec[i], f=f_vec[i])),
                     skip.hessian=F, method="L-BFGS-B", lower=c(u = 0, f = 0), 
                   upper=c(u = 1, f = Inf))
print(i)
}
```


```{r, m1_mle_fits, eval=FALSE}
end_time <- Sys.time()
m1_runtime <- end_time - start_time
m1_runtime


saveRDS(m1_fits, file = here("mle","update","m1_fits.rds"))
```

```{r}
m1_fits <- readRDS(m1_fits, file = here("mle","update","m1_fits.rds"))


fit_data <- tibble(ID = c(1:9),
                   f = c(1:9),
                   u = c(1:9),
                   ll = c(1:9))
for(i in 1:nrow(data_summ)){
  fit_data$ID[i] <- treatment_IDs[i]
  fit_data$f[i] <- as.numeric(coef(m1_fits[[i]])[1])
  fit_data$u[i] <- as.numeric(coef(m1_fits[[i]])[2])
  fit_data$ll[i] <- summary(m1_fits[[i]])@m2logL
}

m1_param_n <- 18
m1_ll <- sum(fit_data$ll)

2*m1_param_n - (2*m1_ll/-2)

```



# model 3 - resource-dependent model

```{r, m3_sim}
m3_sim <- function(R, time, f, u, length, gamma, Z, h){
  times <- seq(0, time, by=0.01)
  xstart <- c(R=R,
              S=1,
              I=0,
              Z=Z)
  params <- c(f=f*(length^gamma)/(1+f*(length^gamma)*h*R),
              u=u)
  output <- as.data.frame(lsoda(y=xstart, times, m1_num_sol, params))
  if(Z == 0) {
  end_data <- slice_max(output, time)[,2]
  }
  else {
  end_data <- slice_max(output, time)[,4]  
  }
  
  # r_end <- ifelse(r_end<0, 0, r_end) #ensure that final resource concentration is never negative
  #probably unnecessary
  return(end_data)
}
```

```{r, m3_ll}
m3_ll <- function(f, u, h, k){
  data <- tmp
  R_end <- as.data.frame(mapply(m3_sim, R=data$amt_init*fora_vol/1000, time=data$time/60/24, f=f/fora_vol,
                                 u = 0, #u actually not important for this part. just wanted to use a single deSolve function for both
                                 length=data$mm, gamma=gamma, Z=0,
                                h=h*fora_vol))
  colnames(R_end) <- "R_end"
  data$end <- R_end$R_end
  data %<>% mutate(resid = log(end) - log(amt_rem*fora_vol/1000))
  
    nll <- dnorm(data$resid, 
                 mean = 0, 
                 sd = sd(data$resid, na.rm = T), 
                 log = T)
    nll_sum <- -sum(nll, na.rm = T)
  
#  exp_data <- dataset %>% filter(exposed==TRUE)
  exp_data <- dataset_tmp %>% filter(exposed==TRUE)

  
  I_end <- as.data.frame(mapply(m3_sim, R=exp_data$resource*life_vol/1000, time=exp_data$time, f=f/life_vol, 
                                u=u, length = exp_data$life_mm, gamma=gamma, Z=spore_conc*life_vol,
                                h=h*life_vol))

  colnames(I_end) <- "I_end"
  
  exp_data %<>% cbind(I_end)
  
    inf_out <- function(inf_status, I_end){
    dbinom(x = inf_status, size = 1, prob=I_end, log=T)
  }
  
  exp_data %<>% 
    mutate(ll = mapply(inf_out, inf_status = inf_status, I_end=I_end))
  nll_sum <- nll_sum + -sum(exp_data$ll)
  return(nll_sum)
}
```

```{r}
m3_fits <- list()

```


Now we use the optimizer
```{r, m3_mle, eval=F}


for(i in 7:length(treatment_IDs)){

tmp <- data %>% filter(treatment_ID == treatment_IDs[i])
dataset_tmp <- dataset %>% filter(treatment_ID == treatment_IDs[i])

u_vec <- c(0.00001,#pass - with message
           0.1,#pass
           0.2,#pass
           0.001,#pass - with message
           0.0001,#pass - with message
           0.001,#pass  - with message
           0.00001,#pass
           0.001,#
           0.001)#

f_vec <- c(10,
           1,
           0.1,
           10,
           10,
           10,
           1,
           1,
           1)

m3_fits[i] <- mle2(m3_ll, start=list(u = u_vec[i], f=f_vec[i], h=1),
                     control=list(parscale = c(u = u_vec[i], f=f_vec[i], h=1)),
                     skip.hessian=F, method="L-BFGS-B", lower=c(u = 0, f = 0, h=0), 
                   upper=c(u = 1, f = Inf, h=Inf))
print(i)
}

```

```{r}
saveRDS(m3_fits, file = here("mle","update","m3_fits.rds"))

```


```{r}
m3_fits <- readRDS(m3_fits, file = here("mle","update","m3_fits.rds"))



m3_fit_data <- tibble(ID = c(1:9),
                   f = c(1:9),
                   u = c(1:9),
                   ll = c(1:9))
for(i in 1:nrow(data_summ)){
  m3_fit_data$ID[i] <- treatment_IDs[i]
  m3_fit_data$f[i] <- as.numeric(coef(m3_fits[[i]])[1])
  m3_fit_data$u[i] <- as.numeric(coef(m3_fits[[i]])[2])
  m3_fit_data$ll[i] <- summary(m3_fits[[i]])@m2logL
}


m3_param_n <- 19
m3_ll <- sum(m3_fit_data$ll)

2*m3_param_n - (2*m3_ll/-2)

```


model 4 - both

```{r, m4_sim}
m4_sim <- function(R, time, f, u, length, gamma, Z, ref_t, arr_t_f, arr_t_u, h, temp){
  times <- seq(0, time, by=0.01)
  xstart <- c(R=R,
              S=1,
              I=0,
              Z=Z)
  params <- c(f=(f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/(1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R),
              u=u*exp(arr_t_u*(1/ref_t - 1/temp)))
  output <- as.data.frame(lsoda(y=xstart, times, m1_num_sol, params))
  if(Z == 0) {
  end_data <- slice_max(output, time)[,2]
  }
  else {
  end_data <- slice_max(output, time)[,4]  
  }
  
  # r_end <- ifelse(r_end<0, 0, r_end) #ensure that final resource concentration is never negative
  #probably unnecessary
  return(end_data)
}
```

```{r, m4_ll}
m4_ll <- function(f, u, arr_t_f, arr_t_u, h){
  data <- tmp
  R_end <- as.data.frame(mapply(m4_sim, R=data$amt_init*fora_vol/1000, time=data$time/60/24, f=f/fora_vol,
                                 u = 0, #u actually not important for this part. just wanted to use a single deSolve function for both
                                 length=data$mm, gamma=gamma, Z=0,
                                ref_t=ref_t,
                                arr_t_f=arr_t_f,
                                arr_t_u=arr_t_u,
                                h=h*fora_vol,
                                temp = data$temp))
  colnames(R_end) <- "R_end"
  data$end <- R_end$R_end
  data %<>% mutate(resid = log(end) - log(amt_rem*fora_vol/1000))
  
    nll <- dnorm(data$resid, 
                 mean = 0, 
                 sd = sd(data$resid, na.rm = T), 
                 log = T)
    nll_sum <- -sum(nll, na.rm = T)
  
#  exp_data <- dataset %>% filter(exposed==TRUE)
  exp_data <- dataset_tmp %>% filter(exposed==TRUE)

  
  I_end <- as.data.frame(mapply(m4_sim, R=exp_data$resource*life_vol/1000, time=exp_data$time, f=f/life_vol, 
                                u=u, length = exp_data$life_mm, gamma=gamma, Z=spore_conc*life_vol,
                                ref_t=ref_t,
                                arr_t_f=arr_t_f,
                                arr_t_u=arr_t_u,
                                h=h*life_vol,
                                temp=exp_data$temp))

  colnames(I_end) <- "I_end"
  
  exp_data %<>% cbind(I_end)
  
    inf_out <- function(inf_status, I_end){
    dbinom(x = inf_status, size = 1, prob=I_end, log=T)
  }
  
  exp_data %<>% 
    mutate(ll = mapply(inf_out, inf_status = inf_status, I_end=I_end))
  nll_sum <- nll_sum + -sum(exp_data$ll)
  return(nll_sum)
}
```




Now we use the optimizer
```{r, m4_mle, eval=F}
m4_fits <- list()
```


```{r, m4_mle, eval=F}


for(i in 7:length(treatment_IDs)){

tmp <- data %>% filter(treatment_ID == treatment_IDs[i])
dataset_tmp <- dataset %>% filter(treatment_ID == treatment_IDs[i])

u_vec <- c(0.00001,#pass - with message
           0.1,#pass
           0.2,#pass
           0.001,#pass - with message
           0.0001,#pass - with message
           0.001,#pass  - with message
           0.001,#pass
           0.001,#
           0.001)#

f_vec <- c(10,
           1,
           0.1,
           10,
           10,
           10,
           10,
           10,
           10)

m4_fits[i] <- mle2(m4_ll, start=list(u = u_vec[i], f=f_vec[i], arr_t_f=10, arr_t_u=10, h=1),
                     control=list(parscale = c(u = u_vec[i], f=f_vec[i], arr_t_f=10, arr_t_u=10, h=1)),
                     skip.hessian=F, method="L-BFGS-B", lower=c(u = 0, f = 0, arr_t_f=0, arr_t_u=0, h=0), 
                   upper=c(u = 1, f = Inf, arr_t_f=Inf, arr_t_u=Inf, h=Inf))
print(i)
}

```

```{r}
saveRDS(m4_fits, file = here("mle","update","m4_fits.rds"))

```


```{r}
m4_fits <- readRDS(m4_fits, file = here("mle","update","m4_fits.rds"))



m4_fit_data <- tibble(ID = c(1:9),
                   f = c(1:9),
                   u = c(1:9),
                   ll = c(1:9))
for(i in 1:nrow(data_summ)){
  m4_fit_data$ID[i] <- treatment_IDs[i]
  m4_fit_data$f[i] <- as.numeric(coef(m4_fits[[i]])[1])
  m4_fit_data$u[i] <- as.numeric(coef(m4_fits[[i]])[2])
  m4_fit_data$ll[i] <- summary(m4_fits[[i]])@m2logL
}


m4_param_n <- 19
m4_ll <- sum(m4_fit_data$ll)

2*m4_param_n - (2*m4_ll/-2)

```



```{r}
data_summ %<>% left_join(.,fit_data)
length_summ %<>% mutate(temp=as.numeric(temp_id))
data_summ %<>% left_join(length_summ)

data_summ %<>% mutate(I_end = mapply(m1_sim, R=resource, time=1, f=f/50, u=u, length = life_mm, gamma=2, Z=200*50))

data_summ %<>% mutate(model_prev = I_end)
```

check to make sure prevalence is the same
```{r}
dataset %>% filter(exposed==T) %>% group_by(treatment) %>% summarize(prev = sum(inf_status)/n())
```


```{r}
prevalence <- readRDS(here("processed_data", "prevalence.rds"))
prevalence %<>% filter(temp %in% c(15, 20, 25)) %>% filter(species=="D") %>% mutate(ID = paste(temp, resource, sep="_")) %>% dplyr::select(-c(temp, resource, species))
data_summ %<>% left_join(., prevalence, by="ID")
```


```{r}
data_summ %>% ggplot(.,aes(x=resource, y=f, group=temp, color=as.factor(temp))) + geom_point()
data_summ %>% ggplot(.,aes(x=resource, y=u, group=temp, color=as.factor(temp))) + geom_point()
data_summ %>% ggplot(.,aes(x=resource, y=log(u), group=temp, color=as.factor(temp))) + geom_point()
data_summ %>% filter(temp %in% c(20, 25))  %>% ggplot(.,aes(x=resource, y=u, group=temp, color=as.factor(temp))) + geom_point()
#data_summ %>% ggplot(.,aes(x=resource, y=f*u, group=temp, color=as.factor(temp))) + geom_point()
data_summ %>% ggplot(.,aes(x=resource, y=model_prev, color=as.factor(temp))) + geom_point()
```
```{r}
data_summ %>% ggplot(.,aes(x=resource, y=f, group=temp, color=as.factor(temp))) + geom_point(size=4) + new_scale_color() + geom_point(aes(x=resource, y=rate_len_mean*60*24, group = temp)) + geom_linerange(aes(x=resource, ymin=(rate_len_mean-rate_len_mean_se)*60*24, ymax=(rate_len_mean+rate_len_mean_se)*60*24))
```


```{r}
data_summ %>% ggplot(.,aes(x=resource, y=model_prev, color=as.factor(temp))) + geom_point(size=4, shape=2) + new_scale_color() + geom_point(size= 2,aes(x=resource, y=prev, group = temp, color = as.factor(temp))) + geom_linerange(aes(x=resource, ymin=conf$lower, ymax=conf$upper,color = as.factor(temp)))
```

```{r}
m1_sim_test <- function(R, time, f, u, length, gamma, Z){
  times <- seq(0, time, by=0.01)
  xstart <- c(R=R,
              S=1,
              I=0,
              Z=Z)
  params <- c(f=f,
              u=u,
              length=length,
              gamma=gamma)
  output <- as.data.frame(lsoda(y=xstart, times, m1_num_sol, params))

  end_data <- slice_max(output, time)[,4]  
  
  
  # r_end <- ifelse(r_end<0, 0, r_end) #ensure that final resource concentration is never negative
  #probably unnecessary
  return(end_data)
}
```

```{r}
factor <- 2.15

data_summ_tmp <- data_summ %>% mutate(output = mapply(m1_sim_test, R=resource*0.05, time=1, f=f/50, u=u*factor, length = life_mm, gamma=2, Z=200*50),
                                      new_u=u*factor) %>% dplyr::select(prev, output, u, new_u)
```

