---
title: "temp_fig"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#packages

```{r}
library(here)
source(here("base","src.R"))
library(ggnewscale)
library(patchwork)

#library(plotly)
```

Formatting
```{r}
theme_set(theme_bw(base_size = 12))

```




```{r}
f_seq_alt <- readRDS(file=here("model_fitting", "foraging", "rate_fit_alt.rds"))
f_seq <- readRDS(file=here("model_fitting", "foraging", "rate_fit.rds"))
u_seq <- readRDS(file = here("model_fitting", "combined", "seq_data.rds"))

data_summ <- readRDS(here("processed_data", "foraging.rds"))

data_summ %<>% dplyr::select(temp, resource, amt_init_mean)
f_seq %<>% left_join(., data_summ)

#f_seq %<>% mutate(amt_diff = resource-amt_rem_mean,
f_seq %<>% mutate(amt_diff = amt_init_mean-amt_rem_mean,
                  m1_diff = resource - m1_R_end/15*1000,
                  m2_diff = resource - m2_R_end/15*1000,
                  m3_diff = resource - m3_R_end/15*1000,
                  m4_diff = resource - m4_R_end/15*1000,
                  m6c_diff = resource - m6c_R_end/15*1000)



f_seq %<>% arrange(desc(temp))
```




```{r}
seq_plot <- function(seq_data, rate){
  seq_data %>% filter(temp %in% c(25,20,15)) %>%
  ggplot(.) +
  geom_line(aes(x=resource, 
                y=!!sym(rate),
                group=as.factor(temp),
                color=as.factor(temp)),
            size = 1) +
  geom_point(aes(x=resource, 
                  y=rate_len_mean, 
                  group = as.factor(temp), 
                  color = as.factor(temp)),
             size=3) + 
    geom_linerange(aes(x=resource, 
                       ymin=rate_len_mean-rate_len_mean_se,
                       ymax=rate_len_mean+rate_len_mean_se,
                       color=as.factor(temp))) +
#    scale_color_manual(values = c("#FFC107", "#1E88E5", "#D81B60")) +
    #scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D")) +
    scale_color_manual(values = c("#FFC107", "#21918c", "#440154")) +
    guides(color = guide_legend(reverse=T)) + 
  labs(x="Resource (mgC/L)", y="Foraging rate (mL/day)", color="Temperature", shape="Temperature", title = "") 
}

seq_plot(f_seq, "m1_rate")
```

```{r}
seq_plot_alt <- function(seq_data, rate){
  seq_data %>% filter(temp %in% c(15,20,25)) %>%
  ggplot(.) +
  geom_line(aes(x=resource, 
                y=!!sym(rate),
                group=as.factor(temp),
                color=as.factor(temp)),
            size = 1) +
#    scale_color_manual(values = c("#FFC107", "#1E88E5", "#D81B60")) +
    #scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D")) +
    scale_color_manual(values = c("#FFC107", "#21918c", "#440154")) +
    scale_x_continuous(breaks = c(0.1, 0.5, 1.0)) + 
    scale_y_continuous(breaks = c(0, 20, 40), limits = c(0, 42)) + 
    guides(color = guide_legend(reverse=T)) + 
  labs(x="Resource (mgC/L)", y="Foraging rate (mL/day)", color="Temperature", shape="Temperature", title = "") 
}

seq_plot_alt(f_seq, "m1_rate")
```


```{r}
seq_plot_temp <- function(seq_data, rate){
  seq_data %>% filter(resource %in% c(0.1, 0.5, 1)) %>%
  ggplot(.) +
  geom_line(aes(x=temp, 
                y=!!sym(rate),
                group=resource,
                color=as.factor(resource)),
            size=1) +
  geom_point(aes(x=temp, 
                  y=rate_len_mean, 
                  group = as.factor(resource), 
                  color = as.factor(resource)),
                 size=3) +
        geom_linerange(aes(x=temp, 
                       ymin=rate_len_mean-rate_len_mean_se,
                       ymax=rate_len_mean+rate_len_mean_se,
                       color=as.factor(resource))) + 
    scale_color_manual(values = c("#CABD88", "#CA5216", "#65320D")) +
  labs(x="Temperature", y="Foraging rate (mL/day)", color="", shape="", title = "") 
}

seq_plot_temp(f_seq, "m1_rate")

```


```{r}
spores_plot <- function(seq_data, var){
seq_data %>% filter(temp %in% const_temp) %>% 
  ggplot(., aes(x=resource, y=!!sym(var), color=as.factor(temp), group = as.factor(temp))) + 
  geom_line(size = 1) + 
  labs(x = "Resource (mgC/L)", 
       y = "Spores consumed",
       color = "Temp") + 
  scale_x_continuous(breaks = c(0.1, 0.5, 1.0)) + 
  scale_y_continuous(breaks = c(0, 2000, 4000, 6000), limits = c(0, 6000)) + 
  guides(color = guide_legend(reverse=T)) + 
  #scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D")) + 
  scale_color_manual(values = c("#FFC107", "#21918c", "#440154"))
}

spores_plot_temp <- function(seq_data, var){
seq_data %>% filter(resource %in% c(0.1, 0.5, 1)) %>% 
  ggplot(., aes(x=temp, y=!!sym(var), color=as.factor(resource), group = as.factor(resource))) + 
  geom_line(size = 1) + 
  labs(x = "Temperature (C)", 
       y = "Spores consumed",
       color = "Resource (mgC/L)") + 
  scale_color_manual(values = c("#CABD88", "#CA5216", "#65320D"))
}

spores_plot(f_seq, "m1_Z_end")

```


```{r}
prev_plot <- function(seq_data, var){
  seq_data %>% filter(temp %in% const_temp) %>% 
    ggplot(.,aes(x=resource, 
                 y=!!sym(var), 
                 color=as.factor(temp))) + 
    geom_line(size=1) +
    #scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D")) +
    scale_color_manual(values = c("#FFC107", "#21918c", "#440154")) +
    new_scale_color() + 
    geom_point(aes(x=resource, y=prev, color=as.factor(temp)), size=3) + 
    geom_linerange(aes(ymin = conf$lower, ymax=conf$upper, color=as.factor(temp))) +
    #scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D")) +
    scale_color_manual(values = c("#FFC107", "#21918c", "#440154")) +
    scale_x_continuous(breaks = c(0.1, 0.5, 1.0)) + 
    scale_y_continuous(breaks = c(0, 0.5, 1.0)) + 
    guides(color = guide_legend(reverse=T)) + 
    labs(x="Resource (mgC/L)", y="Infection Prevalence", color="Temperature", title = "")
}

prev_plot_temp <- function(seq_data, var){
  seq_data %>% filter(resource %in% c(0.1, 0.5, 1)) %>% 
    ggplot(.,aes(x=temp, 
                 y=!!sym(var), 
                 color=as.factor(resource))) + 
    geom_line(size=1) +
    scale_color_manual(values = c("#CABD88", "#CA5216", "#65320D")) +
    new_scale_color() + 
    geom_point(aes(x=temp, y=prev, color=as.factor(resource)), size=3) + 
    geom_linerange(aes(ymin = conf$lower, ymax=conf$upper, color=as.factor(resource))) +
    scale_color_manual(values = c("#CABD88", "#CA5216", "#65320D")) +
    labs(x="Temperature (C) ", y="Probability of Infection", color="Resource (mgC/L)", title = "")
}

prev_plot(u_seq, "m1_I_end")
```


```{r}
rate_plot <- function(seq_data, var){
  seq_data %>% filter(temp %in% const_temp) %>% 
    ggplot(.,aes(x=resource, y=!!sym(var), color=as.factor(temp))) + 
      geom_line(size=1) +
      scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D")) +
      new_scale_color() + 
      geom_point(aes(x=resource, y=rate_mean_ml_day, color=as.factor(temp)), size=3, shape = 1) + 
      geom_linerange(aes(x=resource, 
                     ymin=rate_mean_ml_day-rate_se_ml_day,
                     ymax=rate_mean_ml_day+rate_se_ml_day,
                     color=as.factor(temp))) +
      scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D")) +
      labs(x = "Resource (mgC/L)", y = "Foraging rate (mL/day)", title="")
}

rate_plot(u_seq, "m1_rate")

```


```{r}
u_plot <- function(seq_data, var){
  seq_data %>% 
    filter(temp %in% const_temp) %>% 
    ggplot(.,aes(x=resource, y=!!sym(var), color=as.factor(temp))) + 
    geom_line(size = 1) + 
    #scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D")) +
    scale_color_manual(values = c("#FFC107", "#21918c", "#440154")) +
    #ylim(NA, 0.0025) + 
    scale_x_continuous(breaks = c(0.1, 0.5, 1.0)) + 
    scale_y_continuous(breaks = c(0, 0.001, 0.002), limits = c(0, 0.002)) + 
    guides(color = guide_legend(reverse=T)) + 
    labs(x = "Resource (mgC/L)", y = "Per-Spore Susceptibility", color = "Temp", title = "")
}

u_plot_temp <- function(seq_data, var){
  seq_data %>% 
    filter(resource %in% c(0.1, 0.5, 1)) %>% 
    ggplot(.,aes(x=temp, y=!!sym(var), color=as.factor(resource))) + 
    geom_line(size = 1) + 
    ylim(NA, 0.00275) + 
    scale_color_manual(values = c("#CABD88", "#CA5216", "#65320D")) +
    labs(x = "Temperature (C)", y = "Per-Spore Susceptibility", color = "Resource (mgC/L)", title = "")
}

u_plot(u_seq, "m5_u")
```




```{r}
# algae_plot <- function(seq_data, var){
# seq_data %>% filter(temp %in% const_temp) %>% 
#   ggplot(., aes(x=resource, y=!!sym(var), color=as.factor(temp), group = as.factor(temp))) + 
#   geom_line(size=1) + 
#   geom_point(aes(x=resource, 
#                   y=amt_consumed_mean*15/1000, 
#                   group = as.factor(temp), 
#                   color = as.factor(temp)),
#              size=3) + 
#     geom_linerange(aes(x=resource, 
#                        ymin=amt_consumed_mean*15/1000-amt_consumed_se*15/1000,
#                        ymax=amt_consumed_mean*15/1000+amt_consumed_se*15/1000,
#                        color=as.factor(temp))) +
#   labs(x = "Resource (mgC/L)", 
#        y = "Algae consumed (mgC/L)",
#        color = "Temp") + 
# #    ylim(NA, 0.004) +
#   scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D"))
# }
# 
# algae_plot <- function(seq_data, var){
# seq_data %>% filter(temp %in% const_temp) %>% 
#   ggplot(., aes(x=resource, y=!!sym(var), color=as.factor(temp), group = as.factor(temp))) + 
#   geom_line(size=1) + 
#   geom_point(aes(x=resource, 
#                   y=amt_consumed_mean_theor*15/1000, 
#                   group = as.factor(temp), 
#                   color = as.factor(temp)),
#              size=3) + 
#     geom_linerange(aes(x=resource, 
#                        ymin=amt_consumed_mean_theor*15/1000-amt_consumed_se_theor*15/1000,
#                        ymax=amt_consumed_mean_theor*15/1000+amt_consumed_se_theor*15/1000,
#                        color=as.factor(temp))) +
#   labs(x = "Resource (mgC/L)", 
#        y = "Algae consumed (mgC/L)",
#        color = "Temp") + 
# #    ylim(NA, 0.004) +
#   scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D"))
# }
# 
# algae_plot_temp <- function(seq_data, var){
# seq_data %>% filter(resource %in% c(0.1, 0.5, 1)) %>% 
#   ggplot(., aes(x=temp, y=!!sym(var), color=as.factor(resource), group = as.factor(resource))) + 
#   geom_line(size=1) + 
#   labs(x = "Temperature (C)", 
#        y = "Algae consumed (mgC)",
#        color = "Temp") + 
#   scale_color_manual(values = c("#CABD88", "#CA5216", "#65320D"))
# }
# 
# algae_plot(f_seq, "m1_consumed")
# algae_plot(f_seq, "m2_consumed")
# algae_plot(f_seq, "m3_consumed")
# algae_plot(f_seq, "m4_consumed")
# algae_plot(f_seq, "m6c_consumed")
```

```{r}


algae_plot <- function(seq_data, var){
seq_data %>% filter(temp %in% const_temp) %>% 
  ggplot(., aes(x=resource, y=!!sym(var), color=as.factor(temp), group = as.factor(temp))) + 
  geom_line(size=1) + 
  geom_point(aes(x=resource, 
                  y=amt_rem_mean*15/1000, 
                  group = as.factor(temp), 
                  color = as.factor(temp)),
             size=1) + 
    geom_linerange(aes(x=resource, 
                       ymin=amt_rem_mean*15/1000-amt_rem_se*15/1000,
                       ymax=amt_rem_mean*15/1000+amt_rem_se*15/1000,
                       color=as.factor(temp))) +
  labs(x = "Resource (mgC/L)", 
       y = "Resource remaining (mgC)",
       color = "Temp") + 
    scale_x_continuous(breaks = c(0.1, 0.5, 1.0)) + 
    guides(color = guide_legend(reverse=T)) + 
  #scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D"))
  scale_color_manual(values = c("#FFC107", "#21918c", "#440154"))
}

algae_plot <- function(seq_data, var){
seq_data %>% filter(temp %in% const_temp) %>%
  ggplot(., aes(x=resource, y=!!sym(var)/15*1000, color=as.factor(temp), group = as.factor(temp))) +
  geom_line(size=1) +
  geom_point(aes(x=resource,
                  y=amt_rem_mean,
                  group = as.factor(temp),
                  color = as.factor(temp)),
             size=3) +
    geom_linerange(aes(x=resource,
                       ymin=amt_rem_mean-amt_rem_se,
                       ymax=amt_rem_mean+amt_rem_se,
                       color=as.factor(temp))) +
  labs(x = "Resource (mgC/L)",
       y = "Resource remaining (mgC/L)",
       color = "Temp") +
    scale_x_continuous(breaks = c(0.1, 0.5, 1.0)) + 
    guides(color = guide_legend(reverse=T)) + 
  #scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D"))
  scale_color_manual(values = c("#FFC107", "#21918c", "#440154"))
}


algae_plot_diff <- function(seq_data, var){
seq_data %>% filter(temp %in% const_temp) %>%
  ggplot(., aes(x=resource, y=!!sym(var), color=as.factor(temp), group = as.factor(temp))) +
  geom_line(size=1) +
  geom_point(aes(x=resource,
                  y=amt_diff,
                  group = as.factor(temp),
                  color = as.factor(temp)),
             size=3) +
    geom_linerange(aes(x=resource,
                       ymin=amt_diff-1.96*amt_rem_se,
                       ymax=amt_diff+1.96*amt_rem_se,
                       color=as.factor(temp))) +
  labs(x = "Resource (mgC/L)",
       y = "Resource difference (mgC/L)",
       color = "Temp") +
    scale_x_continuous(breaks = c(0.1, 0.5, 1.0)) + 
    guides(color = guide_legend(reverse=T)) + 
  #scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D"))
  scale_color_manual(values = c("#FFC107", "#21918c", "#440154"))
}




algae_plot_temp <- function(seq_data, var){
seq_data %>% filter(resource %in% c(0.1, 0.5, 1)) %>% 
  ggplot(., aes(x=temp, y=!!sym(var), color=as.factor(resource), group = as.factor(resource))) + 
  geom_line(size=1) + 
  labs(x = "Temperature (C)", 
       y = "Resource remaining (mgC)",
       color = "Temp") + 
  scale_color_manual(values = c("#CABD88", "#CA5216", "#65320D"))
}

algae_plot(f_seq, "m1_R_end")
algae_plot(f_seq, "m2_R_end")
algae_plot(f_seq, "m3_R_end")
algae_plot(f_seq, "m4_R_end")
algae_plot(f_seq, "m6c_R_end")

algae_plot_diff(f_seq, "m1_diff")
algae_plot_diff(f_seq, "m2_diff")
algae_plot_diff(f_seq, "m3_diff")
algae_plot_diff(f_seq, "m4_diff")
algae_plot_diff(f_seq, "m6c_diff")
```

Shifted x-axis

```{r}
algae_plot_diff <- function(seq_data, var){
seq_data %>% filter(temp %in% const_temp) %>%
  ggplot(., aes(x=resource, y=!!sym(var), color=as.factor(temp), group = as.factor(temp))) +
  geom_line(size=1) +
  geom_point(aes(x=amt_init_mean,
                  y=amt_diff,
                  group = as.factor(temp),
                  color = as.factor(temp)),
             size=3) +
    geom_linerange(aes(x=amt_init_mean,
                       ymin=amt_diff-1.96*amt_rem_se,
                       ymax=amt_diff+1.96*amt_rem_se,
                       color=as.factor(temp))) +
  labs(x = "Resource (mgC/L)",
       y = "Resource difference (mgC/L)",
       color = "Temp") +
    scale_x_continuous(breaks = c(0.1, 0.5, 1.0)) + 
    guides(color = guide_legend(reverse=T)) + 
  #scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D"))
  scale_color_manual(values = c("#FFC107", "#21918c", "#440154"))
}

algae_plot_diff(f_seq, "m2_diff")
algae_plot_diff(f_seq, "m3_diff")
algae_plot_diff(f_seq, "m4_diff")
algae_plot_diff(f_seq, "m6c_diff")

```



```{r}
algae_conc_plot <- function(seq_data, var){
seq_data %>% filter(temp %in% const_temp) %>% 
  ggplot(., aes(x=resource, y=!!sym(var)/15*1000, color=as.factor(temp), group = as.factor(temp))) + 
  geom_line(size=1) + 
  geom_point(aes(x=resource, 
                  y=amt_consumed_mean, 
                  group = as.factor(temp), 
                  color = as.factor(temp)),
             size=3) + 
    geom_linerange(aes(x=resource, 
                       ymin=amt_consumed_mean-amt_consumed_se,
                       ymax=amt_consumed_mean+amt_consumed_se,
                       color=as.factor(temp))) +
  labs(x = "Resource (mgC/L)", 
       y = "Algae consumed (mgC/L)",
       color = "Temp") + 
    ylim(0, NA) +
  scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D"))
}

algae_plot_temp <- function(seq_data, var){
seq_data %>% filter(resource %in% c(0.1, 0.5, 1)) %>% 
  ggplot(., aes(x=temp, y=!!sym(var), color=as.factor(resource), group = as.factor(resource))) + 
  geom_line(size=1) + 
  labs(x = "Temperature (C)", 
       y = "Algae consumed (mgC)",
       color = "Temp") + 
  scale_color_manual(values = c("#CABD88", "#CA5216", "#65320D"))
}

#algae_plot(f_seq, "m1_consumed")
```
















Show temp only models

```{r}
t1 <- seq_plot(f_seq, "m2_rate") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
#algae_plot(f_seq, "m2_consumed")
t2 <- spores_plot(f_seq, "m2_Z_end") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
t3 <- u_plot(u_seq, "m2_u") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
t4 <- prev_plot(u_seq, "m2_I_end") + theme(plot.title = element_blank(), legend.position = "none")

temp_plots <- t1 / t2 / t3 / t4

# ggsave(here("workshop", "figures","temp_plots.png"),
#        temp_plots,
#        width = 3,
#        height = 8,
#        units = "in")

```



Show resource only models

```{r}
r1 <- seq_plot_temp(f_seq, "m3_rate") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
#algae_plot_temp(f_seq, "m3_consumed")
r2 <- spores_plot_temp(f_seq, "m3_Z_end") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
r3 <- u_plot_temp(u_seq, "m3_u") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
r4 <- prev_plot_temp(u_seq, "m3_I_end") + theme(plot.title = element_blank(), legend.position = "none")

resource_plots <- r1 / r2 / r3 / r4

# ggsave(here("workshop", "figures","resource_plots.png"),
#        resource_plots,
#        width = 3,
#        height = 8,
#        units = "in")
```


# additive plots

```{r}
add1 <- seq_plot(f_seq, "m4_rate") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
#algae_plot(f_seq, "m4_consumed")
add2 <- spores_plot(f_seq, "m4_Z_end") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
add3 <- u_plot(u_seq, "m4_u") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
add4 <- prev_plot(u_seq, "m4_I_end") + theme(plot.title = element_blank(), legend.position = "none")

additive_plots <- add1 / add2 / add3 / add4

# ggsave(here("workshop", "figures","additive_plots.png"),
#        additive_plots,
#        width = 3,
#        height = 8,
#        units = "in")
```

# interactive plots

```{r}
i1 <- seq_plot(f_seq, "m6c_rate") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
#algae_plot(f_seq, "m6c_consumed")
i2 <- spores_plot(f_seq, "m6c_Z_end") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
i3 <- u_plot(u_seq, "m5_u") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
i4 <- prev_plot(u_seq, "m5_I_end") + theme(plot.title = element_blank(), legend.position = "none", panel.background = element_rect(fill = "#ADD0E9"))

interactive_plots <- i1 / i2 / i3 / i4

# ggsave(here("workshop", "figures","interactive_plots.png"),
#        interactive_plots,
#        width = 3,
#        height = 8,
#        units = "in")
```



# f seq plots


```{r}
f0 <- seq_plot(f_seq, "m1_rate") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
f1 <- seq_plot(f_seq, "m2_rate") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
f2 <- seq_plot(f_seq, "m3_rate") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
f3 <- seq_plot(f_seq, "m4_rate") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
f4 <- seq_plot(f_seq, "m6c_rate") + theme(plot.title = element_blank(), legend.position = "none", axis.title.y = element_blank(), panel.background = element_rect(fill = "#ADD0E9"))

clearance_plots <- f0 / f1 / f2 / f3 / f4

ggsave(here("workshop", "figures","clearance_plots_all.png"),
       clearance_plots,
       width = 3,
       height = 9,
       units = "in")
```


```{r}
f0 <- seq_plot_alt(f_seq, "m1_rate") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
f1 <- seq_plot_alt(f_seq, "m2_rate") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
f2 <- seq_plot_alt(f_seq, "m3_rate") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
f3 <- seq_plot_alt(f_seq, "m4_rate") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
f4 <- seq_plot_alt(f_seq, "m6c_rate") + theme(plot.title = element_blank(), legend.position = "none", axis.title.y = element_blank(), panel.background = element_rect(fill = "#ADD0E9"))

f0 <- seq_plot_alt(f_seq, "m1_rate") + 
  theme(axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
f1 <- seq_plot_alt(f_seq, "m2_rate") + 
  theme(axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
f2 <- seq_plot_alt(f_seq, "m3_rate") + 
  theme(axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
f3 <- seq_plot_alt(f_seq, "m4_rate") + 
  theme(axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
f4 <- seq_plot_alt(f_seq, "m6c_rate") + theme(plot.title = element_blank(), legend.position = "none", axis.title.y = element_blank())


clearance_plots <- f0 / f1 / f2 / f3 / f4

#ggsave(here("workshop", "figures","clearance_plots_alt_all.png"),
ggsave(here("workshop", "figures","clearance_plots_alt_all_axes.png"),
       clearance_plots,
       width = 3,
       height = 9,
       units = "in")
```


```{r}
a1 <- algae_plot(f_seq, "m2_R_end") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
a2 <- algae_plot(f_seq, "m3_R_end") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
a3 <- algae_plot(f_seq, "m4_R_end") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
a4 <- algae_plot(f_seq, "m6c_R_end") + theme(plot.title = element_blank(), legend.position = "none", axis.title.y = element_blank(), panel.background = element_rect(fill = "#ADD0E9"))

algae_plots <- a1 / a2 / a3 / a4

ggsave(here("workshop", "figures","algae_plots.png"),
       algae_plots,
       width = 3,
       height = 8,
       units = "in")
```

```{r}
a0 <- algae_plot_diff(f_seq, "m1_diff") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
a1 <- algae_plot_diff(f_seq, "m2_diff") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
a2 <- algae_plot_diff(f_seq, "m3_diff") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
a3 <- algae_plot_diff(f_seq, "m4_diff") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
a4 <- algae_plot_diff(f_seq, "m6c_diff") + theme(plot.title = element_blank(), legend.position = "none", axis.title.y = element_blank(), panel.background = element_rect(fill = "#ADD0E9"))

a0 <- algae_plot_diff(f_seq, "m1_diff") + 
  theme(axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
a1 <- algae_plot_diff(f_seq, "m2_diff") + 
  theme(axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
a2 <- algae_plot_diff(f_seq, "m3_diff") + 
  theme(axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
a3 <- algae_plot_diff(f_seq, "m4_diff") + 
  theme(axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
a4 <- algae_plot_diff(f_seq, "m6c_diff") + theme(plot.title = element_blank(), legend.position = "none", axis.title.y = element_blank())

algae_plots_diff <- a0 / a1 / a2 / a3 / a4

#ggsave(here("workshop", "figures","algae_plots_diff.png"),
ggsave(here("workshop", "figures","algae_plots_diff_all_axes.png"),
#ggsave(here("workshop", "figures","algae_plots_diff_all.png"),
       algae_plots_diff,
       width = 3,
       height = 9,
       units = "in")
```

```{r}
fs1 <- spores_plot(f_seq, "m2_Z_end") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
fs2 <- spores_plot(f_seq, "m3_Z_end") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
fs3 <- spores_plot(f_seq, "m4_Z_end") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
fs4 <- spores_plot(f_seq, "m6c_Z_end") + theme(axis.title.y=element_blank(), plot.title = element_blank(), legend.position = "none", panel.background = element_rect(fill = "#ADD0E9"))

fora_spores_plots <- fs1 / fs2 / fs3 / fs4

# ggsave(here("workshop", "figures","fora_spore_plots.png"),
#        fora_spores_plots,
#        width = 3,
#        height = 8,
#        units = "in")
```



```{r}
clearance_hz <- f1 | f2 | f3 | f4

# ggsave(here("workshop", "figures","clearance_hz_plots.png"),
#        clearance_hz,
#        width = 8,
#        height = 3,
#        units = "in")
```

```{r}
algae_hz <- a1 | a2 | a3 | a4

# ggsave(here("workshop", "figures","algae_hz_plots.png"),
#        algae_hz,
#        width = 8,
#        height = 3,
#        units = "in")
```


```{r}
fora_spores_hz <- fs1 | fs2 | fs3 | fs4

# ggsave(here("workshop", "figures","fora_spores_hz_plots.png"),
#        fora_spores_hz,
#        width = 8,
#        height = 3,
#        units = "in")
```









# u_seq plots

spores plots


```{r}
spores_plot(u_seq, "spores_consumed_m6c")
spores_plot(f_seq, "m6c_Z_end")
```

```{r}
s0 <- spores_plot(u_seq, "spores_consumed_m1") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
s1 <- spores_plot(u_seq, "spores_consumed_m2") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
s2 <- spores_plot(u_seq, "spores_consumed_m3") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
s3 <- spores_plot(u_seq, "spores_consumed_m4") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
s4 <- spores_plot(u_seq, "spores_consumed_m5") + theme(axis.title.y=element_blank(), plot.title = element_blank(), legend.position = "none", panel.background = element_rect(fill = "#ADD0E9"))

s0 <- spores_plot(u_seq, "spores_consumed_m1") + 
  theme(axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
s1 <- spores_plot(u_seq, "spores_consumed_m2") + 
  theme(axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
s2 <- spores_plot(u_seq, "spores_consumed_m3") + 
  theme(axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
s3 <- spores_plot(u_seq, "spores_consumed_m4") + 
  theme(axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
s4 <- spores_plot(u_seq, "spores_consumed_m5") + theme(axis.title.y=element_blank(), plot.title = element_blank(), legend.position = "none")

spores_plots <- s0 / s1 / s2 / s3 / s4

#ggsave(here("workshop", "figures","spores_plots_all.png"),
ggsave(here("workshop", "figures","spores_plots_all_axes.png"),
       spores_plots,
       width = 3,
       height = 9,
       units = "in")
```


susceptibility plots


```{r}
u0 <- u_plot(u_seq, "m1_u") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
u1 <- u_plot(u_seq, "m2_u") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
u2 <- u_plot(u_seq, "m3_u") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
u3 <- u_plot(u_seq, "m4_u") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
u4 <- u_plot(u_seq, "m5_u") + theme(axis.title.y=element_blank(), plot.title = element_blank(), legend.position = "none", panel.background = element_rect(fill = "#ADD0E9"))

u0 <- u_plot(u_seq, "m1_u") + 
  theme(axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
u1 <- u_plot(u_seq, "m2_u") + 
  theme(axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
u2 <- u_plot(u_seq, "m3_u") + 
  theme(axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
u3 <- u_plot(u_seq, "m4_u") + 
  theme(axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
u4 <- u_plot(u_seq, "m5_u") + theme(axis.title.y=element_blank(), plot.title = element_blank(), legend.position = "none")

susc_plots <- u0 / u1 / u2 / u3 / u4

#ggsave(here("workshop", "figures","susc_plots_all.png"),
ggsave(here("workshop", "figures","susc_plots_all_axes.png"),
       susc_plots,
       width = 3,
       height = 9,
       units = "in")
```

```{r}
u1 <- u_plot_temp(u_seq, "m2_u") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
u2 <- u_plot_temp(u_seq, "m3_u") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
u3 <- u_plot_temp(u_seq, "m4_u") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
u4 <- u_seq %>% 
    filter(resource %in% c(0.1, 0.5, 1)) %>% 
    ggplot(.,aes(x=temp, y=m5b_u, color=as.factor(resource))) + 
    geom_point(size = 4, alpha=0.5, position = position_jitter(width = 0.4)) + 
    scale_color_manual(values = c("#CABD88", "#CA5216", "#65320D")) +
    ylim(NA, 0.00275) + 
    labs(x = "Temperature (C)", y = "Per-Spore Susceptibility", color = "Resource (mgC/L)", title = "") + 
  theme(axis.title.y=element_blank(), plot.title = element_blank(), legend.position = "none", panel.background = element_rect(fill = "#ADD0E9"))

u4 <- u_seq %>% 
    filter(resource %in% c(0.1, 0.5, 1)) %>% 
    ggplot(.,aes(x=temp, y=m5b_u, fill=as.factor(resource))) + 
    geom_col(position=position_dodge(), width=1.5) + 
    scale_fill_manual(values = c("#CABD88", "#CA5216", "#65320D")) +
    ylim(NA, 0.00275) + 
    labs(x = "Temperature (C)", y = "Per-Spore Susceptibility", color = "Resource (mgC/L)", title = "") + 
  theme(axis.title.y=element_blank(), plot.title = element_blank(), legend.position = "none", panel.background = element_rect(fill = "#ADD0E9"))

susc_plots <- u1 / u2 / u3 / u4

# ggsave(here("workshop", "figures","susc_plots_temp.png"),
#        susc_plots,
#        width = 3,
#        height = 8,
#        units = "in")
```



prevalence plots


```{r}
p0 <- prev_plot(u_seq, "m1_I_end") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
p1 <- prev_plot(u_seq, "m2_I_end") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
p2 <- prev_plot(u_seq, "m3_I_end") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
p3 <- prev_plot(u_seq, "m4_I_end") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
p4 <- prev_plot(u_seq, "m5_I_end") + theme(axis.title.y=element_blank(), plot.title = element_blank(), legend.position = "none", panel.background = element_rect(fill = "#ADD0E9"))

p0 <- prev_plot(u_seq, "m1_I_end") + 
  theme(axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
p1 <- prev_plot(u_seq, "m2_I_end") + 
  theme(axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
p2 <- prev_plot(u_seq, "m3_I_end") + 
  theme(axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
p3 <- prev_plot(u_seq, "m4_I_end") + 
  theme(axis.title = element_blank(), plot.title = element_blank(), legend.position = "none")
p4 <- prev_plot(u_seq, "m5_I_end") + theme(axis.title.y=element_blank(), plot.title = element_blank(), legend.position = "none")

prev_plots <- p0 / p1 / p2 / p3 / p4

#ggsave(here("workshop", "figures","prev_plots_all.png"),
ggsave(here("workshop", "figures","prev_plots_all_axes.png"),
       prev_plots,
       width = 3,
       height = 9,
       units = "in")
```


```{r}
spores_hz <- s1 | s2 | s3 | s4

# ggsave(here("workshop", "figures","spores_hz_plots.png"),
#        spores_hz,
#        width = 8,
#        height = 3,
#        units = "in")
```

```{r}
susc_hz <- u1 | u2 | u3 | u4

# ggsave(here("workshop", "figures","susc_hz_plots.png"),
#        susc_hz,
#        width = 8,
#        height = 3,
#        units = "in")
```

```{r}
prev_hz <- p1 | p2 | p3 | p4

# ggsave(here("workshop", "figures","prev_hz_plots.png"),
#        prev_hz,
#        width = 8,
#        height = 3,
#        units = "in")
```



```{r}
rate_plot(u_seq, "m5a_rate")
spores_plot(u_seq, "spores_consumed_m5a")
u_plot(u_seq, "m5a_u")
prev_plot(u_seq, "m5a_I_end")
```



```{r}
rate_4 <- rate_plot(u_seq, "m4_rate")
rate_5 <- rate_plot(u_seq, "m5_rate")
rate_5a <- rate_plot(u_seq, "m5b_rate")

u_rate_plot <- rate_4 / rate_5 / rate_5a

# ggsave(here("workshop", "figures","u_full_rate_plots.png"),
#        u_rate_plot,
#        width = 3,
#        height = 8,
#        units = "in")
```

```{r}
spo_4 <- spores_plot(u_seq, "spores_consumed_m4")
spo_5 <- spores_plot(u_seq, "spores_consumed_m5")
spo_5a <- spores_plot(u_seq, "spores_consumed_m5b")

u_spores_plot <- spo_4 / spo_5 / spo_5a

# ggsave(here("workshop", "figures","u_full_spores_plots.png"),
#        u_spores_plot,
#        width = 3,
#        height = 8,
#        units = "in")
```

```{r}
susc_4 <- u_plot(u_seq, "m4_u")
susc_5 <- u_plot(u_seq, "m5_u")
susc_5a <- u_plot(u_seq, "m5b_u")

u_susc_plot <- susc_4 / susc_5 / susc_5a

# ggsave(here("workshop", "figures","u_full_susc_plots.png"),
#        u_susc_plot,
#        width = 3,
#        height = 8,
#        units = "in")
```


```{r}
prev_4 <- prev_plot(u_seq, "m4_I_end")
prev_5 <- prev_plot(u_seq, "m5_I_end")
prev_5a <- prev_plot(u_seq, "m5b_I_end")

u_prev_plot <- prev_4 / prev_5 / prev_5a

# ggsave(here("workshop", "figures","u_full_prev_plots.png"),
#        u_prev_plot,
#        width = 3,
#        height = 8,
#        units = "in")
```






Foraging - temp only plots


```{r}
t_a <- seq_plot(f_seq, "m2_rate") +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")

t_b <- algae_plot(f_seq, "m2_consumed") +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")

t_c <- spores_plot(f_seq, "m2_Z_end") +
  theme(plot.title = element_blank(), legend.position = "none")

temp_fora_plot <- t_a / t_b / t_c


# ggsave(here("workshop", "figures","temp_fora_plots.png"),
#        temp_fora_plot,
#        width = 3,
#        height = 8,
#        units = "in")
```

```{r}
t_d <- spores_plot(u_seq, "spores_consumed_m2") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")

t_e <- u_plot(u_seq, "m2_u") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")


t_f <- prev_plot(u_seq, "m2_I_end") + 
  theme(plot.title = element_blank(), legend.position = "none")


temp_inf_plot <- t_d / t_e / t_f

# ggsave(here("workshop", "figures","temp_inf_plots.png"),
#        temp_inf_plot,
#        width = 3,
#        height = 8,
#        units = "in")


```






resource only
```{r}
r_a <- seq_plot_temp(f_seq, "m3_rate") +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")

r_b <- algae_plot_temp(f_seq, "m3_consumed") +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")

r_c <- spores_plot_temp(f_seq, "m3_Z_end") + 
  theme(plot.title = element_blank(), legend.position = "none")


res_fora_plot <- r_a / r_b / r_c


# ggsave(here("workshop", "figures","res_fora_plots.png"),
#        res_fora_plot,
#        width = 3,
#        height = 8,
#        units = "in")
```


```{r}
r_d <- spores_plot_temp(u_seq, "spores_consumed_m3") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")

r_e <- u_plot_temp(u_seq, "m3_u") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")

r_f <- prev_plot_temp(u_seq, "m3_I_end") + 
  theme(plot.title = element_blank(), legend.position = "none")

res_inf_plot <- r_d / r_e / r_f

# ggsave(here("workshop", "figures","res_inf_plots.png"),
#        res_inf_plot,
#        width = 3,
#        height = 8,
#        units = "in")

```


additive only


```{r}
a_a <- seq_plot(f_seq, "m4_rate") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")


a_b <- algae_plot(f_seq, "m4_consumed") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")


a_c <- spores_plot(f_seq, "m4_Z_end") + 
  theme(plot.title = element_blank(), legend.position = "none")


add_fora_plot <- a_a / a_b / a_c


# ggsave(here("workshop", "figures","add_fora_plots.png"),
#        add_fora_plot,
#        width = 3,
#        height = 8,
#        units = "in")

```


```{r}
a_d <- spores_plot(u_seq, "spores_consumed_m4") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none", panel.background = element_rect(fill = "#ADD0E9"))

a_e <- u_plot(u_seq, "m4_u") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none", panel.background = element_rect(fill = "#ADD0E9"))

a_f <- prev_plot(u_seq, "m4_I_end") + 
  theme(plot.title = element_blank(), legend.position = "none", panel.background = element_rect(fill = "#ADD0E9"))

add_inf_plot <- a_d / a_e / a_f

# ggsave(here("workshop", "figures","add_inf_plots.png"),
#        add_inf_plot,
#        width = 3,
#        height = 8,
#        units = "in")

```


interactive only


```{r}
i_a <- seq_plot(f_seq, "m6c_rate") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none", panel.background = element_rect(fill = "#ADD0E9"))

i_b <- algae_plot(f_seq, "m6c_consumed") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none", panel.background = element_rect(fill = "#ADD0E9"))

i_c <- spores_plot(f_seq, "m6c_Z_end") + 
  theme(plot.title = element_blank(), legend.position = "none", panel.background = element_rect(fill = "#ADD0E9"))

int_fora_plot <- i_a / i_b / i_c

# ggsave(here("workshop", "figures","int_fora_plots.png"),
#        int_fora_plot,
#        width = 3,
#        height = 8,
#        units = "in")
```



```{r}
i_d <- spores_plot(u_seq, "spores_consumed_m5b") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")

i_e <- u_plot(u_seq, "m5b_u") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")

i_f <- prev_plot(u_seq, "m5b_I_end") + 
  theme(plot.title = element_blank(), legend.position = "none")

int_inf_plot <- i_d / i_e / i_f

# ggsave(here("workshop", "figures","int_inf_plots.png"),
#        int_inf_plot,
#        width = 3,
#        height = 8,
#        units = "in")
```



# data plots

```{r}
f_data <- f_seq %>% 
  dplyr::select(resource, temp, amt_diff, amt_rem_se, amt_init_mean) %>% 
  drop_na() %>%
  ggplot(., aes(x=resource, y=amt_diff, group = as.factor(temp), color = as.factor(temp))) + 
#  ggplot(., aes(x=amt_init_mean, y=amt_diff, group = as.factor(temp), color = as.factor(temp))) + 
  geom_point(size=3) +
  geom_linerange(size = 1, 
                 aes(ymin=amt_diff-1.96*amt_rem_se,
                     ymax=amt_diff+1.96*amt_rem_se,
                     color=as.factor(temp))) +
  #scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D")) +
  scale_color_manual(values = c("#FFC107", "#21918c", "#440154")) +
  scale_x_continuous(breaks = c(0.1, 0.5, 1.0)) + 
  theme(legend.position = "none", title = element_blank()) + 
  labs(x="Resource (mgC/L)", y="Resource difference (mgC/L)", color="Temperature", title = "")

#ggsave(here("workshop", "figures","f_data_new.png"),
ggsave(here("workshop", "figures","f_data.png"),
       f_data,
       width = 3,
       height = 3,
       units = "in")
```

```{r}
prev_data <- u_seq %>% filter(!is.na(prev)) %>% 
ggplot(.,aes(x=resource, 
             y=prev, 
             color=as.factor(temp))) + 
  geom_point(size = 3) + 
  geom_linerange(size=1,
                 aes(ymin = conf$lower, ymax=conf$upper, color=as.factor(temp))) +
  #scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D")) +
  scale_color_manual(values = c("#FFC107", "#21918c", "#440154")) +
  scale_x_continuous(breaks = c(0.1, 0.5, 1.0)) + 
  scale_y_continuous(breaks = c(0, 0.5, 1.0)) + 
  theme(legend.position = "none", title = element_blank()) + 
  labs(x="Resource (mgC/L)", y="Probability of Infection", color="Temperature", title = "")

ggsave(here("workshop", "figures","prev_data.png"),
       prev_data,
       width = 3,
       height = 3,
       units = "in")
```






# 3D plots





```{r}
# u_seq %>% ggplot(., aes(x = resource, y = temp, fill = spores_consumed_m5)) + 
#   geom_tile() + 
#   scale_fill_viridis_c(option = "magma") + 
#   labs(title = "Spores Consumed")

u_seq %>% ggplot(., aes(x = resource, y = temp, z = m5_u, fill = m5_u)) + 
  geom_tile() + 
  geom_contour() + 
  metR::geom_text_contour(stroke = 0.15, label.placer = label_placer_n()) + 
  scale_fill_viridis_c(option = "mako", direction = 1) + 
  labs(x = "Resource", y = "Temperature", title = "Per-Spore Susceptibility") +
  theme(legend.position = "none")

u_seq %>% ggplot(., aes(x = resource, y = temp, z = m5_I_end, fill = m5_I_end)) + 
  geom_tile() + 
  geom_contour() + 
  metR::geom_text_contour(stroke = 0.15, label.placer = label_placer_n()) + 
  scale_fill_viridis_c(option = "magma", direction = 1) + 
  labs(x = "Resource", y = "Temperature", title = "Probability of Infection") +
  theme(legend.position = "none")



```


```{r}
u_seq %>% ggplot(., aes(x = spores_consumed_m5, y = m5_u, size = m5_I_end, color = temp)) + 
  geom_point()
u_seq %>% filter(temp %in% seq(15, 25, by = 1) & resource %in% seq(0.1, 1, by = 0.2)) %>%
  ggplot(., aes(x = spores_consumed_m5, y = m5_u, 
                size = m5_I_end, color = temp, shape = as.factor(resource), group = as.factor(temp))) + 
  geom_point() + 
  geom_line(size = 1) + 
  scale_color_viridis_c()

```



```{r, eval=F}
plot_ly(u_seq, x = ~temp, y = ~resource, z = ~m2_I_end, color = ~m2_I_end)
plot_ly(u_seq, x = ~temp, y = ~resource, z = ~m3_I_end, color = ~m3_I_end)
plot_ly(u_seq, x = ~temp, y = ~resource, z = ~m4_I_end, color = ~m4_I_end)
plot_ly(u_seq, x = ~temp, y = ~resource, z = ~m5_I_end, color = ~m5_I_end)
```

```{r, eval=F}
plot_ly(u_seq, x = ~temp, y = ~resource, z = ~m5_u, color = ~m5_I_end)
```

```{r, eval=F}
plot_ly(u_seq, x = ~spores_consumed_m4, y = ~m4_u, z = ~m4_I_end, color = ~m4_I_end)
plot_ly(u_seq, x = ~spores_consumed_m5, y = ~m5_u, z = ~m5_I_end, color = ~m5_I_end)
```


