---
title: "model results"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = F}
library(here)
source(here("base","src.R"))
```



Model results
```{r, results}
# summary(readRDS(here("mle","m0_f_fit.rds"))) #no size correction
# summary(readRDS(here("mle","m1_f_fit.rds"))) #with size correction
# summary(readRDS(here("mle","m2_f_fit.rds"))) #temperature-dependent
# summary(readRDS(here("mle","m3_f_fit.rds"))) #resource-dependent
# summary(readRDS(here("mle","m4_f_fit.rds"))) #temperature and resource-dependent
# summary(readRDS(here("mle","m5_f_fit.rds"))) #resource on temp effect
# summary(readRDS(here("mle","m6_f_fit.rds"))) #temp on resource effect
# summary(readRDS(here("mle","m7_f_fit.rds"))) #full interaction
```



```{r, AIC}
m0 <- readRDS(here("mle","m0_f_fit.rds"))
m1 <- readRDS(here("mle","m1_f_fit.rds"))
m2 <- readRDS(here("mle","m2_f_fit.rds"))
m3 <- readRDS(here("mle","m3_f_fit.rds"))
m3a <- readRDS(here("mle","m3a_f_fit.rds"))
m4 <- readRDS(here("mle","m4_f_fit.rds"))
m4a <- readRDS(here("mle","m4a_f_fit.rds"))
```


```{r}
m5 <- readRDS(here("mle","m5_f_fit.rds"))
m5a <- readRDS(here("mle","m5a_f_fit.rds"))
m5b <- readRDS(here("mle","m5b_f_fit.rds"))
m5c <- readRDS(here("mle","m5c_f_fit.rds"))
m6 <- readRDS(here("mle","m6_f_fit.rds"))
m6a <- readRDS(here("mle","m6a_f_fit.rds"))
m6b <- readRDS(here("mle","m6b_f_fit.rds"))
m6c <- readRDS(here("mle","m6c_f_fit.rds"))
m7 <- readRDS(here("mle","m7_f_fit.rds"))
m7a <- readRDS(here("mle","m7a_f_fit.rds"))
m7b <- readRDS(here("mle","m7b_f_fit.rds"))
m7c <- readRDS(here("mle","m7c_f_fit.rds"))
m7d <- readRDS(here("mle","m7d_f_fit.rds"))
m7e <- readRDS(here("mle","m7e_f_fit.rds"))
```

```{r}
m0@coef
m1@coef
m2@coef
m3@coef
m3a@coef
m4@coef
# m4a@coef
```


```{r}
m5@coef
m5a@coef
m5b@coef
m5c@coef
```


```{r}
m6@coef
m6a@coef
m6b@coef
m6c@coef
```


```{r}
m7@coef
m7a@coef
m7b@coef
m7c@coef
m7d@coef
m7e@coef
```

```{r}
m0@min
m1@min
m2@min
m3@min
m3a@min
m4@min
# m4a@min
m5@min
m6@min
m7@min
```

# Check this formula and the values from model output

```{r}
getAIC <- function(n, L){
  return(2*length(n)-(2*-L))
}
```


```{r}
# getAIC(m0@coef, m0@min)
# getAIC(m1@coef, m1@min)
# getAIC(m2@coef, m2@min)
# getAIC(m3@coef, m3@min)
# getAIC(m3a@coef, m3a@min)
getAIC(m4@coef, m4@min)
# getAIC(m4a@coef, m4a@min)
```


```{r}
getAIC(m5@coef, m5@min)
getAIC(m5a@coef, m5a@min)
getAIC(m5b@coef, m5b@min)
getAIC(m5c@coef, m5c@min)
```

```{r}
getAIC(m6@coef, m6@min)
getAIC(m6a@coef, m6a@min)
getAIC(m6b@coef, m6b@min)
getAIC(m6c@coef, m6c@min)
```

```{r}
getAIC(m7@coef, m7@min)
getAIC(m7a@coef, m7a@min)
getAIC(m7b@coef, m7b@min)
getAIC(m7c@coef, m7c@min)
getAIC(m7d@coef, m7d@min)
getAIC(m7e@coef, m7e@min)
```

```{r}
m7@coef
arr_t_vec <- c(146.6, 124.8, 118.4)
resource <- c(0.1, 0.5, 1)
arr_t_df <- tibble(arr_t=arr_t_vec,
             resource=resource)

ggplot(arr_t_df,aes(x=resource, y=arr_t_vec)) + geom_line()
ggplot(arr_t_df,aes(x=log(resource), y=arr_t_vec)) + geom_line()
ggplot(arr_t_df,aes(x=resource, y=arr_t_vec*exp(resource))) + geom_line()

summary(lm(arr_t_vec ~ resource))
summary(lm(arr_t_vec ~ log(resource)))
summary(lm(arr_t_vec*exp(resource) ~ resource))

```

```{r}
m7@coef
h_vec <- c(4.57, 0.187, 0.0683)
temp <- c(15,20,25)

h_df <- tibble(h=h_vec,
               temp=temp)

ggplot(h_df, aes(x=temp, y=h)) + geom_line()
ggplot(h_df, aes(x=log(temp), y=h)) + geom_line()
ggplot(h_df, aes(x=temp, y=log(h))) + geom_line()


```



