---
title: "model_fits_viz_final"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r, message = F}
library(here)
source(here("base","src.R"))
library(ggnewscale)
```


```{r, data}
data <- readRDS(here("processed_data","foraging_raw.rds"))
data_summ <- readRDS(here("processed_data", "foraging.rds"))

beta_summ <- readRDS(here("processed_data", "beta_summary.rds"))
beta_summ %<>% filter(temp %in% const_temp) %>% filter(species == "D") %>% mutate(temp = as.numeric(temp))

m0 <- readRDS(here("mle", "m0_f_fit.rds"))
#m1 <- readRDS(here("mle", "final", "m1_u_f_fit.rds"))
m1 <- readRDS(here("mle", "update", "m1_fit.rds")) #updated version from dynamic u method
m2 <- readRDS(here("mle", "final", "m2_u_f_fit.rds"))
m3 <- readRDS(here("mle", "final", "m3_u_f_fit.rds"))
m3b <- readRDS(here("mle", "final", "m3b_u_f_fit.rds"))
m4 <- readRDS(here("mle", "final", "m4_u_f_fit.rds"))
m4b <- readRDS(here("mle", "final", "m4b_u_f_fit.rds"))
m4_sep <- readRDS(here("mle", "final", "m4_sep_u_f_fit.rds"))
m6 <- readRDS(here("mle", "final", "m6_u_f_fit.rds"))
m8 <- readRDS(here("mle", "final", "m8_u_f_fit.rds"))
```

```{r}
m0_coef <- m0@coef

gamma <- 2
ref_t <- 15
vol <- 15
z <- 200
mean_time <- mean(data$time/60/24)
mean_length <- mean(data$mm, na.rm=T)
```

```{r, units}
data_summ %<>% mutate(rate_len_mean = rate_len_mean*60*24)
```


```{r}
temp_range <- seq(15,25,by=0.1)
resource_range <- seq(0.1,1,by=0.01)

seq_data <- tibble(temp=c(),
                   resourece=c())

for (i in 1:length(temp_range)){
  tmp <- tibble(temp = temp_range[i],
                resource = seq(0.1,1,by=0.01))
  seq_data %<>% bind_rows(., tmp)
}

m7_range <- seq_data
```

```{r, echo=F}
seq_data %<>% mutate(temp_factor = as.factor(case_when(temp==15 ~ 15,
                                             temp==20 ~ 20,
                                             temp==25 ~ 25)))
```

```{r}
seq_plot <- function(rate){
  seq_data %>% na.omit() %>%
  ggplot(.) +
  geom_line(aes(x=resource, 
                y=!!sym(rate),
                group=temp_factor,
                color=as.factor(temp_factor))) +
  geom_point(data=data_summ, aes(x=resource, 
                            y=rate_len_mean, 
                            group = as.factor(temp), 
                            color = as.factor(temp),
                            shape = as.factor(temp))) + 
  labs(x="Resource", y="Foraging rate (mL/day)", color="Temperature", shape="Temperature", title = "") 
}

seq_plot_temp <- function(rate){
  seq_data %>% na.omit() %>% filter(resource %in% c(0.1, 0.5, 1)) %>%
  ggplot(.) +
  geom_line(aes(x=temp, 
                y=!!sym(rate),
                group=resource,
                color=as.factor(resource))) +
  geom_point(data=data_summ, aes(x=temp, 
                            y=rate_len_mean, 
                            group = as.factor(resource), 
                            color = as.factor(resource),
                            shape = as.factor(resource))) + 
  labs(x="Temperature", y="Foraging rate (mL/day)", color="", shape="", title = "") 
}

```

```{r}
seq_plot_prev <- function(prev){
  seq_data %>% filter(temp %in% c(15, 20, 25)) %>%
  ggplot(.) +
  geom_line(aes(x=resource, 
                y=!!sym(prev),
                group=temp,
                color=as.factor(temp))) +
  geom_point(data=beta_summ, aes(x=resource, 
                            y=prev, 
                            group = as.factor(temp), 
                            color = as.factor(temp),
                            shape = as.factor(temp))) + 
  labs(x="Resource", y="Prevalence", color="Temperature", shape="Temperature", title = "") 
}

seq_plot_prev_temp <- function(prev){
  seq_data %>% filter(resource %in% c(0.1, 0.5, 1)) %>%
  ggplot(.) +
  geom_line(aes(x=temp, 
                y=!!sym(prev),
                group=resource,
                color=as.factor(resource))) +
  geom_point(data=beta_summ, aes(x=temp, 
                            y=prev, 
                            group = as.factor(resource), 
                            color = as.factor(resource),
                            shape = as.factor(resource))) + 
  labs(x="Temperature", y="Prevalence", color="Resource", shape="Resource", title = "") 
}
```

```{r}
seq_plot_beta <- function(beta){
  seq_data %>% filter(temp %in% c(15, 20, 25)) %>%
  ggplot(.) +
  geom_line(aes(x=resource, 
                y=!!sym(beta),
                group=temp,
                color=as.factor(temp))) +
  geom_point(data=beta_summ, aes(x=resource, 
                            y=beta.est, 
                            group = as.factor(temp), 
                            color = as.factor(temp),
                            shape = as.factor(temp))) + 
  labs(x="Resource", y="Beta", color="Temperature", shape="Temperature", title = "") 
}

seq_plot_beta_temp <- function(beta){
  seq_data %>% filter(resource %in% c(0.1, 0.5, 1)) %>%
  ggplot(.) +
  geom_line(aes(x=temp, 
                y=!!sym(beta),
                group=resource,
                color=as.factor(resource))) +
  geom_point(data=beta_summ, aes(x=temp, 
                            y=beta.est, 
                            group = as.factor(resource), 
                            color = as.factor(resource),
                            shape = as.factor(resource))) + 
  labs(x="Temperature", y="Beta", color="Resource", shape="Resource", title = "") 
}
```


```{r}
m0_f <- as.numeric(m0_coef)
data_summ %<>% mutate(m0_rate = m0_f)
```

```{r}
m1_coef <- coef(m1)
m1_f <- as.numeric(m1_coef[1])
m1_u <- as.numeric(m1_coef[2])



```



```{r}
m3b_coef <- coef(m3b)
m3b_f <- as.numeric(m3b_coef[1])
m3b_h <- as.numeric(m3b_coef[2])
m3b_u <- as.numeric(m3b_coef[3])
m3b_k <- as.numeric(m3b_coef[4])*10000

data_summ %<>% mutate(m3b_rate = ((m3b_f)/(1+m3b_f*m3b_h*resource)))

seq_data %<>% mutate(m3b_rate = ((m3b_f)/(1+m3b_f*m3b_h*resource)),
                     m3b_prev = 1-exp(-m3b_f*(m3b_u*exp(m3b_k*resource))*z),
                     m3b_u_k = m3b_u*exp(m3b_k*resource))

m3b_rate_plot <- seq_plot("m3b_rate")
m3b_prev_plot <- seq_plot_prev("m3b_prev")

m3b_rate_plot
m3b_prev_plot

seq_data %>% ggplot(.,aes(x=resource, y=m3b_u_k)) + geom_line()
```


```{r}
get_rate <- function(f, arr, temp, h, resource){
  ((f*exp(arr*(1/ref_t - 1/temp)))/(1+f*exp(arr*(1/ref_t - 1/temp))*h*resource))
}

get_prev <- function(f, u, arr, temp, k, resource, z){
  1-exp(-f*(u*exp(arr*(1/ref_t-1/temp))*resource/(k + resource))*z)
}
```


```{r}
m4_coef <- coef(m4)
m4_f <- as.numeric(m4_coef[1])
m4_arr <- as.numeric(m4_coef[2])
m4_h <- as.numeric(m4_coef[3])
m4_u <- as.numeric(m4_coef[4])
m4_arr_u <- as.numeric(m4_coef[5])
m4_k <- as.numeric(m4_coef[6])

data_summ %<>% mutate(m4_rate = mapply(get_rate, f=m4_f, arr=m4_arr, temp=data_summ$temp, h=m4_h, resource=data_summ$resource))

seq_data %<>% mutate(m4_rate = mapply(get_rate, f=m4_f, arr=m4_arr, temp=seq_data$temp, h=m4_h, resource=seq_data$resource),
                     m4_prev = mapply(get_prev, f=m4_f, u=m4_u, arr=m4_arr_u, temp=seq_data$temp, k=m4_k, resource = seq_data$resource, z=z))
```

```{r}
m4_rate_plot <- seq_plot("m4_rate")
m4_prev_plot <- seq_plot_prev("m4_prev")
```

```{r}
m4_rate_plot
seq_plot_temp("m4_rate")
m4_prev_plot
seq_plot_prev_temp("m4_prev")
```


```{r}
m4b_coef <- coef(m4b)
m4b_f <- as.numeric(m4b_coef[1])
m4b_arr <- as.numeric(m4b_coef[2])
m4b_h <- as.numeric(m4b_coef[3])
m4b_u <- as.numeric(m4b_coef[4])
m4b_arr_u <- as.numeric(m4b_coef[5])
m4b_k <- as.numeric(m4b_coef[6])*10

data_summ %<>% mutate(m4b_rate = mapply(get_rate, f=m4b_f, arr=m4b_arr, temp=data_summ$temp, h=m4b_h, resource=data_summ$resource))

seq_data %<>% mutate(m4b_rate = mapply(get_rate, f=m4b_f, arr=m4b_arr, temp=seq_data$temp, h=m4b_h, resource=seq_data$resource),
                     m4b_prev = 1-exp(-m4b_f*(m4b_u*exp(m4b_arr*(1/ref_t-1/temp))*exp(m4b_k*resource)*z)),
                     m4b_u_k = m4b_u*exp(m4b_arr*(1/ref_t-1/temp))*exp(m4b_k*resource))

seq_plot("m4b_rate")
seq_plot_prev("m4b_prev")

seq_data %>% filter(temp %in% c(15, 20, 25)) %>%
  ggplot(.) +
  geom_line(aes(x=resource, 
                y=m4b_u_k,
                group=temp,
                color=as.factor(temp)))
```

```{r}
m4_sep_coef <- coef(m4_sep)
m4_sep_f <- as.numeric(m4_sep_coef[1])
m4_sep_arr <- as.numeric(m4_sep_coef[2])
m4_sep_h <- as.numeric(m4_sep_coef[3])
m4_sep_u <- as.numeric(m4_sep_coef[4])
m4_sep_arr_u <- as.numeric(m4_sep_coef[5])
m4_sep_k_15 <- as.numeric(m4_sep_coef[6])
m4_sep_k_20 <- as.numeric(m4_sep_coef[7])
m4_sep_k_25 <- as.numeric(m4_sep_coef[8])
```

```{r}
seq_data %<>% mutate(m4_sep_rate = mapply(get_rate, f=m4_sep_f, arr=m4_sep_arr, temp=seq_data$temp, h=m4_sep_h, resource=seq_data$resource))

m4_sep_data <- seq_data %>% filter(temp %in% c(15,20,25)) %>% mutate(
                     m4_sep_prev = case_when(temp == 15 ~ 1-exp(-m4_sep_f*(m4_sep_u*exp(m4_sep_arr*(1/ref_t-1/temp))*exp(m4_sep_k_15*resource)*z)),
                                             temp == 20 ~ 1-exp(-m4_sep_f*(m4_sep_u*exp(m4_sep_arr*(1/ref_t-1/temp))*exp(m4_sep_k_20*resource)*z)),
                                             temp == 25 ~ 1-exp(-m4_sep_f*(m4_sep_u*exp(m4_sep_arr*(1/ref_t-1/temp))*exp(m4_sep_k_25*resource)*z))),
                     m4_u_k = case_when(temp == 15 ~ m4_sep_u*exp(m4_sep_arr*(1/ref_t-1/temp))*exp(m4_sep_k_15*resource),
                                        temp == 20 ~ m4_sep_u*exp(m4_sep_arr*(1/ref_t-1/temp))*exp(m4_sep_k_20*resource),
                                        temp == 25 ~ m4_sep_u*exp(m4_sep_arr*(1/ref_t-1/temp))*exp(m4_sep_k_25*resource)))
```

```{r}
m4_sep_data %>% filter(temp %in% c(15, 20, 25)) %>%
  ggplot(.) +
  geom_line(aes(x=resource, 
                y=m4_sep_prev,
                group=temp,
                color=as.factor(temp)))
m4_sep_data %>% filter(temp %in% c(15, 20, 25)) %>%
  ggplot(.) +
  geom_line(aes(x=resource, 
                y=m4_u_k,
                group=temp,
                color=as.factor(temp)))
```






```{r}
m6c_coef <- coef(m6)
m6c_f <- as.numeric(m6c_coef[1])
m6c_arr <- as.numeric(m6c_coef[2])
m6c_h <- as.numeric(m6c_coef[3])
m6c_u <- as.numeric(m6c_coef[4])
m6c_arr_u <- as.numeric(m6c_coef[5])
m6c_k <- as.numeric(m6c_coef[6])
m6c_w <- as.numeric(m6c_coef[7])
m6c_w_u <- as.numeric(m6c_coef[8])

  data_summ %<>% mutate(m6c_rate = mapply(get_rate, f=m6c_f, arr=m6c_arr, h=m6c_h*exp(m6c_w*data_summ$temp), temp=data_summ$temp, resource=data_summ$resource))
  
  seq_data %<>% mutate(m6c_rate = mapply(get_rate, f=m6c_f, arr=m6c_arr, h=m6c_h*exp(m6c_w*seq_data$temp), temp=seq_data$temp, resource=seq_data$resource),
                       m6c_prev = mapply(get_prev, f=m6c_f, u=m6c_u, arr=m6c_arr_u, k=m6c_k*exp(m6c_w_u*seq_data$temp), temp=seq_data$temp, resource=seq_data$resource, z=z))
```

```{r}
m6_plot <- seq_plot("m6c_rate")
m6_prev_plot <- seq_plot_prev("m6c_prev")
```

```{r}
m6_plot
m6_prev_plot
seq_plot_prev_temp("m6c_prev")
```

```{r}
m8_coef <- coef(m8)
m8_f <- as.numeric(m8_coef[1])
m8_arr <- as.numeric(m8_coef[2])
m8_h <- as.numeric(m8_coef[3])
m8_u <- as.numeric(m8_coef[4])
m8_arr_u <- as.numeric(m8_coef[5])
m8_w <- as.numeric(m8_coef[6])


  seq_data %<>% mutate(m8_rate = mapply(get_rate, f=m8_f, arr=m8_arr, h=m8_h*exp(m8_w*seq_data$temp), temp=seq_data$temp, resource=seq_data$resource),
                       m8_prev = mapply(get_prev, f=m8_f, u=m8_u, arr=m8_arr_u, temp=seq_data$temp, k=0, resource=seq_data$resource, z=z),
                       m8_u_full = m8_u*exp(m8_arr_u*(1/ref_t-1/temp)),
                       m8_force = m8_rate*m8_u_full,
                       m8_beta = m8_rate*m8_u_full)
```

```{r}
seq_plot("m8_rate")
seq_plot_prev("m8_prev")
seq_plot_prev_temp("m8_prev")

seq_plot_beta("m8_beta")
seq_plot_beta_temp("m8_beta")
```

```{r}
seq_data %>% ggplot(.,aes(x=resource, y=temp, fill=m8_rate)) + geom_tile() + scale_fill_viridis_c()
seq_data %>% ggplot(.,aes(x=resource, y=temp, fill=m8_u)) + geom_tile() + scale_fill_viridis_c()
seq_data %>% ggplot(.,aes(x=resource, y=temp, fill=log(m8_force))) + geom_tile() + scale_fill_viridis_c()
```


```{r}
fora_data <- seq_data %>% filter(temp %in% c(15,20,25)) %>% filter(resource %in% c(0.1,0.5,1.0))
fora_data %<>% left_join(.,beta_summ)
fora_data %<>% mutate(u=beta.est/m8_rate)
```

```{r}
library(patchwork)

theme_set(theme_bw(base_size=8))

symbol_size <- 4

p1 <- fora_data %>% na.omit() %>% 
  ggplot(., aes(x=as.factor(resource), y=m8_rate, color=as.factor(temp))) +
  geom_point(size=symbol_size) +
  scale_color_manual(values = c("#FFC107", "#1E88E5", "#D81B60")) +
  labs(x="Resource", y="f - clearance rate (mL/day)", color="Temperature") +
  theme(legend.position = "none") +
  guides(color = guide_legend(reverse=T))

p2 <- fora_data %>% na.omit() %>% 
  ggplot(., aes(x=as.factor(resource), y=beta.est, color=as.factor(temp))) +
  geom_point(size=symbol_size) +
  scale_color_manual(values = c("#FFC107", "#1E88E5", "#D81B60")) +
  labs(x="Resource", y="beta (derived from infection assay)", color="Temperature") +
  theme(legend.position = "none") +
  guides(color = guide_legend(reverse=T))

p3 <- fora_data %>% na.omit() %>% 
  ggplot(., aes(x=as.factor(resource), y=u, color=as.factor(temp))) +
  geom_point(size=symbol_size) +
  scale_color_manual(values = c("#FFC107", "#1E88E5", "#D81B60")) +
  labs(x="Resource", y="per-spore susceptibility (beta/f)", color="Temperature") +
  guides(color = guide_legend(reverse=T))

fora_data %>% na.omit() %>% 
  ggplot(., aes(x=as.factor(resource), y=m8_u, color=as.factor(temp))) +
  geom_point(size=symbol_size) +
  scale_color_manual(values = c("#FFC107", "#1E88E5", "#D81B60")) +
  labs(x="Resource", y="per-spore susceptibility (beta/f)", color="Temperature") +
  guides(color = guide_legend(reverse=T))

fig <- p1|p2|p3

ggsave(here("f_beta_u.png"), plot = fig)

```





