---
title: "model fits visualized"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = F}
library(here)
source(here("base","src.R"))
library(ggnewscale)
```


First, make basic plot that shows temperature gradient on x-axis, foraging rate on y-axis, and a geom layer for resource concentration. This will be the actual data and will be consistent between each of the model fit visualizations.

```{r, data}
data <- readRDS(here("processed_data","foraging_raw.rds"))
data_summ <- readRDS(here("processed_data", "foraging.rds"))
m0 <- readRDS(here("mle", "m0_f_fit.rds"))
m1 <- readRDS(here("mle", "m1_f_fit.rds"))
m2 <- readRDS(here("mle", "m2_f_fit.rds"))
m3 <- readRDS(here("mle", "m3_f_fit.rds"))
m4 <- readRDS(here("mle", "m4_f_fit.rds"))
```

```{r}
m0_coef <- m0@coef
m1_coef <- m1@coef
m2_coef <- m2@coef
m3_coef <- m3@coef
m4_coef <- m4@coef

gamma <- 2
ref_t <- 15
```



```{r}
data_summ %>% ggplot(., aes(x=as.factor(temp), y=rate_mean, color=as.factor(resource))) + 
  geom_point() + 
  geom_linerange(aes(ymin=rate_mean-rate_se, 
                     ymax=rate_mean+rate_se)) +
  labs(x="Temperature", y="Foraging rate (mL/min)", color="Resource")
```



Now let's get the results from the model
```{r}
data_summ %<>% mutate(m0_rate = as.numeric(m0_coef))
```

```{r}
data_summ %>% ggplot(., aes(x=as.factor(temp), 
                          y=rate_mean, 
                          group = as.factor(resource), 
                          color = as.factor(resource),
                          shape = as.factor(resource))) + 
geom_point() + 
geom_linerange(aes(ymin=rate_mean-rate_se, 
                 ymax=rate_mean+rate_se)) +
labs(x="Temperature", y="Foraging rate (mL/min)", color="Resource", shape="Resource", title = ) +
new_scale_color() +
geom_point(aes(x=as.factor(temp), 
               y=m0_rate, 
               shape=as.factor(resource))) +
scale_color_manual(name="",values="black")
```




```{r}
data_summ %<>% mutate(m1_rate = mm_mean^gamma*as.numeric(m1_coef))

data_summ %>% ggplot(., aes(x=as.factor(temp), 
                          y=rate_mean, 
                          group = as.factor(resource), 
                          color = as.factor(resource),
                          shape = as.factor(resource))) + 
geom_point() + 
geom_linerange(aes(ymin=rate_mean-rate_se, 
                 ymax=rate_mean+rate_se)) +
labs(x="Temperature", y="Foraging rate (mL/min)", color="Resource", shape="Resource", title = ) +
new_scale_color() +
geom_point(aes(x=as.factor(temp), 
               y=m1_rate, 
               shape=as.factor(resource))) +
scale_color_manual(name="",values="black")
```


```{r}
m2_coef
m2_f <- as.numeric(m2_coef[1])
m2_arr <- as.numeric(m2_coef[2])

data_summ %<>% mutate(m2_rate = (mm_mean^gamma)*m2_f*exp(m2_arr*(1/ref_t - 1/temp)))
```

```{r}
data_summ %>% ggplot(., aes(x=as.factor(temp), 
                          y=rate_mean, 
                          group = as.factor(resource), 
                          color = as.factor(resource),
                          shape = as.factor(resource))) + 
geom_point() + 
geom_linerange(aes(ymin=rate_mean-rate_se, 
                 ymax=rate_mean+rate_se)) +
labs(x="Temperature", y="Foraging rate (mL/min)", color="Resource", shape="Resource", 
     title = "Temperature-dependent model") +
new_scale_color() +
geom_point(aes(x=as.factor(temp), 
               y=m2_rate, 
               shape=as.factor(resource))) +
scale_color_manual(name="",values="black")
```

```{r}
m3_coef
m3_f <- as.numeric(m3_coef[1])
m3_h <- as.numeric(m3_coef[2])

data_summ %<>% mutate(m3_rate = ((m3_f*mm_mean^gamma*resource)/(1+m3_f*mm_mean^gamma*m3_h*resource)))
```

```{r}
data_summ %>% ggplot(., aes(x=as.factor(temp), 
                          y=rate_mean, 
                          group = as.factor(resource), 
                          color = as.factor(resource),
                          shape = as.factor(resource))) + 
geom_point() + 
geom_linerange(aes(ymin=rate_mean-rate_se, 
                 ymax=rate_mean+rate_se)) +
labs(x="Temperature", y="Foraging rate (mL/min)", color="Resource", shape="Resource", 
     title = "Resource-dependent model") +
new_scale_color() +
geom_point(aes(x=as.factor(temp), 
               y=m3_rate, 
               shape=as.factor(resource))) +
scale_color_manual(name="",values="black")
```



```{r}
m4_coef
m4_f <- as.numeric(m4_coef[1])
m4_arr <- as.numeric(m4_coef[2])
m4_h <- as.numeric(m4_coef[3])

data_summ %<>% mutate(m4_rate = ((m4_f*exp(m4_arr*(1/ref_t - 1/temp))*(mm_mean^gamma)*resource)/
                                   (1+m4_f*exp(m4_arr*(1/ref_t - 1/temp))*m4_h*(mm_mean^gamma)*resource)))
```

```{r}
data_summ %>% ggplot(., aes(x=as.factor(temp), 
                          y=rate_mean, 
                          color = as.factor(resource))) + 
geom_point() + 
geom_linerange(aes(ymin=rate_mean-rate_se, 
                 ymax=rate_mean+rate_se)) +
labs(x="Temperature", y="Foraging rate (mL/min)", color="Resource", shape="Resource", 
     title = "Temperature and Resource-dependent model") +
new_scale_color() +
geom_point(aes(x=as.factor(temp), 
               y=m4_rate, 
               shape=as.factor(resource))) +
scale_color_manual(name="",values=c("black"))
```


