---
title: "temp_fig"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(here)
source(here("base","src.R"))
library(ggnewscale)
library(patchwork)
```

Formatting
```{r}
theme_set(theme_bw(base_size = 10))

```




```{r}
f_seq <- readRDS(file=here("model_fitting", "foraging", "rate_fit.rds"))
u_seq <- readRDS(file = here("model_fitting", "combined", "seq_data.rds"))
```

```{r}
seq_plot <- function(seq_data, rate){
  seq_data %>% filter(temp %in% c(15,20,25)) %>%
  ggplot(.) +
  geom_line(aes(x=resource, 
                y=!!sym(rate),
                group=temp_factor,
                color=as.factor(temp_factor)),
            size = 1) +
  geom_point(aes(x=resource, 
                  y=rate_len_mean, 
                  group = as.factor(temp), 
                  color = as.factor(temp)),
             size=3) + 
    geom_linerange(aes(x=resource, 
                       ymin=rate_len_mean-rate_len_mean_se,
                       ymax=rate_len_mean+rate_len_mean_se,
                       color=as.factor(temp))) +
#    scale_color_manual(values = c("#FFC107", "#1E88E5", "#D81B60")) +
    scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D")) +
  labs(x="Resource (mgC/L)", y="Foraging rate (mL/day)", color="Temperature", shape="Temperature", title = "") 
}

seq_plot(f_seq, "m1_rate")
```


```{r}
seq_plot_temp <- function(seq_data, rate){
  seq_data %>% filter(resource %in% c(0.1, 0.5, 1)) %>%
  ggplot(.) +
  geom_line(aes(x=temp, 
                y=!!sym(rate),
                group=resource,
                color=as.factor(resource)),
            size=1) +
  geom_point(aes(x=temp, 
                  y=rate_len_mean, 
                  group = as.factor(resource), 
                  color = as.factor(resource)),
                 size=3) +
        geom_linerange(aes(x=temp, 
                       ymin=rate_len_mean-rate_len_mean_se,
                       ymax=rate_len_mean+rate_len_mean_se,
                       color=as.factor(resource))) + 
    scale_color_manual(values = c("#CABD88", "#CA5216", "#65320D")) +
  labs(x="Temperature", y="Foraging rate (mL/day)", color="", shape="", title = "") 
}

seq_plot_temp(f_seq, "m1_rate")

```


```{r}
spores_plot <- function(seq_data, var){
seq_data %>% filter(temp %in% const_temp) %>% 
  ggplot(., aes(x=resource, y=!!sym(var), color=as.factor(temp), group = as.factor(temp))) + 
  geom_line(size = 1) + 
  labs(x = "Resource (mgC/L)", 
       y = "Spores consumed",
       color = "Temp") + 
  scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D"))
}

spores_plot_temp <- function(seq_data, var){
seq_data %>% filter(resource %in% c(0.1, 0.5, 1)) %>% 
  ggplot(., aes(x=temp, y=!!sym(var), color=as.factor(resource), group = as.factor(resource))) + 
  geom_line(size = 1) + 
  labs(x = "Temperature (C)", 
       y = "Spores consumed",
       color = "Resource (mgC/L)") + 
  scale_color_manual(values = c("#CABD88", "#CA5216", "#65320D"))
}

spores_plot(f_seq, "m1_Z_end")

```


```{r}
prev_plot <- function(seq_data, var){
  seq_data %>% filter(temp %in% const_temp) %>% 
    ggplot(.,aes(x=resource, 
                 y=!!sym(var), 
                 color=as.factor(temp))) + 
    geom_line(size=1) +
    scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D")) +
    new_scale_color() + 
    geom_point(aes(x=resource, y=prev, color=as.factor(temp)), size=3) + 
    geom_linerange(aes(ymin = conf$lower, ymax=conf$upper, color=as.factor(temp))) +
    scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D")) +
    labs(x="Resource (mgC/L)", y="Probability of Infection", color="Temperature", title = "")
}

prev_plot_temp <- function(seq_data, var){
  seq_data %>% filter(resource %in% c(0.1, 0.5, 1)) %>% 
    ggplot(.,aes(x=temp, 
                 y=!!sym(var), 
                 color=as.factor(resource))) + 
    geom_line(size=1) +
    scale_color_manual(values = c("#CABD88", "#CA5216", "#65320D")) +
    new_scale_color() + 
    geom_point(aes(x=temp, y=prev, color=as.factor(resource)), size=3) + 
    geom_linerange(aes(ymin = conf$lower, ymax=conf$upper, color=as.factor(resource))) +
    scale_color_manual(values = c("#CABD88", "#CA5216", "#65320D")) +
    labs(x="Temperature (C) ", y="Probability of Infection", color="Resource (mgC/L)", title = "")
}

prev_plot(u_seq, "m1_I_end")
```


```{r}
rate_plot <- function(seq_data, var){
  seq_data %>% filter(temp %in% const_temp) %>% 
    ggplot(.,aes(x=resource, y=!!sym(var), color=as.factor(temp))) + 
      geom_line() +
      new_scale_color() + 
      geom_point(aes(x=resource, y=rate_mean_ml_day, color=as.factor(temp)), size=3, shape = 1) + 
      labs(x = "Resource (mgC/L)", y = "Foraging rate (mL/day)", title="")
}

rate_plot(u_seq, "m1_rate")

```


```{r}
u_plot <- function(seq_data, var){
  seq_data %>% 
    filter(temp %in% const_temp) %>% 
    ggplot(.,aes(x=resource, y=!!sym(var), color=as.factor(temp))) + 
    geom_line(size = 1) + 
    scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D")) +
    labs(x = "Resource (mgC/L)", y = "Per-Spore Susceptibility", color = "Temp", title = "")
}

u_plot_temp <- function(seq_data, var){
  seq_data %>% 
    filter(resource %in% c(0.1, 0.5, 1)) %>% 
    ggplot(.,aes(x=temp, y=!!sym(var), color=as.factor(resource))) + 
    geom_line(size = 1) + 
    scale_color_manual(values = c("#CABD88", "#CA5216", "#65320D")) +
    labs(x = "Temperature (C)", y = "Per-Spore Susceptibility", color = "Resource (mgC/L)", title = "")
}

u_plot(u_seq, "m5_u")
```




```{r}
algae_plot <- function(seq_data, var){
seq_data %>% filter(temp %in% const_temp) %>% 
  ggplot(., aes(x=resource, y=!!sym(var), color=as.factor(temp), group = as.factor(temp))) + 
  geom_line() + 
  labs(x = "Resource (mgC/L)", 
       y = "Algae consumed (mgC)",
       color = "Temp") + 
  scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D"))
}

algae_plot_temp <- function(seq_data, var){
seq_data %>% filter(resource %in% c(0.1, 0.5, 1)) %>% 
  ggplot(., aes(x=temp, y=!!sym(var), color=as.factor(resource), group = as.factor(resource))) + 
  geom_line() + 
  labs(x = "Temperature (C)", 
       y = "Algae consumed (mgC)",
       color = "Temp") + 
  scale_color_manual(values = c("#CABD88", "#CA5216", "#65320D"))
}

algae_plot(f_seq, "m1_consumed")
```


Show temp only models

```{r}
p1 <- seq_plot(f_seq, "m2_rate") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
#algae_plot(f_seq, "m2_consumed")
p2 <- spores_plot(f_seq, "m2_Z_end") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
p3 <- u_plot(u_seq, "m2_u") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
p4 <- prev_plot(u_seq, "m2_I_end") + theme(plot.title = element_blank(), legend.position = "none")

temp_plots <- p1 / p2 / p3 / p4

ggsave(here("workshop", "figures","temp_plots.png"),
       temp_plots,
       width = 3,
       height = 8,
       units = "in")

```



Show resource only models

```{r}
p1 <- seq_plot_temp(f_seq, "m3_rate") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
#algae_plot_temp(f_seq, "m3_consumed")
p2 <- spores_plot_temp(f_seq, "m3_Z_end") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
p3 <- u_plot_temp(u_seq, "m3_u") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
p4 <- prev_plot_temp(u_seq, "m3_I_end") + theme(plot.title = element_blank(), legend.position = "none")

resource_plots <- p1 / p2 / p3 / p4

ggsave(here("workshop", "figures","resource_plots.png"),
       resource_plots,
       width = 3,
       height = 8,
       units = "in")
```


```{r}
p1 <- seq_plot(f_seq, "m4_rate") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
#algae_plot(f_seq, "m4_consumed")
p2 <- spores_plot(f_seq, "m4_Z_end") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
p3 <- u_plot(u_seq, "m4_u") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
p4 <- prev_plot(u_seq, "m4_I_end") + theme(plot.title = element_blank(), legend.position = "none")

additive_plots <- p1 / p2 / p3 / p4

ggsave(here("workshop", "figures","additive_plots.png"),
       additive_plots,
       width = 3,
       height = 8,
       units = "in")
```

```{r}
p1 <- seq_plot(f_seq, "m6c_rate") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
#algae_plot(f_seq, "m6c_consumed")
p2 <- spores_plot(f_seq, "m6c_Z_end") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
p3 <- u_plot(u_seq, "m5_u") + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank() ,axis.title.x = element_blank(), plot.title = element_blank(), legend.position = "none")
p4 <- prev_plot(u_seq, "m5_I_end") + theme(plot.title = element_blank(), legend.position = "none")

interactive_plots <- p1 / p2 / p3 / p4

ggsave(here("workshop", "figures","interactive_plots.png"),
       interactive_plots,
       width = 3,
       height = 8,
       units = "in")
```


```{r}
spores_plot(u_seq, "spores_consumed_m6c")
spores_plot(f_seq, "m6c_Z_end")
```







