---
title: "addl_fits"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = F}
library(here)
source(here("base","src.R"))

library(ggnewscale)
```

# Notes

```{r}
fitness <- read.csv(here("raw_data/main_fitness_edit.csv")) #must be read.csv
fitness %<>% dplyr::select(tube, temp_id, REMOVED, KBP, final_date) #remove unnecessary variables
mort <-  read_csv(here("raw_data/main_mort_edit.csv")) #mortality data
lengths <- read_csv(here("raw_data", "day5_length.csv")) #get average lengths
lengths %<>% filter(temp_id %in% const_temp)


dataset <- left_join(mort,fitness) #life table data
```


```{r}
data <- readRDS(here("processed_data","foraging_raw.rds")) #foraging rate data
data_summ <- readRDS(here("processed_data", "foraging.rds")) #foraging rate data summary

data %<>% mutate(treatment_ID = paste(temp, resource, sep = "_"))

data %<>% mutate(resource_tot = resource*vol) #resource_tot is the total amount of resources in our tube. resource concentration * total volume of tube
```


```{r}
treatment_IDs <- unique(data$treatment_ID)
resource_IDs <- unique(data$resource)
temp_IDs <- unique(data$temp)


fora_vol <- 15 #mL
life_vol <- 50 #mL
spore_conc <- 200 #spores/mL
gamma <- 2 
ref_t <- 15 #celsius

```

```{r}
dataset %<>% filter(species == "D") %>% #only daphnia for this analysis
  filter(temp %in% const_temp) #only constant temp for this analysis

dataset %<>% mutate(birthdate = ifelse(species == "daphnia", "4/5/22", "4/6/22"), 
                    lifespan = as.numeric(mdy(final_date) - mdy(birthdate)),
                    temp = as.numeric(temp),
                    treatment = paste(temp, resource, sep = "_")) %>% 
  filter(is.na(male)) %>% #remove males
  filter(is.na(missing)) %>% #remove missing
  filter(!is.na(inf)) #remove NAs for inf for estimating beta. sometimes they died too young to tell

dataset %<>% mutate(inf_status = inf, dead = ifelse(is.na(REMOVED) & is.na(KBP), 1, 0))


dataset %<>% mutate(spore_exposure = 200, #spores/mL
                    uninf = 1-inf_status,
                    time = 1, #duration of exposure in days
                    trt = paste(temp, resource, species, sep = "_"))
```

```{r}
lengths %<>% mutate(mm = raw_meas*17.86/1000)
#at default magnification (5.6x), 1 unit is equal to 17.86 micron

length_summ <- lengths %>% 
  group_by(temp_id, resource) %>% 
  summarize(life_mm = mean(mm),
            var = var(mm),
            sd = sd(mm),
            se = sd(mm)/sqrt(n())) %>%
  ungroup() %>%
  dplyr::select(temp_id, resource, life_mm)

length_summ %<>% add_row(temp_id=as.character(25), resource=as.numeric(0.5), life_mm=1.16) #midpoint between 1.0 and 0.1

dataset %<>% left_join(length_summ)

length_summ %<>% mutate(ID = paste(temp_id, resource, sep="_")) %>% dplyr::select(-c(temp_id, resource))

```

```{r}
mean_length_summ <- data_summ %>% dplyr::select(temp, resource, mm_mean)
data %<>% left_join(., mean_length_summ)
data %<>% mutate(mm = if_else(!is.na(mm), mm, mm_mean))

mean_length_summ %<>% rename(fora_mm = "mm_mean")
dataset %<>% left_join(., mean_length_summ)
```

```{r}
inf_out <- function(inf_status, I_end){
  dbinom(x = inf_status, size = 1, prob=I_end, log=T)
}
```



```{r}

m5_num_sol_add_f_add_u <- function(t, x, params){
  R <- x[1]
  S <- x[2]
  I <- x[3]
  Z <- x[4]
  
  with(as.list(params),{
    dR <- -R*(S+I)*(f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
              (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R)
    
    dS <- -Z*S*u*exp(arr_t_u*(1/ref_t - 1/temp))*exp(resource*rho)*
      (f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
                (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R)
    
    dI <- Z*S*u*exp(arr_t_u*(1/ref_t - 1/temp))*exp(resource*rho)*
      (f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
               (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R)
    
    dZ <- -Z*(S+I)*(f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
              (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R)
    
    res <- c(dR, dS, dI, dZ)
    list(res)}
  )
}


    # dS = -S*Z*u*exp(T_A_u*((1/15)-(1/T_trt)))*exp(R_trt*u2)*exp(R_trt*T_trt*u3)*
    #   f*(l^2)*exp(T_A_f*((1/15)-(1/T_trt))) / (1+(A*f*(l^2)*h*exp(h2*T_trt)))
    # dI = S*Z*u*exp(T_A_u*((1/15)-(1/T_trt)))*exp(R_trt*u2)*exp(R_trt*T_trt*u3)*
    #   f*(l^2)*exp(T_A_f*((1/15)-(1/T_trt))) / (1+(A*f*(l^2)*h*exp(h2*T_trt)))
    # dZ = -(S+I)*Z*f*(l^2)*exp(T_A_f*((1/15)-(1/T_trt))) / (1+(A*f*(l^2)*h*exp(h2*T_trt)))
    # dA = -(S+I)*A*f*(l^2)*exp(T_A_f*((1/15)-(1/T_trt))) / (1+(A*f*(l^2)*h*exp(h2*T_trt)))
```


```{r}
m5_sim_add_f_add_u <- function(R, time, f, u, length, gamma, Z, ref_t, arr_t_f, arr_t_u, h, temp, resource, rho){
  times <- seq(0, time, by=0.01)
  xstart <- c(R=R,
              S=1,
              I=0,
              Z=Z)
  params <- c(f=f,
              u=u,
              length = length,
              gamma = gamma,
              Z = Z,
              ref_t = ref_t,
              arr_t_f = arr_t_f,
              arr_t_u = arr_t_u,
              h = h,
              temp = temp,
              resource = resource,
              rho = rho)
  output <- as.data.frame(lsoda(y=xstart, times, m5_num_sol_add_f_add_u , params))
  
  if(Z == 0) {
  end_data <- slice_max(output, time)[,2]
  }
  else {
  end_data <- slice_max(output, time)[,4]  
  }

  return(end_data)
}
```


```{r}
m5_ll_add_f_add_u <- function(f, u, arr_t_f, arr_t_u, h, rho){
  
  if(f<0 | h<0 | u<0 | arr_t_f<0 | arr_t_u<0 |
      (u/100000*exp(arr_t_u*((1/15)-(1/15)))*exp(0.1/1000*rho)) <0 |
     (u/100000*exp(arr_t_u*((1/15)-(1/25)))*exp(1.0/1000*rho)) <0) {
  
      return(NA)
  
  } 
  
  else {  
  
  
  data <- tmp
  R_end <- as.data.frame(mapply(m5_sim_add_f_add_u, 
                                R=data$amt_init*fora_vol/1000, 
                                time=data$time/60/24, 
                                f=f/fora_vol,
                                u = 0, 
                                length=data$mm, 
                                gamma=gamma, 
                                Z=0,
                                ref_t=ref_t,
                                arr_t_f=arr_t_f,
                                arr_t_u=arr_t_u,
                                h=h,
                                temp = data$temp,
                                resource = data$resource,
                                rho = rho))
  colnames(R_end) <- "R_end"
  data$end <- R_end$R_end
  #data %<>% mutate(resid = log(end) - log(amt_rem*fora_vol/1000))
  data %<>% mutate(resid = sqrt(end) - sqrt(amt_rem*fora_vol/1000))
  
    nll <- dnorm(data$resid, 
                 mean = 0, 
                 sd = sd(data$resid), 
                 log = T)
    nll_sum <- -sum(nll)
  
  exp_data <- tmp_dataset %>% filter(exposed==TRUE)

  
  I_end <- as.data.frame(mapply(m5_sim_add_f_add_u, 
                                R=exp_data$resource*life_vol/1000, 
                                time=exp_data$time, 
                                f=f/life_vol, 
                                u=u/100000, 
                                length = exp_data$life_mm, 
                                gamma=gamma, 
                                Z=spore_conc*life_vol,
                                ref_t=ref_t,
                                arr_t_f=arr_t_f,
                                arr_t_u=arr_t_u,
                                h=h,
                                temp=exp_data$temp,
                                resource=exp_data$resource,
                                rho = rho))

  colnames(I_end) <- "I_end"
  
  exp_data %<>% cbind(I_end)
  
  exp_data %<>% 
    mutate(ll = mapply(inf_out, inf_status = inf_status, I_end=I_end))
  nll_sum <- nll_sum + -sum(exp_data$ll)
  return(nll_sum)
  
  }
}
```

```{r, eval=F}
start_time <- Sys.time()
tmp <- data
tmp_dataset <- dataset
m5_add_f_add_u <- mle2(m5_ll_add_f_add_u, start=list(u = 20,
                                      f=30, 
                                      arr_t_f=30, 
                                      arr_t_u=30,
                                      h=100,
                                      rho=0.1), 
                     control=list(parscale = c(u = 20,
                                      f=1, 
                                      arr_t_f=10, 
                                      arr_t_u=10,
                                      h=100,
                                      rho=0.1),
                                  maxit=5000),
                                  skip.hessian=F, 
                                  method="BFGS")

end_time <- Sys.time()
end_time - start_time


coef(m5_add_f_add_u)

saveRDS(m5_add_f_add_u, file = here("model_fitting","add_f_add_u_fit.rds"))
```





additive f interactive u

```{r}

m5_num_sol_add_f_int_u <- function(t, x, params){
  R <- x[1]
  S <- x[2]
  I <- x[3]
  Z <- x[4]
  
  with(as.list(params),{
    dR <- -R*(S+I)*(f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
              (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R)
    
    dS <- -Z*S*u*exp(arr_t_u*(1/ref_t - 1/temp))*exp(resource*rho)*exp(resource*temp*phi)*
      (f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
                (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R)
    
    dI <- Z*S*u*exp(arr_t_u*(1/ref_t - 1/temp))*exp(resource*rho)*exp(resource*temp*phi)*
      (f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
               (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R)
    
    dZ <- -Z*(S+I)*(f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
              (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R)
    
    res <- c(dR, dS, dI, dZ)
    list(res)}
  )
}


    # dS = -S*Z*u*exp(T_A_u*((1/15)-(1/T_trt)))*exp(R_trt*u2)*exp(R_trt*T_trt*u3)*
    #   f*(l^2)*exp(T_A_f*((1/15)-(1/T_trt))) / (1+(A*f*(l^2)*h*exp(h2*T_trt)))
    # dI = S*Z*u*exp(T_A_u*((1/15)-(1/T_trt)))*exp(R_trt*u2)*exp(R_trt*T_trt*u3)*
    #   f*(l^2)*exp(T_A_f*((1/15)-(1/T_trt))) / (1+(A*f*(l^2)*h*exp(h2*T_trt)))
    # dZ = -(S+I)*Z*f*(l^2)*exp(T_A_f*((1/15)-(1/T_trt))) / (1+(A*f*(l^2)*h*exp(h2*T_trt)))
    # dA = -(S+I)*A*f*(l^2)*exp(T_A_f*((1/15)-(1/T_trt))) / (1+(A*f*(l^2)*h*exp(h2*T_trt)))
```


```{r}
m5_sim_add_f_int_u <- function(R, time, f, u, length, gamma, Z, ref_t, arr_t_f, arr_t_u, h, temp, resource, rho, phi){
  times <- seq(0, time, by=0.01)
  xstart <- c(R=R,
              S=1,
              I=0,
              Z=Z)
  params <- c(f=f,
              u=u,
              length = length,
              gamma = gamma,
              Z = Z,
              ref_t = ref_t,
              arr_t_f = arr_t_f,
              arr_t_u = arr_t_u,
              h = h,
              temp = temp,
              resource = resource,
              rho = rho,
              phi = phi)
  output <- as.data.frame(lsoda(y=xstart, times, m5_num_sol_add_f_int_u, params))
  
  if(Z == 0) {
  end_data <- slice_max(output, time)[,2]
  }
  else {
  end_data <- slice_max(output, time)[,4]  
  }

  return(end_data)
}
```


```{r}
m5_ll_add_f_int_u <- function(f, u, arr_t_f, arr_t_u, h, rho, phi){
  
  if(f<0 | h<0 | u<0 | arr_t_f<0 | arr_t_u<0 |
      (u/100000*exp(arr_t_u*((1/15)-(1/15)))*exp(0.1/1000*rho)*exp(0.1/1000*15*phi)) <0 |
     (u/100000*exp(arr_t_u*((1/15)-(1/25)))*exp(1.0/1000*rho)*exp(1.0/1000*25*phi)) <0) {
  
      return(NA)
  
  } 
  
  else {  
  
  
  data <- tmp
  R_end <- as.data.frame(mapply(m5_sim_add_f_int_u, 
                                R=data$amt_init*fora_vol/1000, 
                                time=data$time/60/24, 
                                f=f/fora_vol,
                                u = 0, 
                                length=data$mm, 
                                gamma=gamma, 
                                Z=0,
                                ref_t=ref_t,
                                arr_t_f=arr_t_f,
                                arr_t_u=arr_t_u,
                                h=h,
                                temp = data$temp,
                                resource = data$resource,
                                rho = rho,
                                phi = phi))
  colnames(R_end) <- "R_end"
  data$end <- R_end$R_end
  #data %<>% mutate(resid = log(end) - log(amt_rem*fora_vol/1000))
  data %<>% mutate(resid = sqrt(end) - sqrt(amt_rem*fora_vol/1000))
  
    nll <- dnorm(data$resid, 
                 mean = 0, 
                 sd = sd(data$resid), 
                 log = T)
    nll_sum <- -sum(nll)
  
  exp_data <- tmp_dataset %>% filter(exposed==TRUE)

  
  I_end <- as.data.frame(mapply(m5_sim_add_f_int_u, 
                                R=exp_data$resource*life_vol/1000, 
                                time=exp_data$time, 
                                f=f/life_vol, 
                                u=u/100000, 
                                length = exp_data$life_mm, 
                                gamma=gamma, 
                                Z=spore_conc*life_vol,
                                ref_t=ref_t,
                                arr_t_f=arr_t_f,
                                arr_t_u=arr_t_u,
                                h=h,
                                temp=exp_data$temp,
                                resource=exp_data$resource,
                                rho = rho,
                                phi = phi))

  colnames(I_end) <- "I_end"
  
  exp_data %<>% cbind(I_end)
  
  exp_data %<>% 
    mutate(ll = mapply(inf_out, inf_status = inf_status, I_end=I_end))
  nll_sum <- nll_sum + -sum(exp_data$ll)
  return(nll_sum)
  
  }
}
```

```{r, eval=F}
start_time <- Sys.time()
tmp <- data
tmp_dataset <- dataset
m5_add_f_int_u <- mle2(m5_ll_add_f_int_u, start=list(u = 20,
                                      f=30, 
                                      arr_t_f=30, 
                                      arr_t_u=30,
                                      h=100,
                                      rho=0.1,
                                      phi=0.1), 
                     control=list(parscale = c(u = 20,
                                      f=1, 
                                      arr_t_f=10, 
                                      arr_t_u=10,
                                      h=100,
                                      rho=0.1,
                                      phi=0.1),
                                  maxit=5000),
                                  skip.hessian=F, 
                                  method="BFGS")

end_time <- Sys.time()
end_time - start_time


coef(m5_add_f_int_u)

saveRDS(m5_add_f_int_u, file = here("model_fitting","add_f_int_u_fit.rds"))
```


```{r}
getAIC <- function(model){
  return(2*length(coef(model))-(2*summary(model)@m2logL/-2))
}
```


```{r}
m4 <- readRDS(here("model_fitting","m4_coef_fit.rds"))
m5 <- readRDS(here("model_fitting","m5_phi_fit.rds"))
```



```{r}
getAIC(m4)
getAIC(m5)
getAIC(m5_add_f_add_u)
getAIC(m5_add_f_int_u)
```








