---
title: "u_f_fits"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = F}
library(here)
source(here("base","src.R"))

library(ggnewscale)
```

# Notes

```{r}
fitness <- read.csv(here("raw_data/main_fitness_edit.csv")) #must be read.csv
fitness %<>% dplyr::select(tube, temp_id, REMOVED, KBP, final_date) #remove unnecessary variables
mort <-  read_csv(here("raw_data/main_mort_edit.csv")) #mortality data
lengths <- read_csv(here("raw_data", "day5_length.csv")) #get average lengths
lengths %<>% filter(temp_id %in% const_temp)


dataset <- left_join(mort,fitness) #life table data
```


```{r}
data <- readRDS(here("processed_data","foraging_raw.rds")) #foraging rate data
data_summ <- readRDS(here("processed_data", "foraging.rds")) #foraging rate data summary

data %<>% mutate(treatment_ID = paste(temp, resource, sep = "_"))

data %<>% mutate(resource_tot = resource*vol) #resource_tot is the total amount of resources in our tube. resource concentration * total volume of tube
```


```{r}
treatment_IDs <- unique(data$treatment_ID)
resource_IDs <- unique(data$resource)
temp_IDs <- unique(data$temp)


fora_vol <- 15 #mL
life_vol <- 50 #mL
spore_conc <- 200 #spores/mL
gamma <- 2 
ref_t <- 15 #celsius

```

```{r}
dataset %<>% filter(species == "D") %>% #only daphnia for this analysis
  filter(temp %in% const_temp) #only constant temp for this analysis

dataset %<>% mutate(birthdate = ifelse(species == "daphnia", "4/5/22", "4/6/22"), 
                    lifespan = as.numeric(mdy(final_date) - mdy(birthdate)),
                    temp = as.numeric(temp),
                    treatment = paste(temp, resource, sep = "_")) %>% 
  filter(is.na(male)) %>% #remove males
  filter(is.na(missing)) %>% #remove missing
  filter(!is.na(inf)) #remove NAs for inf for estimating beta. sometimes they died too young to tell

dataset %<>% mutate(inf_status = inf, dead = ifelse(is.na(REMOVED) & is.na(KBP), 1, 0))


dataset %<>% mutate(spore_exposure = 200, #spores/mL
                    uninf = 1-inf_status,
                    time = 1, #duration of exposure in days
                    trt = paste(temp, resource, species, sep = "_"))
```

```{r}
lengths %<>% mutate(mm = raw_meas*17.86/1000)
#at default magnification (5.6x), 1 unit is equal to 17.86 micron

length_summ <- lengths %>% 
  group_by(temp_id, resource) %>% 
  summarize(life_mm = mean(mm),
            var = var(mm),
            sd = sd(mm),
            se = sd(mm)/sqrt(n())) %>%
  ungroup() %>%
  dplyr::select(temp_id, resource, life_mm)

length_summ %<>% add_row(temp_id=as.character(25), resource=as.numeric(0.5), life_mm=1.16) #midpoint between 1.0 and 0.1

dataset %<>% left_join(length_summ)

length_summ %<>% mutate(ID = paste(temp_id, resource, sep="_")) %>% dplyr::select(-c(temp_id, resource))

```

```{r}
mean_length_summ <- data_summ %>% dplyr::select(temp, resource, mm_mean)
data %<>% left_join(., mean_length_summ)
data %<>% mutate(mm = if_else(!is.na(mm), mm, mm_mean))

mean_length_summ %<>% rename(fora_mm = "mm_mean")
dataset %<>% left_join(., mean_length_summ)
```

```{r}
inf_out <- function(inf_status, I_end){
  dbinom(x = inf_status, size = 1, prob=I_end, log=T)
}
```


```{r}
getAIC <- function(model){
  return(2*length(coef(model))-(2*summary(model)@m2logL/-2))
}
```



$$
\frac{dR}{dt} = -\frac{fe^{T_{A}(1/T_{R}-1/T)} L^{\gamma}R}{1 + fe^{T_{A}(1/T_{R}-1/T)}hL^{\gamma}R} S \\
$$


# Independent Model

$$
\frac{dR}{dt} = -L^{\gamma} fRS\\
$$

```{r}
m1_num_sol <- function(t, x, params){
  R <- x[1]
  S <- x[2]
  I <- x[3]
  Z <- x[4]
  
  with(as.list(params),{
    dR <- -((f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
                (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R))*R*(S+I)
    dS <- -u*((f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
                (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R))*Z*S
    dI <- u*((f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
                (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R))*Z*S
    dZ <- -((f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
                (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R))*Z*(S+I)
    res <- c(dR, dS, dI, dZ)
    list(res)}
    )
}
```


```{r, m1_sim}
m1_sim <- function(R, time, f, u, length, gamma, Z, ref_t, arr_t_f, h, temp){
  times <- seq(0, time, by=0.01)
  xstart <- c(R=R,
              S=1,
              I=0,
              Z=Z)
  params <- c(f=f,
              u=u,
              length = length,
              gamma = gamma,
              Z = Z,
              ref_t = ref_t,
              arr_t_f = arr_t_f,
              h = h,
              temp = temp)
  output <- as.data.frame(lsoda(y=xstart, times, m1_num_sol, params))
  
  if(Z == 0) {
  end_data <- slice_max(output, time)[,2]
  }
  else {
  end_data <- slice_max(output, time)[,4]  
  }
  
  return(end_data)
}
```

```{r, m1_ll}
m1_ll <- function(u, f, arr_t_f, h, w, sd_est){
  data <- tmp
  R_end <- as.data.frame(mapply(m1_sim, 
                                R=data$amt_init*fora_vol/1000, 
                                time=data$time/60/24, 
                                f=f/fora_vol,
                                u = 0, 
                                length=data$mm, 
                                gamma=gamma, 
                                Z=0,
                                ref_t=ref_t,
                                arr_t_f=arr_t_f,
                                h=h*exp(w*data$temp),
                                temp=data$temp))
  
  colnames(R_end) <- "R_end"
  data$end <- R_end$R_end
  #data %<>% mutate(resid = log(end) - log(amt_rem*fora_vol/1000))
  data %<>% mutate(resid = sqrt(end) - sqrt(amt_rem*fora_vol/1000))
  data %<>% mutate(sqrt_model_end = sqrt(end),
                   sqrt_data_end = sqrt(amt_rem*vol/1000),
                   log_model_end = log(end),
                   log_data_end = log(amt_rem*vol/1000))
  
    nll_sum <- 0
    for(i in 1:length(treatment_IDs)){
      treatment_data <- data %>% filter(treatment_ID == treatment_IDs[i])
      nll <- dnorm(treatment_data$sqrt_data_end,
                 mean = mean(treatment_data$sqrt_model_end),
                 sd = sd_est,
                 log = T)
      nll_sum <- -sum(nll) + nll_sum
    }

  
  exp_data <- dataset %>% filter(exposed==TRUE)

  
  I_end <- as.data.frame(mapply(m1_sim, 
                                R=exp_data$resource*life_vol/1000, 
                                time=exp_data$time, 
                                f=f/life_vol, 
                                u=u, 
                                length = exp_data$life_mm, 
                                gamma=gamma, 
                                Z=spore_conc*life_vol,
                                ref_t=ref_t,
                                arr_t_f=arr_t_f,
                                h=h*exp(w*exp_data$temp),
                                temp=exp_data$temp))
  colnames(I_end) <- "I_end"
  
  exp_data %<>% cbind(I_end)
  
  exp_data %<>% 
    mutate(ll = mapply(inf_out, inf_status = inf_status, I_end=I_end))
  nll_sum <- nll_sum + -sum(exp_data$ll)
  return(nll_sum)
}
```





Now we use the optimizer

```{r, m1_mle, eval=F}
start_time <- Sys.time()
tmp <- data
m1_u_f_fit <- mle2(m1_ll, start=list(u = 0.0001, 
                                     f=18, 
                                     arr_t_f=30, 
                                     h=17000, 
                                     w=-0.2,
                                     sd_est = 0.01),
                     control=list(parscale = c(u = 0.0001, 
                                               f=1, 
                                               arr_t_f=10, 
                                               h=10000, 
                                               w=0.1,
                                               sd_est = 0.01)),
                     skip.hessian=F, method="Nelder-Mead")


end_time <- Sys.time()
m1_runtime <- end_time - start_time
m1_runtime

coef(m1_u_f_fit)

saveRDS(m1_u_f_fit, file = here("mle","m1_combined_fit.rds"))
```


# Temperature-Dependent Model

$$
\frac{dR}{dt} = -L^{\gamma}fe^{T_{A}(1/T_{R}-1/T)} RS\\  
$$

```{r, m2_sim}
m2_sim <-  function(R, time, f, u, length, gamma, Z, ref_t, arr_t_f, arr_t_u, h, temp){
  times <- seq(0, time, by=0.01)
  xstart <- c(R=R,
              S=1,
              I=0,
              Z=Z)
  params <- c(f=f,
              u=u*exp(arr_t_u*(1/ref_t - 1/temp)),
              length = length,
              gamma = gamma,
              Z = Z,
              ref_t = ref_t,
              arr_t_f = arr_t_f,
              h = h,
              temp = temp)
  output <- as.data.frame(lsoda(y=xstart, times, m1_num_sol, params))
  
  if(Z == 0) {
  end_data <- slice_max(output, time)[,2]
  }
  else {
  end_data <- slice_max(output, time)[,4]  
  }
  
  return(end_data)
}
```

```{r, m2_ll}
m2_ll <- function(f, u, arr_t_f, arr_t_u, h, w, sd_est){
  data <- tmp
  R_end <- as.data.frame(mapply(m2_sim, 
                                R=data$amt_init*fora_vol/1000, 
                                time=data$time/60/24, 
                                f=f/fora_vol,
                                u = 0, 
                                length=data$mm, 
                                gamma=gamma, 
                                Z=0,
                                arr_t_f=arr_t_f,
                                arr_t_u=arr_t_u,
                                ref_t=ref_t,
                                h=h*exp(w*data$temp),
                                temp=data$temp))
  colnames(R_end) <- "R_end"
  data$end <- R_end$R_end
  #data %<>% mutate(resid = log(end) - log(amt_rem*fora_vol/1000))
  data %<>% mutate(resid = sqrt(end) - sqrt(amt_rem*fora_vol/1000))
  data %<>% mutate(sqrt_model_end = sqrt(end),
                   sqrt_data_end = sqrt(amt_rem*vol/1000),
                   log_model_end = log(end),
                   log_data_end = log(amt_rem*vol/1000))
  
    nll_sum <- 0
    for(i in 1:length(treatment_IDs)){
      treatment_data <- data %>% filter(treatment_ID == treatment_IDs[i])
      nll <- dnorm(treatment_data$sqrt_data_end,
                 mean = mean(treatment_data$sqrt_model_end),
                 sd = sd_est,
                 log = T)
      nll_sum <- -sum(nll) + nll_sum
    }

  exp_data <- dataset %>% filter(exposed==TRUE)


  
  I_end <- as.data.frame(mapply(m2_sim, 
                                R=exp_data$resource*life_vol/1000, 
                                time=exp_data$time, 
                                f=f/life_vol, 
                                u=u, 
                                length = exp_data$life_mm, 
                                gamma=gamma, 
                                Z=spore_conc*life_vol,
                                arr_t_f=arr_t_f,
                                arr_t_u=arr_t_u,
                                ref_t=ref_t,
                                h=h*exp(w*exp_data$temp),
                                temp=exp_data$temp))

  colnames(I_end) <- "I_end"
  
  exp_data %<>% cbind(I_end)
  
  exp_data %<>% 
    mutate(ll = mapply(inf_out, inf_status = inf_status, I_end=I_end))
  nll_sum <- nll_sum + -sum(exp_data$ll)
  return(nll_sum)
}
```

Now we use the optimizer

```{r, m2_mle, eval=F}
start_time <- Sys.time()
tmp <- data
m2_u_f_fit <- mle2(m2_ll, start=list(u = 0.0001, 
                                     f=18,
                                     arr_t_f = 30,
                                     arr_t_u = 65,
                                     h=16000,
                                     w=-0.1,
                                     sd_est = 0.01), 
                     control=list(parscale = c(u = 0.0001, 
                                               f=1,
                                               arr_t_f = 10,
                                               arr_t_u = 10,
                                               h=10000,
                                               w=0.1,
                                     sd_est = 0.01)),
                     skip.hessian=F, method="BFGS")



end_time <- Sys.time()
m2_runtime <- end_time - start_time
m2_runtime

coef(m2_u_f_fit)

saveRDS(m2_u_f_fit, file = here("mle","m2_combined_fit.rds"))
```

# Resource-depdendent Model

$$
\frac{dR}{dt} = - \frac{fL^{\gamma}R}{1 + fL^{\gamma}hR}S \\
$$

```{r, m3_sim}
m3_sim <- function(R, time, f, u, length, gamma, Z, ref_t, arr_t_f, h, temp){
  times <- seq(0, time, by=0.01)
  xstart <- c(R=R,
              S=1,
              I=0,
              Z=Z)
  params <- c(f=f,
              u=u,
              length = length,
              gamma = gamma,
              Z = Z,
              ref_t = ref_t,
              arr_t_f = arr_t_f,
              h = h,
              temp = temp)
  output <- as.data.frame(lsoda(y=xstart, times, m1_num_sol, params))
  if(Z == 0) {
  end_data <- slice_max(output, time)[,2]
  }
  else {
  end_data <- slice_max(output, time)[,4]  
  }

  return(end_data)
}
```

```{r, m3_ll}
m3_ll <- function(f, u, arr_t_f, h, w, rho, sd_est){
  data <- tmp
  R_end <- as.data.frame(mapply(m3_sim, 
                                R=data$amt_init*fora_vol/1000, 
                                time=data$time/60/24, 
                                f=f/fora_vol,
                                u = 0, 
                                length=data$mm, 
                                gamma=gamma, 
                                Z=0,
                                arr_t_f=arr_t_f,
                                ref_t=ref_t,
                                h=h*exp(w*data$temp),
                                temp=data$temp))
  colnames(R_end) <- "R_end"
  data$end <- R_end$R_end
  #data %<>% mutate(resid = log(end) - log(amt_rem*fora_vol/1000))
  data %<>% mutate(resid = sqrt(end) - sqrt(amt_rem*fora_vol/1000))
  data %<>% mutate(sqrt_model_end = sqrt(end),
                   sqrt_data_end = sqrt(amt_rem*vol/1000),
                   log_model_end = log(end),
                   log_data_end = log(amt_rem*vol/1000))
  
    nll_sum <- 0
    for(i in 1:length(treatment_IDs)){
      treatment_data <- data %>% filter(treatment_ID == treatment_IDs[i])
      nll <- dnorm(treatment_data$sqrt_data_end,
                 mean = mean(treatment_data$sqrt_model_end),
                 sd = sd_est,
                 log = T)
      nll_sum <- -sum(nll) + nll_sum
    }
  

  exp_data <- dataset %>% filter(exposed==TRUE)


  
  I_end <- as.data.frame(mapply(m3_sim, 
                                R=exp_data$resource*life_vol/1000, 
                                time=exp_data$time, 
                                f=f/life_vol, 
                                u=u*exp(exp_data$resource*rho), 
                                length = exp_data$life_mm, 
                                gamma=gamma, 
                                Z=spore_conc*life_vol,
                                arr_t_f=arr_t_f,
                                ref_t=ref_t,
                                h=h*exp(w*exp_data$temp),
                                temp=exp_data$temp))

  colnames(I_end) <- "I_end"
  
  exp_data %<>% cbind(I_end)
  
  exp_data %<>% 
    mutate(ll = mapply(inf_out, inf_status = inf_status, I_end=I_end))
  nll_sum <- nll_sum + -sum(exp_data$ll)
  return(nll_sum)
}
```

Now we use the optimizer

```{r, m3_mle, eval=F}
start_time <- Sys.time()
tmp <- data
m3_u_f_fit <- mle2(m3_ll, start=list(u = 0.0001, 
                                     f=30, 
                                     arr_t_f = 30,
                                     h=16000,
                                     w=0.1,
                                     rho = 0.1,
                                     sd_est = 0.01), 
                     control=list(parscale = c(u = 0.0001, 
                                               f=1, 
                                               arr_t_f = 1,
                                               h=10000,
                                               w=0.1,
                                               rho = 0.1,
                                     sd_est = 0.01)),
                     skip.hessian=F, method="Nelder-Mead")


end_time <- Sys.time()
m3_runtime <- end_time - start_time
m3_runtime

coef(m3_u_f_fit)

saveRDS(m3_u_f_fit, file = here("mle","m3_combined_fit.rds"))
```


# Full Model


```{r}
m4_num_sol <- function(t, x, params){
  R <- x[1]
  S <- x[2]
  I <- x[3]
  Z <- x[4]
  
  with(as.list(params),{
    dR <- -R*(S+I)*(f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
              (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R*exp(w*temp))
    
    dS <- -Z*S*u*exp(arr_t_u*(1/ref_t - 1/temp))*exp(resource*rho)*(f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
                (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R*exp(w*temp))
    
    dI <- Z*S*u*exp(arr_t_u*(1/ref_t - 1/temp))*exp(resource*rho)*(f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
               (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R*exp(w*temp))
    
    dZ <- -Z*(S+I)*(f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
              (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R*exp(w*temp))
    res <- c(dR, dS, dI, dZ)
    list(res)}
  )
}


```






```{r, m4_sim}
m4_sim <- function(R, time, f, u, length, gamma, Z, ref_t, arr_t_f, arr_t_u, h, temp, resource, w, rho){
  times <- seq(0, time, by=0.01)
  xstart <- c(R=R,
              S=1,
              I=0,
              Z=Z)
  params <- c(f=f,
              u=u,
              length = length,
              gamma = gamma,
              Z = Z,
              ref_t = ref_t,
              arr_t_f = arr_t_f,
              arr_t_u = arr_t_u,
              h = h,
              temp = temp,
              resource = resource,
              w = w,
              rho = rho)
  output <- as.data.frame(lsoda(y=xstart, times, m4_num_sol, params))
  
  if(Z == 0) {
  end_data <- slice_max(output, time)[,2]
  }
  else {
  end_data <- slice_max(output, time)[,4]  
  }

  return(end_data)
}
```


# ```{r, eval=F}
# m4_sim <- function(R, time, f, u, length, gamma, Z, ref_t, arr_t_f, arr_t_u, h, temp){
#   times <- seq(0, time, by=0.01)
#   xstart <- c(R=R,
#               S=1,
#               I=0,
#               Z=Z)
#   params <- c(f=f,
#               u=u*exp(arr_t_u*(1/ref_t - 1/temp)),
#               length = length,
#               gamma = gamma,
#               Z = Z,
#               ref_t = ref_t,
#               arr_t_f = arr_t_f,
#               arr_t_u = arr_t_u,
#               h = h,
#               temp = temp)
#   output <- as.data.frame(lsoda(y=xstart, times, m1_num_sol, params))
#   
#   if(Z == 0) {
#   end_data <- slice_max(output, time)[,2]
#   }
#   else {
#   end_data <- slice_max(output, time)[,4]  
#   }
# 
#   return(end_data)
# }
# ```






```{r, m4_ll}
m4_ll <- function(f, u, arr_t_f, arr_t_u, h, w, rho, sd_est){
  
  #   if(f<0 | h<0 | u<0 | arr_t_f<0 | arr_t_u<0 |
  #     (u/10000*exp(arr_t_u*((1/15)-(1/15)))*exp(0.1/1000*rho)) <0 |
  #    (u/10000*exp(arr_t_u*((1/15)-(1/25)))*exp(1.0/1000*rho)) <0) {
  # 
  #     return(NA)
  # 
  # } 
  # 
  # else {  
  
  
  data <- tmp
  R_end <- as.data.frame(mapply(m4_sim, 
                                R=data$amt_init*fora_vol/1000, 
                                time=data$time/60/24, 
                                f=f/fora_vol,
                                u = 0, 
                                length=data$mm, 
                                gamma=gamma, 
                                Z=0,
                                ref_t=ref_t,
                                arr_t_f=arr_t_f,
                                arr_t_u=arr_t_u,
                                h=h,
                                temp = data$temp,
                                resource = data$resource,
                                w = w,
                                rho = rho))
  colnames(R_end) <- "R_end"
  data$end <- R_end$R_end
  #data %<>% mutate(resid = log(end) - log(amt_rem*fora_vol/1000))
  data %<>% mutate(resid = sqrt(end) - sqrt(amt_rem*fora_vol/1000))
  data %<>% mutate(sqrt_model_end = sqrt(end),
                   sqrt_data_end = sqrt(amt_rem*vol/1000),
                   log_model_end = log(end),
                   log_data_end = log(amt_rem*vol/1000))
  
    nll_sum <- 0
    for(i in 1:length(treatment_IDs)){
      treatment_data <- data %>% filter(treatment_ID == treatment_IDs[i])
      nll <- dnorm(treatment_data$sqrt_data_end,
                 mean = mean(treatment_data$sqrt_model_end),
                 sd = sd_est,
                 log = T)
      nll_sum <- -sum(nll) + nll_sum
    }

  
  exp_data <- dataset %>% filter(exposed==TRUE)
#  exp_data <- dataset_tmp %>% filter(exposed==TRUE)

  
  I_end <- as.data.frame(mapply(m4_sim, 
                                R=exp_data$resource*life_vol/1000, 
                                time=exp_data$time, 
                                f=f/life_vol, 
                                u=(u/10000), 
                                length = exp_data$life_mm, 
                                gamma=gamma, 
                                Z=spore_conc*life_vol,
                                ref_t=ref_t,
                                arr_t_f=arr_t_f,
                                arr_t_u=arr_t_u,
                                h=h,
                                temp=exp_data$temp,
                                resource=exp_data$resource,
                                w = w,
                                rho = rho))

  colnames(I_end) <- "I_end"
  
  exp_data %<>% cbind(I_end)
  
  exp_data %<>% 
    mutate(ll = mapply(inf_out, inf_status = inf_status, I_end=I_end))
  nll_sum <- nll_sum + -sum(exp_data$ll)
  return(nll_sum)
  
  }
#}
```

Now we use the optimizer

```{r, eval=F}
m4_fit <- readRDS(file = here("mle","m4_combined_fit.rds"))
m4_coef <- coef(m4_fit)

adjust_factor <- 1

m4_f <- m4_coef[1]*adjust_factor
m4_u <- m4_coef[2]*adjust_factor
m4_arr_t_f <- m4_coef[3]*adjust_factor
m4_arr_t_u <- m4_coef[4]*adjust_factor
m4_h <- m4_coef[5]*adjust_factor
m4_w <- m4_coef[6]*adjust_factor
m4_rho <- m4_coef[7]*adjust_factor


```

```{r, eval=F}


start_time <- Sys.time()
tmp <- data
m4_u_f_fit <- mle2(m4_ll, start=list(f = 10,
                                      u=10, 
                                      arr_t_f=30, 
                                      arr_t_u=30,
                                      h=1000,
                                      w=0.1,
                                      rho=0.1,
                                     sd_est = 0.01),
                     control=list(parscale = 
                                    c(f = 10,
                                      u=10, 
                                      arr_t_f=30, 
                                      arr_t_u=30,
                                      h=1000,
                                      w=0.1,
                                      rho=0.1,
                                     sd_est = 0.01), maxit = 10000),
                     skip.hessian=F, method="Nelder-Mead")


end_time <- Sys.time()
m4_runtime <- end_time - start_time
m4_runtime

coef(m4_u_f_fit)


saveRDS(m4_u_f_fit, file = here("mle","m4_combined_fit.rds"))

```


```{r}
start_time <- Sys.time()
tmp <- data
m4_u_f_fit <- mle2(m4_ll, start=list(f = 10,
                                      u=1, 
                                      arr_t_f=30, 
                                      arr_t_u=30,
                                      h=10000,
                                      w=0.1,
                                      rho=0.1,
                                     sd_est = 0.01),
                     control=list(parscale = 
                                    c(f = 10,
                                      u=1, 
                                      arr_t_f=30, 
                                      arr_t_u=30,
                                      h=10000,
                                      w=0.1,
                                      rho=0.1,
                                     sd_est = 0.01), maxit = 10000),
                     skip.hessian=F, method="Nelder-Mead")


end_time <- Sys.time()
m4_runtime <- end_time - start_time
m4_runtime

coef(m4_u_f_fit)


saveRDS(m4_u_f_fit, file = here("mle","m4_combined_fit_a.rds"))
```




```{r}
adjust_factor <- 1.1

start_time <- Sys.time()
tmp <- data
m4_u_f_fit <- mle2(m4_ll,  start=list(u = m4_u*adjust_factor*100000, 
                                     f=m4_f*adjust_factor,
                                     arr_t_f=m4_arr_t_f*adjust_factor,
                                     arr_t_u=m4_arr_t_u*adjust_factor,
                                     h=m4_h*adjust_factor,
                                     w=m4_w*adjust_factor,
                                     rho=m4_rho*adjust_factor,
                                     sd_est = 0.01),
                     control=list(parscale = c(u = m4_u*adjust_factor*100000, 
                                     f=m4_f*adjust_factor,
                                     arr_t_f=m4_arr_t_f*adjust_factor,
                                     arr_t_u=m4_arr_t_u*adjust_factor,
                                     h=m4_h*adjust_factor,
                                     w=m4_w*adjust_factor,
                                     rho=m4_rho*adjust_factor,
                                     sd_est = 0.01), maxit = 10000),
                     skip.hessian=F, method="Nelder-Mead")


end_time <- Sys.time()
m4_runtime <- end_time - start_time
m4_runtime

coef(m4_u_f_fit)


saveRDS(m4_u_f_fit, file = here("model_fitting","m4_1.1_coef_fit.rds"))
#saveRDS(m4_u_f_fit, file = here("model_fitting","m4_1.1_fit_log.rds"))

```




```{r}
adjust_factor <- 0.5

start_time <- Sys.time()
tmp <- data
m4_u_f_fit <- mle2(m4_ll, start=list(u = m4_u*adjust_factor*100000, 
                                     f=m4_f*adjust_factor,
                                     arr_t_f=m4_arr_t_f*adjust_factor,
                                     arr_t_u=m4_arr_t_u*adjust_factor,
                                     h=m4_h*adjust_factor,
                                     w=m4_w*adjust_factor,
                                     rho=m4_rho*adjust_factor,
                                     sd_est = 0.01),
                     control=list(parscale = c(u = m4_u*adjust_factor*100000, 
                                     f=m4_f*adjust_factor,
                                     arr_t_f=m4_arr_t_f*adjust_factor,
                                     arr_t_u=m4_arr_t_u*adjust_factor,
                                     h=m4_h*adjust_factor,
                                     w=m4_w*adjust_factor,
                                     rho=m4_rho*adjust_factor,
                                     sd_est = 0.01), maxit=10000),
                     skip.hessian=F, method="Nelder-Mead")


end_time <- Sys.time()
m4_runtime <- end_time - start_time
m4_runtime

coef(m4_u_f_fit)


saveRDS(m4_u_f_fit, file = here("model_fitting","m4_0.5_coef_fit.rds"))
#saveRDS(m4_u_f_fit, file = here("model_fitting","m4_0.5_fit_log.rds"))

```

# Interaction Model


```{r, eval=F}
m5_coef

f <- m5_coef[1]
u_15 <- m5_coef[2]
u_20 <- m5_coef[3]
u_25 <- m5_coef[4]
arr_t_f <- m5_coef[5]
h <- m5_coef[6]
w <- m5_coef[7]
rho_15 <- m5_coef[8]
rho_20 <- m5_coef[9]
rho_25 <- m5_coef[10]

```


```{r}

m5_num_sol <- function(t, x, params){
  R <- x[1]
  S <- x[2]
  I <- x[3]
  Z <- x[4]
  
  with(as.list(params),{
    dR <- -R*(S+I)*(f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
              (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R*exp(w*temp))
    
    dS <- -Z*S*u*exp(arr_t_u*(1/ref_t - 1/temp))*exp(resource*rho)*exp(resource*temp*phi)*
      (f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
                (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R*exp(w*temp))
    
    dI <- Z*S*u*exp(arr_t_u*(1/ref_t - 1/temp))*exp(resource*rho)*exp(resource*temp*phi)*
      (f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
               (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R*exp(w*temp))
    
    dZ <- -Z*(S+I)*(f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
              (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R*exp(w*temp))
    res <- c(dR, dS, dI, dZ)
    list(res)}
  )
}


```


```{r}
m5_sim <- function(R, time, f, u, length, gamma, Z, ref_t, arr_t_f, arr_t_u, h, temp, resource, w, rho, phi){
  times <- seq(0, time, by=0.01)
  xstart <- c(R=R,
              S=1,
              I=0,
              Z=Z)
  params <- c(f=f,
              u=u,
              length = length,
              gamma = gamma,
              Z = Z,
              ref_t = ref_t,
              arr_t_f = arr_t_f,
              arr_t_u = arr_t_u,
              h = h,
              temp = temp,
              resource = resource,
              w = w,
              rho = rho,
              phi = phi)
  output <- as.data.frame(lsoda(y=xstart, times, m5_num_sol, params))
  
  if(Z == 0) {
  end_data <- slice_max(output, time)[,2]
  }
  else {
  end_data <- slice_max(output, time)[,4]  
  }

  return(end_data)
}
```


```{r}
m5_ll <- function(f, u, arr_t_f, arr_t_u, h, w, rho, phi, sd_est){
  
  if(f<0 | h<0 | u<0 | arr_t_f<0 | arr_t_u<0 |
      (u/100000*exp(arr_t_u*((1/15)-(1/15)))*exp(0.1/1000*rho)*exp(0.1/1000*15*phi)) <0 |
     (u/100000*exp(arr_t_u*((1/15)-(1/25)))*exp(1.0/1000*rho)*exp(1.0/1000*25*phi)) <0) {
  
      return(NA)
  
  } 
  
  else {  
  
  
  data <- tmp
  R_end <- as.data.frame(mapply(m5_sim, 
                                R=data$amt_init*fora_vol/1000, 
                                time=data$time/60/24, 
                                f=f/fora_vol,
                                u = 0, 
                                length=data$mm, 
                                gamma=gamma, 
                                Z=0,
                                ref_t=ref_t,
                                arr_t_f=arr_t_f,
                                arr_t_u=arr_t_u,
                                h=h,
                                temp = data$temp,
                                resource = data$resource,
                                w = w,
                                rho = rho,
                                phi = phi))
  colnames(R_end) <- "R_end"
  data$end <- R_end$R_end
  #data %<>% mutate(resid = log(end) - log(amt_rem*fora_vol/1000))
  data %<>% mutate(resid = sqrt(end) - sqrt(amt_rem*fora_vol/1000))
  data %<>% mutate(sqrt_model_end = sqrt(end),
                   sqrt_data_end = sqrt(amt_rem*vol/1000),
                   log_model_end = log(end),
                   log_data_end = log(amt_rem*vol/1000))
  
    nll_sum <- 0
    for(i in 1:length(treatment_IDs)){
      treatment_data <- data %>% filter(treatment_ID == treatment_IDs[i])
      nll <- dnorm(treatment_data$sqrt_data_end,
                 mean = mean(treatment_data$sqrt_model_end),
                 sd = sd_est,
                 log = T)
      nll_sum <- -sum(nll) + nll_sum
    }
  

  exp_data <- tmp_dataset %>% filter(exposed==TRUE)

  
  I_end <- as.data.frame(mapply(m5_sim, 
                                R=exp_data$resource*life_vol/1000, 
                                time=exp_data$time, 
                                f=f/life_vol, 
                                u=u/100000, 
                                length = exp_data$life_mm, 
                                gamma=gamma, 
                                Z=spore_conc*life_vol,
                                ref_t=ref_t,
                                arr_t_f=arr_t_f,
                                arr_t_u=arr_t_u,
                                h=h,
                                temp=exp_data$temp,
                                resource=exp_data$resource,
                                w = w,
                                rho = rho,
                                phi = phi))

  colnames(I_end) <- "I_end"
  
  exp_data %<>% cbind(I_end)
  
  exp_data %<>% 
    mutate(ll = mapply(inf_out, inf_status = inf_status, I_end=I_end))
  nll_sum <- nll_sum + -sum(exp_data$ll)
  return(nll_sum)
  
  }
}
```

```{r, eval=F}
start_time <- Sys.time()
tmp <- data
tmp_dataset <- dataset
m5_u_f_fit <- mle2(m5_ll, start=list(f = 10,
                                      u=10, 
                                      arr_t_f=30, 
                                      arr_t_u=30,
                                      h=100,
                                      w=0.1,
                                      rho=0.1,
                                      phi=0.1,
                                     sd_est = 0.01), 
                     control=list(parscale = c(f = 10,
                                      u=10, 
                                      arr_t_f=10, 
                                      arr_t_u=10,
                                      h=100,
                                      w=0.1,
                                      rho=0.1,
                                      phi=0.1,
                                     sd_est = 0.01),
                                  maxit=5000),
                                  skip.hessian=F, 
                                  method="BFGS")

end_time <- Sys.time()
end_time - start_time


coef(m5_u_f_fit)

saveRDS(m5_u_f_fit, file = here("mle","m5_combined_fit.rds"))
```

```{r, eval=F}
adjust_factor <- 1.1

start_time <- Sys.time()
tmp <- data
tmp_dataset <- dataset
m5_u_f_fit <- mle2(m5_ll, start=list(u = 20*adjust_factor,
                                      f=30*adjust_factor, 
                                      arr_t_f=30*adjust_factor, 
                                      arr_t_u=30*adjust_factor,
                                      h=100*adjust_factor,
                                      w=0.1*adjust_factor,
                                      rho=0.1*adjust_factor,
                                      phi=0.1*adjust_factor), 
                     control=list(parscale = c(u = 20*adjust_factor,
                                      f=30*adjust_factor, 
                                      arr_t_f=30*adjust_factor, 
                                      arr_t_u=30*adjust_factor,
                                      h=100*adjust_factor,
                                      w=0.1*adjust_factor,
                                      rho=0.1*adjust_factor,
                                      phi=0.1*adjust_factor),
                                  maxit=5000),
                                  skip.hessian=F, 
                                  method="BFGS")

end_time <- Sys.time()
end_time - start_time


coef(m5_u_f_fit)

saveRDS(m5_u_f_fit, file = here("model_fitting","m5_phi_fit_1.1.rds"))
```

```{r}
adjust_factor <- 0.5

start_time <- Sys.time()
tmp <- data
tmp_dataset <- dataset
m5_u_f_fit <- mle2(m5_ll, start=list(u = 20*adjust_factor,
                                      f=30*adjust_factor, 
                                      arr_t_f=30*adjust_factor, 
                                      arr_t_u=30*adjust_factor,
                                      h=100*adjust_factor,
                                      w=0.1*adjust_factor,
                                      rho=0.1*adjust_factor,
                                      phi=0.1*adjust_factor), 
                     control=list(parscale = c(u = 20*adjust_factor,
                                      f=30*adjust_factor, 
                                      arr_t_f=30*adjust_factor, 
                                      arr_t_u=30*adjust_factor,
                                      h=100*adjust_factor,
                                      w=0.1*adjust_factor,
                                      rho=0.1*adjust_factor,
                                      phi=0.1*adjust_factor),
                                  maxit=5000),
                                  skip.hessian=F, 
                                  method="BFGS")

end_time <- Sys.time()
end_time - start_time


coef(m5_u_f_fit)

saveRDS(m5_u_f_fit, file = here("model_fitting","m5_phi_fit_0.5.rds"))
```









