---
title: "final_fits_viz"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(here)
source(here("base","src.R")) #packages
source(here("model_fitting", "combined", "final_prep.R")) #data, global variables and fu
```




```{r}
m1_u_f_fit <- readRDS(file = here("mle", "final", "m1_fit.rds"))
m2_u_f_fit <- readRDS(file = here("mle", "final", "m2_fit.rds"))
m3_u_f_fit <- readRDS(file = here("mle", "final", "m3_fit.rds"))
m4_u_f_fit <- readRDS(file = here("mle", "final", "m4_fit.rds"))
m5_u_f_fit <- readRDS(file = here("mle", "final", "m5_fit.rds"))
```



```{r}
getAIC(m1_u_f_fit) #constant u
getAIC(m2_u_f_fit) #temperature-dependent u 
getAIC(m3_u_f_fit) #rho
getAIC(m4_u_f_fit) #temperature-dependent u and rho
getAIC(m5_u_f_fit) #per-temperature u and rho
```





```{r}
fora_summ <- data %>% 
  mutate(ID = treatment_ID) %>%
  group_by(ID) %>% 
  summarize(end_r_mean = mean(amt_rem)*fora_vol/1000,
            end_r_se = (sd(amt_rem)/sqrt(n()))*fora_vol/1000)

prevalence <- readRDS(here("processed_data", "prevalence.rds"))
prevalence %<>% filter(temp %in% c(15, 20, 25)) %>% filter(species=="D") %>% mutate(ID = paste(temp, resource, sep="_")) %>% dplyr::select(-c(temp, resource, species))


viz_summ <- left_join(fora_summ, prevalence)
viz_summ %<>% left_join(., data_summ)
viz_summ %<>% left_join(., length_summ)
```

```{r}
temp_range <- seq(15,25,by=0.1)
resource_range <- seq(0.1,1,by=0.01)

seq_data <- tibble(temp=c(),
                   resourece=c())

for (i in 1:length(temp_range)){
  tmp <- tibble(temp = temp_range[i],
                resource = seq(0.1,1,by=0.01))
  seq_data %<>% bind_rows(., tmp)
}


```

```{r}
lm(life_mm ~ resource + as.numeric(temp_id), data = length_summ)
summary(lm(life_mm ~ resource + as.numeric(temp_id), data = length_summ))
length_coef <- coef(lm(life_mm ~ resource + as.numeric(temp_id), data = length_summ))


interpolate_length <- function(resource, temp){
  length <- length_coef[1] + resource*length_coef[2] + temp*length_coef[3]
}

seq_data %<>% mutate(length = mapply(interpolate_length, 
                                     resource = resource,
                                     temp = temp))

seq_data %<>% left_join(., viz_summ, by=c("temp", "resource"))
```



```{r}
m1_coef <- coef(m1_u_f_fit)
m1_u <- as.numeric(m1_coef[1])
m1_f <- as.numeric(m1_coef[2])
m1_arr <- as.numeric(m1_coef[3])
m1_h <- as.numeric(m1_coef[4])
m1_w <- as.numeric(m1_coef[5])


viz_summ %<>% mutate(m1_I_end = mapply(m1_sim, 
                                       R=resource*life_vol/1000, 
                                       time=1, 
                                       f=m1_f/life_vol, 
                                       u = m1_u, 
                                       length=life_mm, 
                                       gamma=gamma, 
                                       Z=200*life_vol,
                                       ref_t = ref_t,
                                       arr_t_f = m1_arr,
                                       h = m1_h*exp(m1_w*temp),
                                       temp = temp))



data_summ %<>% mutate(m1_rate = (m1_f*exp(m1_arr*(1/ref_t - 1/temp))*(mm_mean^gamma))/
                        (1+m1_f*exp(m1_arr*(1/ref_t - 1/temp))*(mm_mean^gamma)*m1_h*exp(m1_w*temp)*resource/1000),
                      m1_u = m1_u)
```


```{r, eval=F}
seq_data %<>% mutate(m1_I_end = mapply(m1_sim, 
                                       R=resource*life_vol/1000, 
                                       time=1, 
                                       f=m1_f/life_vol, 
                                       u = m1_u, 
                                       length=length, 
                                       gamma=gamma, 
                                       Z=200*life_vol,
                                       ref_t = ref_t,
                                       arr_t_f = m1_arr,
                                       h = m1_h*exp(m1_w*temp),
                                       temp = temp))

seq_data %<>% mutate(m1_rate = (m1_f*exp(m1_arr*(1/ref_t - 1/temp))*(length^gamma))/
                        (1+m1_f*exp(m1_arr*(1/ref_t - 1/temp))*(length^gamma)*m1_h*exp(m1_w*temp)*resource/1000),
                      m1_u = m1_u)
```

```{r}
m2_coef <- coef(m2_u_f_fit)
m2_f <- as.numeric(m2_coef[1])
m2_u <- as.numeric(m2_coef[2])
m2_arr <- as.numeric(m2_coef[3])
m2_arr_u <- as.numeric(m2_coef[4])
m2_h <- as.numeric(m2_coef[5])
m2_w <- as.numeric(m2_coef[6])


viz_summ %<>% mutate(m2_I_end = mapply(m2_sim, 
                                       R=resource*life_vol/1000,
                                       time=1,
                                       f=m2_f/life_vol,
                                       u = m2_u,
                                       length=life_mm,
                                       gamma=gamma,
                                       Z=200*life_vol,
                                       ref_t = ref_t,
                                       arr_t_f = m2_arr,
                                       arr_t_u = m2_arr_u,
                                       h = m2_h*exp(m2_w*temp),
                                       temp = temp))




data_summ %<>% mutate(m2_rate = (m2_f*exp(m2_arr*(1/ref_t - 1/temp))*(mm_mean^gamma))/
                        (1+m2_f*exp(m2_arr*(1/ref_t - 1/temp))*(mm_mean^gamma)*m2_h*exp(m2_w*temp)*resource/1000),
                      m2_u = m2_u*exp(m2_arr_u*(1/ref_t - 1/temp)))
```


```{r, eval=F}
seq_data %<>% mutate(m2_I_end = mapply(m2_sim, 
                                       R=resource*life_vol/1000,
                                       time=1,
                                       f=m2_f/life_vol,
                                       u = m2_u,
                                       length=length,
                                       gamma=gamma,
                                       Z=200*life_vol,
                                       ref_t = ref_t,
                                       arr_t_f = m2_arr,
                                       arr_t_u = m2_arr_u,
                                       h = m2_h*exp(m2_w*temp),
                                       temp = temp))


seq_data %<>% mutate(m2_rate = (m2_f*exp(m2_arr*(1/ref_t - 1/temp))*(length^gamma))/
                        (1+m2_f*exp(m2_arr*(1/ref_t - 1/temp))*(length^gamma)*m2_h*exp(m2_w*temp)*resource/1000),
                      m2_u = m2_u*exp(m2_arr_u*(1/ref_t - 1/temp)))
```

```{r}
m3_coef <- coef(m3_u_f_fit)
m3_f <- as.numeric(m3_coef[1])
m3_u <- as.numeric(m3_coef[2])
m3_arr <- as.numeric(m3_coef[3])
m3_h <- as.numeric(m3_coef[4])
m3_w <- as.numeric(m3_coef[5])
m3_rho <- as.numeric(m3_coef[6])


viz_summ %<>% mutate(m3_I_end = mapply(m3_sim, 
                                       R=resource*life_vol/1000,
                                       time=1,
                                       f=m3_f/life_vol,
                                       u = m3_u*exp(m3_rho*resource),
                                       length=life_mm,
                                       gamma=gamma,
                                       Z=200*life_vol,
                                       ref_t = ref_t,
                                       arr_t_f = m3_arr,
                                       h = m3_h*exp(m3_w*temp),
                                       temp = temp))





data_summ %<>% mutate(m3_rate = (m3_f*exp(m3_arr*(1/ref_t - 1/temp))*(mm_mean^gamma))/
                        (1+m3_f*exp(m2_arr*(1/ref_t - 1/temp))*(mm_mean^gamma)*m3_h*exp(m3_w*temp)*resource/1000),
                      m3_u = m3_u*exp(m3_rho*temp))
```


```{r, eval=F}
seq_data %<>% mutate(m3_I_end = mapply(m3_sim, 
                                       R=resource*life_vol/1000,
                                       time=1,
                                       f=m3_f/life_vol,
                                       u = m3_u*exp(m3_rho*resource),
                                       length=length,
                                       gamma=gamma,
                                       Z=200*life_vol,
                                       ref_t = ref_t,
                                       arr_t_f = m3_arr,
                                       h = m3_h*exp(m3_w*temp),
                                       temp = temp))

seq_data %<>% mutate(m3_rate = (m3_f*exp(m3_arr*(1/ref_t - 1/temp))*(length^gamma))/
                        (1+m3_f*exp(m2_arr*(1/ref_t - 1/temp))*(length^gamma)*m3_h*exp(m3_w*temp)*resource/1000),
                      m3_u = m3_u*exp(m3_rho*temp))
```


```{r}
m4_coef <- coef(m4_u_f_fit)
m4_f <- as.numeric(m4_coef[1])
m4_u <- as.numeric(m4_coef[2])
m4_arr <- as.numeric(m4_coef[3])
m4_arr_u <- as.numeric(m4_coef[4])
m4_h <- as.numeric(m4_coef[5])
m4_w <- as.numeric(m4_coef[6])
m4_rho <- as.numeric(m4_coef[7])


viz_summ %<>% mutate(m4_I_end = mapply(m4_sim, 
                                       R=resource*life_vol/1000, 
                                       time=1, 
                                       f=m4_f/life_vol, 
                                       u = m4_u*exp(m4_rho*resource), 
                                       length=life_mm, 
                                       gamma=gamma, 
                                       Z=200*life_vol,
                                       ref_t = ref_t,
                                       arr_t_f = m4_arr,
                                       arr_t_u = m4_arr_u,
                                       h = m4_h*exp(m4_w*temp),
                                       temp = temp))




data_summ %<>% mutate(m4_rate = (m4_f*exp(m4_arr*(1/ref_t - 1/temp))*(mm_mean^gamma))/
                        (1+m4_f*exp(m4_arr*(1/ref_t - 1/temp))*(mm_mean^gamma)*m4_h*exp(m4_w*temp)*resource/1000),
                      m4_u = m4_u*exp(m4_arr_u*(1/ref_t - 1/temp))*exp(m4_rho*temp))
```


```{r, eval=F}
seq_data %<>% mutate(m4_I_end = mapply(m4_sim, 
                                       R=resource*life_vol/1000, 
                                       time=1, 
                                       f=m4_f/life_vol, 
                                       u = m4_u*exp(m4_rho*resource), 
                                       length=length, 
                                       gamma=gamma, 
                                       Z=200*life_vol,
                                       ref_t = ref_t,
                                       arr_t_f = m4_arr,
                                       arr_t_u = m4_arr_u,
                                       h = m4_h*exp(m4_w*temp),
                                       temp = temp))

seq_data %<>% mutate(m4_rate = (m4_f*exp(m4_arr*(1/ref_t - 1/temp))*(length^gamma))/
                        (1+m4_f*exp(m4_arr*(1/ref_t - 1/temp))*(length^gamma)*m4_h*exp(m4_w*temp)*resource/1000),
                      m4_u = m4_u*exp(m4_arr_u*(1/ref_t - 1/temp))*exp(m4_rho*temp))
```


```{r}
m5_coef <- coef(m5_u_f_fit)
m5_f <- as.numeric(m5_coef[1])
m5_u_15 <- as.numeric(m5_coef[2])
m5_u_20 <- as.numeric(m5_coef[3])
m5_u_25 <- as.numeric(m5_coef[4])
m5_arr <- as.numeric(m5_coef[5])
m5_h <- as.numeric(m5_coef[6])
m5_w <- as.numeric(m5_coef[7])
m5_rho_15 <- as.numeric(m5_coef[8])
m5_rho_20 <- as.numeric(m5_coef[9])
m5_rho_25 <- as.numeric(m5_coef[10])


viz_summ %<>% mutate(m5_I_end = mapply(m3_sim, 
                                       R=resource*life_vol/1000, 
                                       time=1, 
                                       f=m5_f/life_vol, 
                                       u = case_when(temp == 15 ~ m5_u_15*exp(m5_rho_15*resource),
                                                     temp == 20 ~ m5_u_20*exp(m5_rho_20*resource),
                                                     temp == 25 ~ m5_u_25*exp(m5_rho_25*resource)), 
                                       length=life_mm, 
                                       gamma=gamma, 
                                       Z=200*life_vol,
                                       ref_t = ref_t,
                                       arr_t_f = m5_arr,
                                       h = m5_h*exp(m5_w*temp),
                                       temp = temp))


data_summ %<>% mutate(m5_rate = (m5_f*exp(m5_arr*(1/ref_t - 1/temp))*(mm_mean^gamma))/
                        (1+m5_f*exp(m5_arr*(1/ref_t - 1/temp))*(mm_mean^gamma)*m5_h*exp(m5_w*temp)*resource/1000),
                      m5_u = case_when(temp == 15 ~ m5_u_15*exp(m5_rho_15*resource),
                                       temp == 20 ~ m5_u_20*exp(m5_rho_20*resource),
                                       temp == 25 ~ m5_u_25*exp(m5_rho_25*resource)))
```


```{r, eval=F}
seq_data %<>% mutate(m5_I_end = mapply(m3_sim, 
                                       R=resource*life_vol/1000, 
                                       time=1, 
                                       f=m5_f/life_vol, 
                                       u = case_when(temp == 15 ~ m5_u_15*exp(m5_rho_15*resource),
                                                     temp == 20 ~ m5_u_20*exp(m5_rho_20*resource),
                                                     temp == 25 ~ m5_u_25*exp(m5_rho_25*resource)), 
                                       length=life_mm, 
                                       gamma=gamma, 
                                       Z=200*life_vol,
                                       ref_t = ref_t,
                                       arr_t_f = m5_arr,
                                       h = m5_h*exp(m5_w*temp),
                                       temp = temp))

seq_data %<>% mutate(m5_rate = (m5_f*exp(m5_arr*(1/ref_t - 1/temp))*(length^gamma))/
                        (1+m5_f*exp(m5_arr*(1/ref_t - 1/temp))*(length^gamma)*m5_h*exp(m5_w*temp)*resource/1000),
                      m5_u = case_when(temp == 15 ~ m5_u_15*exp(m5_rho_15*resource),
                                       temp == 20 ~ m5_u_20*exp(m5_rho_20*resource),
                                       temp == 25 ~ m5_u_25*exp(m5_rho_25*resource)))
```



```{r}
data_summ %<>% mutate(rate_mean_ml_day=rate_len_mean*60*24,
                      rate_se_ml_day=rate_len_mean_se*60*24)
```


```{r, eval=F}
seq_data %<>% mutate(rate_mean_ml_day=rate_len_mean*60*24,
                     rate_se_ml_day=rate_len_mean_se*60*24)

```


```{r}
#saveRDS(seq_data, file = here("model_fitting", "combined", "seq_data.rds"))
seq_data <- readRDS(file = here("model_fitting", "combined", "seq_data.rds"))
```


```{r}
prev_plot <- function(var){
  seq_data %>% filter(temp %in% const_temp) %>% 
    ggplot(.,aes(x=resource, 
                 y=!!sym(var), 
                 color=as.factor(temp))) + 
    geom_line() +
    new_scale_color() + 
    geom_point(aes(x=resource, y=prev, color=as.factor(temp)), size=4) + 
    geom_linerange(aes(ymin = conf$lower, ymax=conf$upper, color=as.factor(temp))) +
    labs(x="Resource", y="Prevalence", color="Temperature", title = "")
}
```


```{r}
viz_summ %>% ggplot(.,aes(x=resource, y=prev, color=as.factor(temp)))  +
  geom_point(size=4) + 
  geom_linerange(aes(ymin = conf$lower, ymax=conf$upper)) +
  labs(title="experimental data")

prev_plot("m1_I_end") + labs(title = "size-dependent model")
prev_plot("m2_I_end") + labs(title = "temp-dependent model")
prev_plot("m3_I_end") + labs(title = "resource-dependent model")
prev_plot("m4_I_end") + labs(title = "full model")

viz_summ %>% ggplot(.,aes(x=resource, y=m5_I_end, color=as.factor(temp), group=as.factor(temp))) + 
  geom_point(size = 5, shape=2) +
  geom_line() +
  new_scale_color() + 
  geom_point(aes(x=resource, y=prev, color=as.factor(temp)), size=4) + 
  geom_linerange(aes(ymin = conf$lower, ymax=conf$upper, color=as.factor(temp))) +
  labs(title="interaction model")
```

```{r}
all_fits <- seq_data %>% mutate(upper = conf$upper, lower = conf$lower) %>% 
  dplyr::select(resource, temp, prev, upper, lower, m2_I_end, m3_I_end, m4_I_end, m5_I_end) %>%
  filter(temp %in% c(15, 20, 25)) %>%
  mutate("temp-only" = m2_I_end, "resource-only" = m3_I_end, "additive" = m4_I_end) %>%
  dplyr::select(-c(m2_I_end, m3_I_end, m4_I_end)) %>%
  pivot_longer(cols=c('temp-only', 'resource-only', 'additive')) %>%
  ggplot(.,aes(x=resource, y=value, group = interaction(name, as.factor(temp)), color=as.factor(temp))) +
  geom_line(aes(linetype=name)) +
  scale_linetype_manual(values = c(5, 1, 3)) +
  geom_point(aes(x=resource, y=m5_I_end, color = as.factor(temp), shape="Interactive Model Estimate"), size=4) + 
  geom_point(aes(x=resource, y=prev, color=as.factor(temp), shape="Experimental Data"), size=4) + 
  scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D")) +
  geom_linerange(aes(ymin = lower, ymax=upper, color=as.factor(temp))) +
  labs(x="Resource Conc. (mgC/L)", y="Probability of Infection", color="Temp", shape="Data", title = "", linetype="Model") 

all_fits

ggsave("prev_fits_final.png", all_fits, path=here("mle/fit_plots"), width = outwidth[1], height = outwidth[1]/golden)
```





```{r, eval=F}
viz_summ %>% ggplot(.,aes(x=resource, y=prev, color=as.factor(temp)))  +
  geom_point(size=4) + 
  geom_linerange(aes(ymin = conf$lower, ymax=conf$upper)) +
  labs(title="experimental data")

viz_summ %>% ggplot(.,aes(x=resource, y=m1_I_end, color=as.factor(temp))) + 
  geom_point(size = 4, shape=2) +
  new_scale_color() + 
  geom_point(aes(x=resource, y=prev, color=as.factor(temp)), size=4) + 
  geom_linerange(aes(ymin = conf$lower, ymax=conf$upper, color=as.factor(temp))) +
  labs(title="independent model")

viz_summ %>% ggplot(.,aes(x=resource, y=m2_I_end, color=as.factor(temp))) + 
  geom_point(size = 4, shape=2) +
  new_scale_color() +
  geom_point(aes(x=resource, y=prev, color=as.factor(temp)), size=4) + 
  labs(title="temperature-dependent model")

viz_summ %>% ggplot(.,aes(x=resource, y=m3_I_end, color=as.factor(temp))) + 
  geom_point(size = 4, shape=2) +
  new_scale_color() + 
  geom_point(aes(x=resource, y=prev, color=as.factor(temp)), size=4) + 
  labs(title="resource-dependent model")

viz_summ %>% ggplot(.,aes(x=resource, y=m4_I_end, color=as.factor(temp))) + 
  geom_point(size = 4, shape=2) +
  new_scale_color() + 
  geom_point(aes(x=resource, y=prev, color=as.factor(temp)), size=4) + 
  labs(title="full model")

viz_summ %>% ggplot(.,aes(x=resource, y=m5_I_end, color=as.factor(temp))) + 
  geom_point(size = 4, shape=2) +
  new_scale_color() + 
  geom_point(aes(x=resource, y=prev, color=as.factor(temp)), size=4) + 
  labs(title="interaction model")

```

```{r}
rate_plot <- function(var){
  seq_data %>% filter(temp %in% const_temp) %>% 
    ggplot(.,aes(x=resource, y=!!sym(var), color=as.factor(temp))) + 
      geom_line() +
      new_scale_color() + 
      geom_point(aes(x=resource, y=rate_mean_ml_day, color=as.factor(temp)), size=3, shape = 1) + 
      labs(x = "resource", y = "Foraging rate (mL/day)", title="")
}
```

```{r}
  seq_data %>% filter(temp %in% const_temp) %>% 
    ggplot(.,aes(x=resource, y=m1_rate, color=as.factor(temp), group=as.factor(temp))) + 
      geom_line(size = 1, shape=2) +
      new_scale_color() + 
      geom_point(aes(x=resource, y=rate_mean_ml_day, color=as.factor(temp)), size=2, shape = 1) + 
      labs(x = "resource", y = "Foraging rate (mL/day)", title="")
```


```{r}
rate_plot("m1_rate") + labs(title = "Size-dependent model")
rate_plot("m2_rate") + labs(title = "Temperature-dependent model")
rate_plot("m3_rate") + labs(title = "Resource-dependent model")
rate_plot("m4_rate") + labs(title = "Temp. + Res. dependent model")
rate_plot("m5_rate") + labs(title = "Interaction model")

```



```{r}
data_summ %>% ggplot(.,aes(x=resource, y=m1_rate, color=as.factor(temp))) + geom_point(size = 3, shape=2) +
  new_scale_color() + geom_point(aes(x=resource, y=rate_mean_ml_day, color=as.factor(temp)), size=4) + labs(title="independent model")

seq_data %>% filter(temp %in% const_temp) %>% ggplot(.,aes(x=resource, y=m1_rate, color=as.factor(temp))) + 
  geom_point(size = 3, shape=2) +
  new_scale_color() + 
  geom_point(aes(x=resource, y=rate_mean_ml_day, color=as.factor(temp)), size=4) + 
  labs(title="independent model")



data_summ %>% ggplot(.,aes(x=resource, y=m2_rate, color=as.factor(temp))) + geom_point(size = 3, shape=2) +
  new_scale_color() + geom_point(aes(x=resource, y=rate_mean_ml_day, color=as.factor(temp)), size=4) + labs(title="temperature-dependent model")

data_summ %>% ggplot(.,aes(x=resource, y=m3_rate, color=as.factor(temp))) + geom_point(size = 3, shape=2) +
  new_scale_color() + geom_point(aes(x=resource, y=rate_mean_ml_day, color=as.factor(temp)), size=4) + labs(title="resource_dependent model")

data_summ %>% ggplot(.,aes(x=resource, y=m4_rate, color=as.factor(temp))) + geom_point(size = 3, shape=2) +
  new_scale_color() + geom_point(aes(x=resource, y=rate_mean_ml_day, color=as.factor(temp)), size=4) + labs(title="full model")

data_summ %>% ggplot(.,aes(x=resource, y=m5_rate, color=as.factor(temp))) + geom_point(size = 3, shape=2) +
  new_scale_color() + geom_point(aes(x=resource, y=rate_mean_ml_day, color=as.factor(temp)), size=4) + labs(title="interaction model")
```

```{r}
u_plot <- function(var){
  seq_data %>% 
    filter(temp %in% const_temp) %>% 
    ggplot(.,aes(x=resource, y=!!sym(var), color=as.factor(temp))) + 
    geom_line(size = 2) + 
    scale_color_manual(values = c("#619CFF", "#00BA38", "#F8766D")) +
    labs(x = "Resource (mgC/L)", y = "Per-Spore Susceptibility", color = "Temp", title = "")
}
```

```{r}
susc_plot <- u_plot("m5_u") + labs(title="")
susc_plot
ggsave("susc_plot.png", susc_plot, path=here("mle/fit_plots"))
```


```{r, eval=F}
data_summ %>% ggplot(.,aes(x=resource, y=m1_u, color=as.factor(temp))) + geom_point()
data_summ %>% ggplot(.,aes(x=resource, y=m2_u, color=as.factor(temp))) + geom_point()
data_summ %>% ggplot(.,aes(x=resource, y=m3_u, color=as.factor(temp))) + geom_point()
data_summ %>% ggplot(.,aes(x=resource, y=m4_u, color=as.factor(temp))) + geom_point()
data_summ %>% ggplot(.,aes(x=resource, y=m5_u, color=as.factor(temp))) + geom_point()
```


How well are the full and independent model estimating f

```{r}
  data <- tmp
  R_end <- as.data.frame(mapply(m4_sim, 
                                R=data$amt_init*fora_vol/1000, 
                                time=data$time/60/24, 
                                f=f/fora_vol,
                                u = 0, 
                                length=data$mm, gamma=gamma, Z=0,
                                ref_t=ref_t,
                                arr_t_f=arr_t_f,
                                arr_t_u=arr_t_u,
                                h=h*exp(w*data$temp),
                                temp = data$temp))
  colnames(R_end) <- "R_end"
  data$end <- R_end$R_end
  data %<>% mutate(resid = log(end) - log(amt_rem*fora_vol/1000))
  
    nll <- dnorm(data$resid, 
                 mean = 0, 
                 sd = sd(data$resid, na.rm = T), 
                 log = T)
    nll_sum <- -sum(nll, na.rm = T)
  
  exp_data <- dataset %>% filter(exposed==TRUE)
#  exp_data <- dataset_tmp %>% filter(exposed==TRUE)

  
  I_end <- as.data.frame(mapply(m4_sim, 
                                R=exp_data$resource*life_vol/1000, 
                                time=exp_data$time, 
                                f=f/life_vol, 
                                u=u*exp(exp_data$resource*rho), 
                                length = exp_data$life_mm, 
                                gamma=gamma, 
                                Z=spore_conc*life_vol,
                                ref_t=ref_t,
                                arr_t_f=arr_t_f,
                                arr_t_u=arr_t_u,
                                h=h*exp(w*exp_data$temp),
                                temp=exp_data$temp))

  colnames(I_end) <- "I_end"
  
  exp_data %<>% cbind(I_end)
  
  exp_data %<>% 
    mutate(ll = mapply(inf_out, inf_status = inf_status, I_end=I_end))
  nll_sum <- nll_sum + -sum(exp_data$ll)
```


model 4 - full model
```{r}
data <- tmp
R_end <- as.data.frame(mapply(m4_sim, 
                              R=data$amt_init*fora_vol/1000, 
                              time=data$time/60/24, 
                              f=m4_f/fora_vol,
                              u = 0, 
                              length=data$mm, 
                              gamma=gamma, 
                              Z=0,
                              ref_t=ref_t,
                              arr_t_f=m4_arr,
                              arr_t_u=m4_arr_u,
                              h=m4_h*exp(m4_w*data$temp),
                              temp=data$temp))

colnames(R_end) <- "R_end"
data$end <- R_end$R_end
data %<>% mutate(resid = log(end) - log(amt_rem*fora_vol/1000))

  nll <- dnorm(data$resid, 
               mean = 0, 
               sd = sd(data$resid, na.rm = T), 
               log = T)
  nll_sum_f_m4 <- -sum(nll, na.rm = T)

exp_data <- dataset %>% filter(exposed==TRUE)

I_end <- as.data.frame(mapply(m4_sim, 
                              R=exp_data$resource*life_vol/1000, 
                              time=exp_data$time, 
                              f=m4_f/life_vol, 
                              u=m4_u*exp(exp_data$resource*rho), 
                              length=exp_data$life_mm, 
                              gamma=gamma, 
                              Z=spore_conc*life_vol,
                              ref_t=ref_t,
                              arr_t_f=m4_arr,
                              arr_t_u=m4_arr_u,
                              h=m4_h*exp(m4_w*exp_data$temp),
                              temp=exp_data$temp))


colnames(I_end) <- "I_end"

exp_data %<>% cbind(I_end)

exp_data %<>% 
  mutate(ll = mapply(inf_out, inf_status = inf_status, I_end=I_end))
nll_sum_u_m4 <- -sum(exp_data$ll)
```


model 5 - interaction model


```{r}
data <- tmp
R_end <- as.data.frame(mapply(m3_sim, 
                              R=data$amt_init*fora_vol/1000, 
                              time=data$time/60/24, 
                              f=m5_f/fora_vol,
                              u = 0, 
                              length=data$mm, 
                              gamma=gamma, 
                              Z=0,
                              ref_t=ref_t,
                              arr_t_f=m5_arr,
                              h=m5_h*exp(m5_w*data$temp),
                              temp=data$temp))

colnames(R_end) <- "R_end"
data$end <- R_end$R_end
data %<>% mutate(resid = log(end) - log(amt_rem*fora_vol/1000))

  nll <- dnorm(data$resid, 
               mean = 0, 
               sd = sd(data$resid, na.rm = T), 
               log = T)
  nll_sum_f_m5 <- -sum(nll, na.rm = T)

  nll_sum_u_m5 <- 0
  u_vec <- c(m5_u_15, m5_u_20, m5_u_25)
  rho_vec <- c(m5_rho_15, m5_rho_20, m5_rho_25)
  
  for(i in 1:3){
  exp_data <- dataset %>% filter(exposed==TRUE) %>% filter(temp == temp_IDs[i])

  I_end <- as.data.frame(mapply(m3_sim, 
                                R=exp_data$resource*life_vol/1000, 
                                time=exp_data$time, 
                                f=m5_f/life_vol, 
                                u=u_vec[i]*exp(exp_data$resource*rho_vec[i]), 
                                length = exp_data$life_mm, 
                                gamma=gamma, 
                                Z=spore_conc*life_vol,
                                ref_t=ref_t,
                                arr_t_f=m5_arr,
                                h=m5_h*exp(m5_w*exp_data$temp),
                                temp=exp_data$temp))

  colnames(I_end) <- "I_end"
  
  exp_data %<>% cbind(I_end)
  
  
  exp_data %<>% 
    mutate(ll = mapply(inf_out, inf_status = inf_status, I_end=I_end))
  nll_sum_u_m5 <- nll_sum_u_m5 + -sum(exp_data$ll)
  }

```

```{r}
nll_sum_f_m4
nll_sum_u_m4
(nll_sum_f_m4 + nll_sum_u_m4)

nll_sum_f_m5
nll_sum_u_m5
(nll_sum_f_m5 + nll_sum_u_m5)
```

```{r}
summary(m4_u_f_fit)
summary(m5_u_f_fit)
```



```{r}
getAIC(m4_u_f_fit)
getAIC(m5_u_f_fit)

2*length(coef(m4_u_f_fit))
2*length(coef(m5_u_f_fit))

2*summary(m4_u_f_fit)@m2logL/-2
2*summary(m5_u_f_fit)@m2logL/-2
```