---
title: "mod_results_combined"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = F}
library(here)
source(here("base","src.R"))
```


# Models

Iterative models
```{r, AIC}
m1 <- readRDS(here("mle","final","m1_fit.rds"))
m2 <- readRDS(here("mle","final","m2_fit.rds"))
m3 <- readRDS(here("mle","final","m3_fit.rds"))
m4 <- readRDS(here("model_fitting","m4_coef_fit.rds"))
m5 <- readRDS(here("model_fitting","m5_phi_fit.rds"))
m5_add_f_add_u <- readRDS(here("model_fitting","add_f_add_u_fit.rds"))
m5_add_f_int_u <- readRDS(here("model_fitting", "add_f_int_u_fit.rds"))
#m5a <- readRDS(here("mle","final","m5a_fit_alt2.rds"))
```


```{r}
getAIC <- function(model){
  return(2*length(coef(model))+(summary(model)@m2logL))
}

# getAIC <- function(model){
#   return(2*length(coef(model))-(2*summary(model)@m2logL/-2))
# }
```

```{r}
getAIC(m1)
getAIC(m2)
getAIC(m3)
getAIC(m4)
getAIC(m5)
#getAIC(m5a)
```


```{r}
model_list <- list(m1, m2, m3, m4, m5)
mod_names <- c("m1", "m2", "m3", "m4", "m5")
mod_names_descriptive <- c("size", "temp", "rsc", "add", "inter")
mod_names_full <- paste(mod_names, mod_names_descriptive, sep="_")
#tibble(mod_names, mod_names_descriptive) #check to make sure names line up

aic_table_final <- AICtab(model_list, logLik=T, base=T, mnames=mod_names_full, weights=T)

aic_table_final

saveRDS(aic_table_final, file=here("mle/aic_table_combined_final.rds"))
```

```{r, eval=F}
model_list <- list(m1, m2, m3, m4, m5, m5a)
mod_names <- c("m1", "m2", "m3", "m4", "m5", "m5a")
mod_names_descriptive <- c("size", "temp", "rsc", "add", "inter", "inter-arr")
mod_names_full <- paste(mod_names, mod_names_descriptive, sep="_")
#tibble(mod_names, mod_names_descriptive) #check to make sure names line up

aic_table_final <- AICtab(model_list, logLik=T, base=T, mnames=mod_names_full, weights=T)

aic_table_final
```


```{r, eval=F}
model_list <- list(m1, m2, m3, m4, m5a)
mod_names <- c("m1", "m2", "m3", "m4", "m5")
mod_names_descriptive <- c("size", "temp", "rsc", "add", "inter")
mod_names_full <- paste(mod_names, mod_names_descriptive, sep="_")
#tibble(mod_names, mod_names_descriptive) #check to make sure names line up

aic_table_final <- AICtab(model_list, logLik=T, base=T, mnames=mod_names_full, weights=T)

aic_table_final

saveRDS(aic_table_final, file=here("mle/aic_table_combined_final_alt.rds"))
```


```{r}
model_list <- list(m4, m5, m5_add_f_add_u, m5_add_f_int_u)
mod_names <- c("m4", "m5", "m4_alt", "m5_alt")
mod_names_descriptive <- c("int_f-add_u", "int_f-int_u", "add_f-add_u", "add_f-int_u")
mod_names_full <- paste(mod_names, mod_names_descriptive, sep="_")
#tibble(mod_names, mod_names_descriptive) #check to make sure names line up

aic_table_final <- AICtab(model_list, logLik=T, base=T, mnames=mod_names_descriptive, weights=T)

aic_table_final

saveRDS(aic_table_final, file=here("mle/aic_table_combined_final_addl.rds"))
```

# AIC corrections for small sample size

```{r}
source(here("model_fitting", "combined", "final_prep.R")) #data, global variables and functions
```

# Get component AICs


```{r, m1_ll}
m1_ll <- function(u, f, arr_t_f, h, w){
  data <- tmp
  R_end <- as.data.frame(mapply(m1_sim, 
                                R=data$amt_init*fora_vol/1000, 
                                time=data$time/60/24, 
                                f=f/fora_vol,
                                u = 0, 
                                length=data$mm, 
                                gamma=gamma, 
                                Z=0,
                                ref_t=ref_t,
                                arr_t_f=arr_t_f,
                                h=h*exp(w*data$temp),
                                temp=data$temp))
  
  colnames(R_end) <- "R_end"
  data$end <- R_end$R_end
  #data %<>% mutate(resid = log(end) - log(amt_rem*fora_vol/1000))
  data %<>% mutate(resid = sqrt(end) - sqrt(amt_rem*fora_vol/1000))

    nll <- dnorm(data$resid,
                 mean = 0,
                 sd = sd(data$resid),
                 log = T)
    f_nll <- sum(nll)
  
    
  exp_data <- dataset %>% filter(exposed==TRUE)

  
  I_end <- as.data.frame(mapply(m1_sim, 
                                R=exp_data$resource*life_vol/1000, 
                                time=exp_data$time, 
                                f=f/life_vol, 
                                u=u, 
                                length = exp_data$life_mm, 
                                gamma=gamma, 
                                Z=spore_conc*life_vol,
                                ref_t=ref_t,
                                arr_t_f=arr_t_f,
                                h=h*exp(w*exp_data$temp),
                                temp=exp_data$temp))
  colnames(I_end) <- "I_end"
  
  exp_data %<>% cbind(I_end)
  
  
  exp_data %<>% 
    mutate(ll = mapply(inf_out, inf_status = inf_status, I_end=I_end))
  u_nll <- sum(exp_data$ll)
  
  return(c(f_nll, u_nll))
}
```

```{r, m2_ll}
m2_ll <- function(f, u, arr_t_f, arr_t_u, h, w){
  data <- tmp
  R_end <- as.data.frame(mapply(m2_sim, 
                                R=data$amt_init*fora_vol/1000, 
                                time=data$time/60/24, 
                                f=f/fora_vol,
                                u = 0, 
                                length=data$mm, 
                                gamma=gamma, 
                                Z=0,
                                arr_t_f=arr_t_f,
                                arr_t_u=arr_t_u,
                                ref_t=ref_t,
                                h=h*exp(w*data$temp),
                                temp=data$temp))
  colnames(R_end) <- "R_end"
  data$end <- R_end$R_end
  #data %<>% mutate(resid = log(end) - log(amt_rem*fora_vol/1000))
  data %<>% mutate(resid = sqrt(end) - sqrt(amt_rem*fora_vol/1000))
  
    nll <- dnorm(data$resid, 
                 mean = 0, 
                 sd = sd(data$resid), 
                 log = T)
    f_nll <- sum(nll)
  
  exp_data <- dataset %>% filter(exposed==TRUE)


  
  I_end <- as.data.frame(mapply(m2_sim, 
                                R=exp_data$resource*life_vol/1000, 
                                time=exp_data$time, 
                                f=f/life_vol, 
                                u=u, 
                                length = exp_data$life_mm, 
                                gamma=gamma, 
                                Z=spore_conc*life_vol,
                                arr_t_f=arr_t_f,
                                arr_t_u=arr_t_u,
                                ref_t=ref_t,
                                h=h*exp(w*exp_data$temp),
                                temp=exp_data$temp))

  colnames(I_end) <- "I_end"
  
  exp_data %<>% cbind(I_end)
  
  exp_data %<>% 
    mutate(ll = mapply(inf_out, inf_status = inf_status, I_end=I_end))
  u_nll <- sum(exp_data$ll)
  return(c(f_nll, u_nll))
}
```


```{r, m3_ll}
m3_ll <- function(f, u, arr_t_f, h, w, rho){
  data <- tmp
  R_end <- as.data.frame(mapply(m3_sim, 
                                R=data$amt_init*fora_vol/1000, 
                                time=data$time/60/24, 
                                f=f/fora_vol,
                                u = 0, 
                                length=data$mm, 
                                gamma=gamma, 
                                Z=0,
                                arr_t_f=arr_t_f,
                                ref_t=ref_t,
                                h=h*exp(w*data$temp),
                                temp=data$temp))
  colnames(R_end) <- "R_end"
  data$end <- R_end$R_end
  #data %<>% mutate(resid = log(end) - log(amt_rem*fora_vol/1000))
  data %<>% mutate(resid = sqrt(end) - sqrt(amt_rem*fora_vol/1000))
  
    nll <- dnorm(data$resid, 
                 mean = 0, 
                 sd = sd(data$resid), 
                 log = T)
    f_nll <- sum(nll)
  
  exp_data <- dataset %>% filter(exposed==TRUE)


  
  I_end <- as.data.frame(mapply(m3_sim, 
                                R=exp_data$resource*life_vol/1000, 
                                time=exp_data$time, 
                                f=f/life_vol, 
                                u=u*exp(exp_data$resource*rho), 
                                length = exp_data$life_mm, 
                                gamma=gamma, 
                                Z=spore_conc*life_vol,
                                arr_t_f=arr_t_f,
                                ref_t=ref_t,
                                h=h*exp(w*exp_data$temp),
                                temp=exp_data$temp))

  colnames(I_end) <- "I_end"
  
  exp_data %<>% cbind(I_end)
  
  exp_data %<>% 
    mutate(ll = mapply(inf_out, inf_status = inf_status, I_end=I_end))
  u_nll <- sum(exp_data$ll)
  return(c(f_nll, u_nll))
}
```


```{r, m4_ll}
m4_ll <- function(f, u, arr_t_f, arr_t_u, h, w, rho){
  
    if(f<0 | h<0 | u<0 | arr_t_f<0 | arr_t_u<0 |
      (u/100000*exp(arr_t_u*((1/15)-(1/15)))*exp(0.1/1000*rho)) <0 |
     (u/100000*exp(arr_t_u*((1/15)-(1/25)))*exp(1.0/1000*rho)) <0) {
  
      return(NA)
  
  } 
  
  else {  
  
  
  data <- tmp
  R_end <- as.data.frame(mapply(m4_sim, 
                                R=data$amt_init*fora_vol/1000, 
                                time=data$time/60/24, 
                                f=f/fora_vol,
                                u = 0, 
                                length=data$mm, 
                                gamma=gamma, 
                                Z=0,
                                ref_t=ref_t,
                                arr_t_f=arr_t_f,
                                arr_t_u=arr_t_u,
                                h=h*exp(data$temp*w),
                                temp = data$temp))
  colnames(R_end) <- "R_end"
  data$end <- R_end$R_end
  #data %<>% mutate(resid = log(end) - log(amt_rem*fora_vol/1000))
  data %<>% mutate(resid = sqrt(end) - sqrt(amt_rem*fora_vol/1000))
  
    nll <- dnorm(data$resid, 
                 mean = 0, 
                 sd = sd(data$resid), 
                 log = T)
    f_nll <- sum(nll)
  
  exp_data <- dataset %>% filter(exposed==TRUE)
#  exp_data <- dataset_tmp %>% filter(exposed==TRUE)

  
  I_end <- as.data.frame(mapply(m4_sim, 
                                R=exp_data$resource*life_vol/1000, 
                                time=exp_data$time, 
                                f=f/life_vol, 
                                u=(u/100000)*exp(exp_data$resource*rho), 
                                length = exp_data$life_mm, 
                                gamma=gamma, 
                                Z=spore_conc*life_vol,
                                ref_t=ref_t,
                                arr_t_f=arr_t_f,
                                arr_t_u=arr_t_u,
                                h=h*exp(exp_data$temp*w),
                                temp=exp_data$temp))

  colnames(I_end) <- "I_end"
  
  exp_data %<>% cbind(I_end)
  
  exp_data %<>% 
    mutate(ll = mapply(inf_out, inf_status = inf_status, I_end=I_end))
  u_nll <- sum(exp_data$ll)
  return(c(f_nll, u_nll))
  
  }
}
```


```{r}

m5_num_sol <- function(t, x, params){
  R <- x[1]
  S <- x[2]
  I <- x[3]
  Z <- x[4]
  
  with(as.list(params),{
    dR <- -R*(S+I)*(f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
              (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R*exp(w*temp))
    
    dS <- -Z*S*u*exp(arr_t_u*(1/ref_t - 1/temp))*exp(resource*rho)*exp(resource*temp*phi)*
      (f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
                (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R*exp(w*temp))
    
    dI <- Z*S*u*exp(arr_t_u*(1/ref_t - 1/temp))*exp(resource*rho)*exp(resource*temp*phi)*
      (f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
               (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R*exp(w*temp))
    
    dZ <- -Z*(S+I)*(f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma))/
              (1+f*exp(arr_t_f*(1/ref_t - 1/temp))*(length^gamma)*h*R*exp(w*temp))
    res <- c(dR, dS, dI, dZ)
    list(res)}
  )
}


    # dS = -S*Z*u*exp(T_A_u*((1/15)-(1/T_trt)))*exp(R_trt*u2)*exp(R_trt*T_trt*u3)*
    #   f*(l^2)*exp(T_A_f*((1/15)-(1/T_trt))) / (1+(A*f*(l^2)*h*exp(h2*T_trt)))
    # dI = S*Z*u*exp(T_A_u*((1/15)-(1/T_trt)))*exp(R_trt*u2)*exp(R_trt*T_trt*u3)*
    #   f*(l^2)*exp(T_A_f*((1/15)-(1/T_trt))) / (1+(A*f*(l^2)*h*exp(h2*T_trt)))
    # dZ = -(S+I)*Z*f*(l^2)*exp(T_A_f*((1/15)-(1/T_trt))) / (1+(A*f*(l^2)*h*exp(h2*T_trt)))
    # dA = -(S+I)*A*f*(l^2)*exp(T_A_f*((1/15)-(1/T_trt))) / (1+(A*f*(l^2)*h*exp(h2*T_trt)))
```


```{r}
m5_sim <- function(R, time, f, u, length, gamma, Z, ref_t, arr_t_f, arr_t_u, h, temp, resource, w, rho, phi){
  times <- seq(0, time, by=0.01)
  xstart <- c(R=R,
              S=1,
              I=0,
              Z=Z)
  params <- c(f=f,
              u=u,
              length = length,
              gamma = gamma,
              Z = Z,
              ref_t = ref_t,
              arr_t_f = arr_t_f,
              arr_t_u = arr_t_u,
              h = h,
              temp = temp,
              resource = resource,
              w = w,
              rho = rho,
              phi = phi)
  output <- as.data.frame(lsoda(y=xstart, times, m5_num_sol, params))
  
  if(Z == 0) {
  end_data <- slice_max(output, time)[,2]
  }
  else {
  end_data <- slice_max(output, time)[,4]  
  }

  return(end_data)
}
```

```{r}
m5_ll <- function(f, u, arr_t_f, arr_t_u, h, w, rho, phi){
  
  if(f<0 | h<0 | u<0 | arr_t_f<0 | arr_t_u<0 |
      (u/100000*exp(arr_t_u*((1/15)-(1/15)))*exp(0.1/1000*rho)*exp(0.1/1000*15*phi)) <0 |
     (u/100000*exp(arr_t_u*((1/15)-(1/25)))*exp(1.0/1000*rho)*exp(1.0/1000*25*phi)) <0) {
  
      return(NA)
  
  } 
  
  else {  
  
  
  data <- tmp
  R_end <- as.data.frame(mapply(m5_sim, 
                                R=data$amt_init*fora_vol/1000, 
                                time=data$time/60/24, 
                                f=f/fora_vol,
                                u = 0, 
                                length=data$mm, 
                                gamma=gamma, 
                                Z=0,
                                ref_t=ref_t,
                                arr_t_f=arr_t_f,
                                arr_t_u=arr_t_u,
                                h=h,
                                temp = data$temp,
                                resource = data$resource,
                                w = w,
                                rho = rho,
                                phi = phi))
  colnames(R_end) <- "R_end"
  data$end <- R_end$R_end
  #data %<>% mutate(resid = log(end) - log(amt_rem*fora_vol/1000))
  data %<>% mutate(resid = sqrt(end) - sqrt(amt_rem*fora_vol/1000))
  
    nll <- dnorm(data$resid, 
                 mean = 0, 
                 sd = sd(data$resid), 
                 log = T)
    f_nll <- sum(nll)
  
  exp_data <- dataset %>% filter(exposed==TRUE)

  
  I_end <- as.data.frame(mapply(m5_sim, 
                                R=exp_data$resource*life_vol/1000, 
                                time=exp_data$time, 
                                f=f/life_vol, 
                                u=u/100000, 
                                length = exp_data$life_mm, 
                                gamma=gamma, 
                                Z=spore_conc*life_vol,
                                ref_t=ref_t,
                                arr_t_f=arr_t_f,
                                arr_t_u=arr_t_u,
                                h=h,
                                temp=exp_data$temp,
                                resource=exp_data$resource,
                                w = w,
                                rho = rho,
                                phi = phi))

  colnames(I_end) <- "I_end"
  
  exp_data %<>% cbind(I_end)
  
  exp_data %<>% 
    mutate(ll = mapply(inf_out, inf_status = inf_status, I_end=I_end))
  u_nll <- sum(exp_data$ll)
  return(c(f_nll, u_nll))
  
  }
}
```


```{r}
tmp <- data

m1_output <- m1_ll(u = coef(m1)[1], 
      f=coef(m1)[2], 
      arr_t_f=coef(m1)[3], 
      h=coef(m1)[4], 
      w=coef(m1)[5])

m2_output <- m2_ll(f = coef(m2)[1], 
      u=coef(m2)[2], 
      arr_t_f=coef(m2)[3], 
      arr_t_u=coef(m2)[4], 
      h=coef(m2)[5], 
      w=coef(m2)[6])

m3_output <- m3_ll(f = coef(m3)[1], 
      u=coef(m3)[2], 
      arr_t_f=coef(m3)[3], 
      h=coef(m3)[4], 
      w=coef(m3)[5],
      rho=coef(m3)[6])

m4_output <- m4_ll(f = coef(m4)[1], 
      u=coef(m4)[2], 
      arr_t_f=coef(m4)[3], 
      arr_t_u=coef(m4)[4], 
      h=coef(m4)[5], 
      w=coef(m4)[6],
      rho=coef(m4)[7])

m5_output <- m5_ll(f = coef(m5)[1], 
      u=coef(m5)[2], 
      arr_t_f=coef(m5)[3], 
      arr_t_u=coef(m5)[4], 
      h=coef(m5)[5], 
      w=coef(m5)[6],
      rho=coef(m5)[7],
      phi=coef(m5)[8])
```

```{r}
check_ll <- function(model, output){
  summary(model)@m2logL == -2*sum(output)
}

m1_output
check_ll(m1, m1_output)

m2_output
check_ll(m2, m2_output)

m3_output
check_ll(m3, m3_output)

m4_output
check_ll(m4, m4_output)

m5_output
check_ll(m5, m5_output)
```

```{r}
get_combined_AIC <- function(model, output){
 return((2*4 - 2*output[1]) + (2*(length(coef(model))-4) - 2*output[2]))
}
```

```{r}
get_combined_AIC(m1, m1_output) == getAIC(m1)
get_combined_AIC(m2, m2_output) == getAIC(m2)
get_combined_AIC(m3, m3_output) == getAIC(m3)
get_combined_AIC(m4, m4_output) == getAIC(m4)
get_combined_AIC(m5, m5_output) == getAIC(m5)
```

```{r}
fora_n <- nrow(data)
inf_n <- nrow(dataset %>% filter(exposed==T))

get_combined_corrected_AIC <- function(model, output){
  (2*4 - 2*output[1]) + (2*4^2 + 2*4)/(fora_n - 4 - 1) + 
  
  (2*(length(coef(model))-4) - 2*output[2]) + (2*(length(coef(m1))-4)^2 + 2*(length(coef(m1))-4))/(inf_n - (length(coef(m1))-4) - 1)
}
```


```{r}
getAIC(m1)
get_combined_AIC(m1, m1_output)
get_combined_corrected_AIC(m1, m1_output)
```

```{r}
getAIC(m1)
getAIC(m2)
getAIC(m3)
getAIC(m4)
getAIC(m5)
```


```{r}
get_combined_AIC(m1, m1_output)

get_combined_AIC(m2, m2_output)

get_combined_AIC(m3, m3_output)

get_combined_AIC(m4, m4_output)

get_combined_AIC(m5, m5_output)
```


```{r}
get_combined_corrected_AIC(m1, m1_output)

get_combined_corrected_AIC(m2, m2_output)

get_combined_corrected_AIC(m3, m3_output)

get_combined_corrected_AIC(m4, m4_output)

get_combined_corrected_AIC(m5, m5_output)
```






