---
title: "cerio"
author: "Daniel Suh"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=F}
library(here)

source(here("base","src.R"))
```

```{r}
fecundity <- readRDS(here("processed_data", "fecundity.rds"))
length <- readRDS(here("processed_data", "length.rds"))
lifespan <- readRDS(here("processed_data", "lifespan.rds"))
lt_summary <- readRDS(here("processed_data", "lt_summary.rds"))
prevalence <- readRDS(here("processed_data", "prevalence.rds"))
spore_yield <- readRDS(here("processed_data", "spore_yield.rds"))
```

lifespan 
currently, 
```{r}
lifespan %>% filter(temp %in% const_temp & resource == 1) %>%
  ggplot(.,aes(x=temp, y = as.numeric(mean_span),color = inf_status)) + 
  geom_point(aes(), position = position_dodge(width = 0.5)) + 
  geom_line(aes(group = interaction(temp, inf_status)), position = position_dodge(width = 0.5)) +
  geom_errorbar(aes(ymin = mean_span-se, ymax = mean_span+se), position = position_dodge(width = 0.5)) +
  facet_wrap(vars(species), nrow=1) +
  scale_color_manual(values = c("red", "blue")) + 
  labs(y = "Average Lifespan (Days)", x = "Temperature (C)", color = "Infection\nStatus" )

lifespan %>% filter(temp %in% const_temp & resource == 1) %>% 
  group_by(temp, species) %>% 
  summarize(diff = first(mean_span) - last(mean_span)) %>%
  ggplot(.,aes(x = temp, y = diff, fill = species)) + 
  geom_col(position="dodge") + 
  labs(y = "Difference in lifespan\ndue to infection (days)", x = "Temperature (C)")

lifespan %>% filter(temp %in% const_temp & resource == 1) %>% 
  group_by(temp, species) %>% 
  summarize(perc = ((first(as.numeric(mean_span)) - last(as.numeric(mean_span)))/first(as.numeric(mean_span)))) %>%
  ggplot(.,aes(x = temp, y = perc, fill = species)) + 
  geom_col(position="dodge") + 
  labs(y = "Difference in lifespan\ndue to infection (percent)", x = "Temperature (C)")
```


```{r}
prob_inf <- prevalence %>% filter(temp %in% const_temp & species =="C") %>%
  ggplot(.,aes(x=resource, y = prev, group = temp, color = temp)) +
  geom_bar(stat = "identity", aes(fill = temp), width = 0.5, position = position_dodge(width = 0.5), color = "black") +
  geom_linerange(aes(ymax=conf$upper, ymin=conf$lower), position = position_dodge(width = 0.5), color = "black") +
  scale_fill_manual(values = c("#619CFF", "#00BA38", "#F8766D")) + 
  labs(y = "Probability of Infection", x = "Resource Concentration (mgC/L)", fill = "Temperature") + 
  proj_theme
prob_inf
```

Reproductive Rate
```{r}
little_r_fig <- lt_summary %>% filter(temp_var == 0, resource ==1) %>% 
  ggplot(.,aes(x=as.factor(resource),y=S.r,color=inf_status, shape = species)) + 
  geom_point(aes(), position = position_dodge(width = 0.5)) + 
  geom_linerange(aes(ymax=S.r.975, ymin=S.r.025), position = position_dodge(width = 0.5)) +
  scale_color_manual(values = c("red", "blue")) + 
  facet_wrap(vars(temp_id,species), nrow = 1) + 
  labs(y = "Host net reproductive rate", x = "Resource Concentration mgC/L", color = "Infection\nStatus" ) +
  proj_theme
little_r_fig
```


Spore Yield
```{r}
spores_fig <- spore_yield %>% filter(temp %in% const_temp & species =="C") %>%  
  ggplot(., aes(x=resource, y = log_mean_yield)) + 
  geom_point(aes(), position = position_dodge(width = 0.5)) + 
  geom_line(aes(group = temp), position = position_dodge(width = 0.5)) +
  geom_errorbar(aes(ymin = log_mean_yield-log_se, ymax = log_mean_yield+log_se), position = position_dodge(width = 0.5)) +
  facet_wrap(vars(temp)) + 
  labs(y = "ln(Average Spore Yield)", x = "Resource Concentration (mgC/L)") +
  proj_theme
spores_fig
```


