---
title: "compare_best_models"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(here)
source(here("base","src.R")) #packages
source(here("model_fitting", "combined", "final_prep.R")) #data, global variables and functions

library(patchwork)
```




```{r}
m4_u_f_fit <- readRDS(file = here("mle", "final", "m4_fit.rds"))
m5_u_f_fit <- readRDS(file = here("mle", "final", "m5_fit.rds"))
m5a_u_f_fit <- readRDS(file = here("mle", "final", "m5a_fit.rds"))
```



```{r}
m4_coef <- coef(m4_u_f_fit)
m4_f <- as.numeric(m4_coef[1])
m4_u <- as.numeric(m4_coef[2])
m4_arr <- as.numeric(m4_coef[3])
m4_arr_u <- as.numeric(m4_coef[4])
m4_h <- as.numeric(m4_coef[5])
m4_w <- as.numeric(m4_coef[6])
m4_rho <- as.numeric(m4_coef[7])


m5_coef <- coef(m5_u_f_fit)
m5_f <- as.numeric(m5_coef[1])
m5_u_15 <- as.numeric(m5_coef[2])
m5_u_20 <- as.numeric(m5_coef[3])
m5_u_25 <- as.numeric(m5_coef[4])
m5_arr <- as.numeric(m5_coef[5])
m5_h <- as.numeric(m5_coef[6])
m5_w <- as.numeric(m5_coef[7])
m5_rho_15 <- as.numeric(m5_coef[8])
m5_rho_20 <- as.numeric(m5_coef[9])
m5_rho_25 <- as.numeric(m5_coef[10])


m5a_coef <- coef(m5a_u_f_fit)
m5a_f <- as.numeric(m5a_coef[1])
m5a_u <- as.numeric(m5a_coef[2])
m5a_arr <- as.numeric(m5a_coef[3])
m5a_arr_u <- as.numeric(m5a_coef[4])
m5a_h <- as.numeric(m5a_coef[5])
m5a_w <- as.numeric(m5a_coef[6])
m5a_rho_15 <- as.numeric(m5a_coef[7])
m5a_rho_20 <- as.numeric(m5a_coef[8])
m5a_rho_25 <- as.numeric(m5a_coef[9])
```



How well are the full and independent model estimating f


model 4 - full model
```{r}
#data <- tmp
R_end <- as.data.frame(mapply(m4_sim, 
                              R=data$amt_init*fora_vol/1000, 
                              time=data$time/60/24, 
                              f=m4_f/fora_vol,
                              u = 0, 
                              length=data$mm, 
                              gamma=gamma, 
                              Z=0,
                              ref_t=ref_t,
                              arr_t_f=m4_arr,
                              arr_t_u=m4_arr_u,
                              h=m4_h*exp(m4_w*data$temp),
                              temp=data$temp))

colnames(R_end) <- "R_end"
data$end <- R_end$R_end
data %<>% mutate(resid = log(end) - log(amt_rem*fora_vol/1000))

  nll <- dnorm(data$resid, 
               mean = 0, 
               sd = sd(data$resid, na.rm = T), 
               log = T)
  nll_sum_f_m4 <- -sum(nll, na.rm = T)

exp_data <- dataset %>% filter(exposed==TRUE)

I_end <- as.data.frame(mapply(m4_sim, 
                              R=exp_data$resource*life_vol/1000, 
                              time=exp_data$time, 
                              f=m4_f/life_vol, 
                              u=m4_u*exp(exp_data$resource*m4_rho), 
                              length=exp_data$life_mm, 
                              gamma=gamma, 
                              Z=spore_conc*life_vol,
                              ref_t=ref_t,
                              arr_t_f=m4_arr,
                              arr_t_u=m4_arr_u,
                              h=m4_h*exp(m4_w*exp_data$temp),
                              temp=exp_data$temp))


colnames(I_end) <- "I_end"

exp_data %<>% cbind(I_end)

exp_data %<>% 
  mutate(ll = mapply(inf_out, inf_status = inf_status, I_end=I_end))
nll_sum_u_m4 <- -sum(exp_data$ll)
```


model 5 - interaction model


```{r}
#data <- tmp
R_end <- as.data.frame(mapply(m3_sim, 
                              R=data$amt_init*fora_vol/1000, 
                              time=data$time/60/24, 
                              f=m5_f/fora_vol,
                              u = 0, 
                              length=data$mm, 
                              gamma=gamma, 
                              Z=0,
                              ref_t=ref_t,
                              arr_t_f=m5_arr,
                              h=m5_h*exp(m5_w*data$temp),
                              temp=data$temp))

colnames(R_end) <- "R_end"
data$end <- R_end$R_end
data %<>% mutate(resid = log(end) - log(amt_rem*fora_vol/1000))

  nll <- dnorm(data$resid, 
               mean = 0, 
               sd = sd(data$resid, na.rm = T), 
               log = T)
  nll_sum_f_m5 <- -sum(nll, na.rm = T)

  nll_sum_u_m5 <- 0
  u_vec <- c(m5_u_15, m5_u_20, m5_u_25)
  rho_vec <- c(m5_rho_15, m5_rho_20, m5_rho_25)
  
  for(i in 1:3){
  exp_data <- dataset %>% filter(exposed==TRUE) %>% filter(temp == temp_IDs[i])

  I_end <- as.data.frame(mapply(m3_sim, 
                                R=exp_data$resource*life_vol/1000, 
                                time=exp_data$time, 
                                f=m5_f/life_vol, 
                                u=u_vec[i]*exp(exp_data$resource*rho_vec[i]), 
                                length = exp_data$life_mm, 
                                gamma=gamma, 
                                Z=spore_conc*life_vol,
                                ref_t=ref_t,
                                arr_t_f=m5_arr,
                                h=m5_h*exp(m5_w*exp_data$temp),
                                temp=exp_data$temp))

  colnames(I_end) <- "I_end"
  
  exp_data %<>% cbind(I_end)
  
  
  exp_data %<>% 
    mutate(ll = mapply(inf_out, inf_status = inf_status, I_end=I_end))
  nll_sum_u_m5 <- nll_sum_u_m5 + -sum(exp_data$ll)
  }

```


model 5a

```{r}
#data <- tmp
R_end <- as.data.frame(mapply(m4_sim, 
                              R=data$amt_init*fora_vol/1000, 
                              time=data$time/60/24, 
                              f=m5a_f/fora_vol,
                              u = 0, 
                              length=data$mm, 
                              gamma=gamma, 
                              Z=0,
                              ref_t=ref_t,
                              arr_t_f=m5a_arr,
                              arr_t_u=m5a_arr_u,
                              h=m5a_h*exp(m5a_w*data$temp),
                              temp=data$temp))

colnames(R_end) <- "R_end"
data$end <- R_end$R_end
data %<>% mutate(resid = log(end) - log(amt_rem*fora_vol/1000))

  nll <- dnorm(data$resid, 
               mean = 0, 
               sd = sd(data$resid, na.rm = T), 
               log = T)
  nll_sum_f_m5a <- -sum(nll, na.rm = T)

  nll_sum_u_m5a <- 0
  rho_vec <- c(m5a_rho_15, m5a_rho_20, m5a_rho_25)
  
  for(i in 1:3){
  exp_data <- dataset %>% filter(exposed==TRUE) %>% filter(temp == temp_IDs[i])

  I_end <- as.data.frame(mapply(m4_sim, 
                                R=exp_data$resource*life_vol/1000, 
                                time=exp_data$time, 
                                f=m5a_f/life_vol, 
                                u=m5a_u*exp(exp_data$resource*rho_vec[i]), 
                                length = exp_data$life_mm, 
                                gamma=gamma, 
                                Z=spore_conc*life_vol,
                                ref_t=ref_t,
                                arr_t_f=m5a_arr,
                                arr_t_u=m5a_arr_u,
                                h=m5a_h*exp(m5a_w*exp_data$temp),
                                temp=exp_data$temp))

  colnames(I_end) <- "I_end"
  
  exp_data %<>% cbind(I_end)
  
  
  exp_data %<>% 
    mutate(ll = mapply(inf_out, inf_status = inf_status, I_end=I_end))
  nll_sum_u_m5a <- nll_sum_u_m5a + -sum(exp_data$ll)
  }

```


```{r}
nll_sum_f_m4
nll_sum_u_m4
(nll_sum_f_m4 + nll_sum_u_m4)
```


```{r}
nll_sum_f_m5
nll_sum_u_m5
(nll_sum_f_m5 + nll_sum_u_m5)
```


```{r}
nll_sum_f_m5a
nll_sum_u_m5a
(nll_sum_f_m5a + nll_sum_u_m5a)
```

```{r}
summary(m4_u_f_fit)
summary(m5_u_f_fit)
summary(m5a_u_f_fit)
```


```{r}
getAIC(m4_u_f_fit)
getAIC(m5_u_f_fit)
getAIC(m5a_u_f_fit)

2*length(coef(m4_u_f_fit))
2*length(coef(m5_u_f_fit))
2*length(coef(m5a_u_f_fit))

2*summary(m4_u_f_fit)@m2logL/-2
2*summary(m5_u_f_fit)@m2logL/-2
2*summary(m5a_u_f_fit)@m2logL/-2
```