---
title: "Epidemiological Parameters"
author: "Daniel Suh"
date: "`r Sys.Date()`"
output: html_document
---

```{r packages, message = F}
library(here)

source(here("base","src.R"))
library(bbmle)
```

$$ 
R\emptyset = \frac { \beta S^* \sigma }{ \mu } \\

\beta = transmission\ rate \\

S^*= equilibrium\ susceptible\ host\ density \\

\sigma = spore\ yield \\

\mu = degradation\ rate \\ 
$$
```{r, read data}
fitness <- read.csv(here("raw_data/main_fitness_edit.csv")) #must be read.csv
mort <- read_csv(here("raw_data/main_mort_edit.csv"))

fitness %<>% mutate(species = ifelse(species=="daphnia", "D", "C"))
fitness %<>% select(-c(end_data_date, mortality_day))
mort %<>% select(-c(end_data_date, mortality_day))

foraging <- read_csv(here("raw_data","foraging.csv"))

dataset <- left_join(fitness, mort)
```

```{r}


#calculate foraging rates for each individual
foraging %<>% mutate(length = as.numeric(length),
                     start_min = time_in_hr*60+time_in_min,
                     end_min = time_measured_hr*60+time_measured_min,
                     time = end_min-start_min,
                     vol = 15)

control <- foraging %>% filter(trt=="C") %>% 
  group_by(temp, resource, block) %>% 
  summarize(control_read = mean(read, na.rm=T))

foraging %<>% left_join(., control)

foraging %<>% filter(trt=="trt") %>% 
  mutate(rate = log(control_read/read)*(vol/time),
         amt_time = (control_read - read)/time)

foraging %<>% mutate(rate = rate*1440) #convert rate from ml/min to ml/day
foraging %<>% filter(trt == "trt") %>% mutate(ID = paste(temp, resource, "D", sep = "_"))

```





```{r seed}
set.seed(30605)
```

euler-lotka
$$

$$




I need to figure out why the line that makes "inf_status" and "dead" is removing rows
```{r, little r}


#DCS Note: if using read_csv so that dataset is a tibble then dates are properly encoded
#however, this somehow changes how some of the NaN's are handled downstream (in the little.r.calculator) which breaks the function
#if NaN's are manually changed to 0's then this then alters results

dataset %<>% mutate(birthdate = ifelse(species == "daphnia", "4/5/22", "4/6/22"), 
                    lifespan = as.numeric(mdy(final_date) - mdy(birthdate))) %>% filter(is.na(male))

#dataset <- read.csv("/Users/dcsuh/Desktop/Traits1-3.csv", na.strings=c("NA", "NULL"))

dataset %<>% mutate(inf_status = replace_na(inf, 0), dead = ifelse(is.na(REMOVED) & is.na(KBP), 1, 0)) %>% mutate(ID = paste(species, temp_id, resource, inf_status, sep = "_")) #why is this removing rows?


##Spore Yield
dataset %<>% mutate(spore_conc = ((spore_RAW/8)*10000))
#this doubles the spore count if the water was added because that would make it twice as dilute
#spore yield is calculated by dividing total counted spores by 8 (number of cells used in hemocytomer) and then multiplying by 10000 to get spores/mL
dataset %<>% mutate(spore_yield = ifelse(spore_water_added==1,spore_conc*0.5,spore_conc*0.25))


dataset$spore_exposure <- 200
dataset$uninf <- 1-dataset$inf # could do it either way
dataset$time <- 1 # best guess at duration of exposure?
dataset <- dataset[!is.na(dataset$uninf),] # remove NAs
dataset <- dataset[dataset$spore_exposure > 0,] # can't estimate beta if no exposure!
dataset$spore_exposure <- as.numeric(dataset$spore_exposure) 

# this is the function that estimates beta. i'll put it in a couple loops below. 
# right here it is estimating a single beta for the entire dataset (not very useful,
# but it gives me a sense of what order of magnitude to start the optimizer on)
beta.est <- mle2(uninf ~ dbinom(size=1, prob=exp(-beta*spore_exposure*1000*time)), 
                 start=list(beta = 0.000001), data=dataset, control=list(parscale = c(beta = 0.000001)),
                 skip.hessian=F,method="L-BFGS-B", lower=.00000001, upper=0.0001)
print(coef(beta.est))

# will loop through all treatments:
dataset$trt <- paste(dataset$temp, dataset$resource, dataset$species, sep = "_")
trts <- unique(dataset$trt)
trts
beta.summary <- data.frame(treatment = trts)


treatments <- unique(dataset$trt) 
length(treatments) # how many unique? # this tells you how big to make the summary 
# dataframe where we will store all of the results. we will be looping through. 


#########################################################
# 2) some meta-information to now about the experiment:

age.at.start <- 5  #this tells the function what the starting age of animals in the spread sheet is
# day.columns <- which(names(dataset)%in%c("4/10/22",       "4/11/22",       "4/12/22",       "4/13/22",
#                                          "4/14/22",       "4/15/22",       "4/16/22",       "4/17/22",
#                                          "4/18/22",       "4/19/22",       "4/20/22",       "4/21/22",
#                                          "4/22/22",       "4/23/22",       "4/24/22",       "4/25/22",
#                                          "4/26/22",       "4/27/22",       "4/28/22",       "4/29/22",
#                                          "4/30/22",       "5/1/22",        "5/2/22",        "5/3/22",
#                                          "5/4/22",        "5/5/22",        "5/6/22",        "5/7/22",
#                                          "5/8/22",        "5/9/22",        "5/10/22",       "5/11/22",
#                                          "5/12/22",       "5/13/22",       "5/14/22",       "5/15/22",
#                                          "5/16/22",       "5/17/22",       "5/18/22",       "5/19/22",
#                                          "5/20/22",       "5/21/22",       "5/22/22",       "5/23/22"))

day.columns <- which(names(dataset)%in%c("X4.10.22","X4.11.22","X4.12.22","X4.13.22","X4.14.22","X4.15.22","X4.16.22",
                                         "X4.17.22","X4.18.22","X4.19.22","X4.20.22","X4.21.22","X4.22.22","X4.23.22",
                                         "X4.24.22","X4.25.22","X4.26.22","X4.27.22","X4.28.22","X4.29.22","X4.30.22",
                                         "X5.1.22","X5.2.22","X5.3.22","X5.4.22","X5.5.22","X5.6.22","X5.7.22",
                                         "X5.8.22","X5.9.22","X5.10.22","X5.11.22","X5.12.22","X5.13.22","X5.14.22",
                                         "X5.15.22","X5.16.22","X5.17.22","X5.18.22","X5.19.22","X5.20.22","X5.21.22",
                                         "X5.22.22","X5.23.22"))
# which columns in the spreadsheet have entries that correspond to # babies on each day?
max.age <- length(day.columns) + age.at.start - 1 # we use this in the calculation of death
# rate, in case some hosts never died


#########################################################
# 3) define functions that will estimate r and d

Euler = function(r, column, day){
  sum(column*exp(-r*day)) - 1}
# define the euler lotka equation. this would be a complex polynomial and really
# difficult/impossible to solve by hand... so we just ask the computer to do it for us

d.NLL = function(d){
  d <- exp(d) # apply exp transform to ensure positive death rate
  observed <- ddata$dead
  day <- ddata$lifespan
  NLL <- 0
  for (i in 1:length(observed)){
    NLL <- ifelse(observed[i]==1, NLL - log(d*exp(-d*day[i])),
            NLL - (-d*max.age))}
    NLL}
# the if/else statement says lets us leverage data from hosts that died (and which day 
# they died) but also data for hosts that were still alive at the end

little.r.calculator = function(rdat){
  # fx is mean fecundity produced by surviving moms on each day x
  fx <- colMeans(rdat[day.columns], na.rm=T) # note that moms that 
  # had previously died should be blank (or NA) so they are removed from this mean
  
  #DCS note: daphnia and ceriodaphnia started on different dates so they must use different age.at.start
  if(unique(rdat$species=="C")){
    age.at.start <- 4
  }
  
    # z is total number of moms at start of the experiment
  z <- nrow(rdat)
  # sx is proportion of original moms surviving to day x
  Sx <- numeric(length(day.columns))
  for (i in day.columns){
    Sx[(i-day.columns[1]+1)] <- length(na.omit(rdat[,i]))/z}
  
  # now combine survivorship and fecundity into an expression to solve for r
  day <- age.at.start:(length(Sx)+age.at.start-1)
  both <- Sx*fx
    for( k in 1:length(both)){
    if(Sx[k] == 0)
      {both[k] = 0}
    else{both[k]=Sx[k]*fx[k]}}
  
  # finally use the function from earlier to find out what value of 'r' solves the euler-lotka
  little.r <<- uniroot(Euler, interval= c(-2, 2), column=both, day=day)$root
  # need to use <<- to define outside of function (global environment)
  little.r 
  }

```


modified beta
$$

$$


```{r starting values}


for(i in 1:length(trts)){
  dsub <- dataset[dataset$trt==trts[i],]
  beta.summary$temp[i] <- dsub$temp[1]
  beta.summary$resource[i] <- dsub$resource[1]
  beta.summary$species[i] <- dsub$species[1]
  beta.summary$treatment[i] <- dsub$trt[1]
  beta.summary$prev[i] <- sum(dsub$inf)/nrow(dsub)
  
  beta.est <- mle2(uninf ~ dbinom(size=1, prob=exp(-beta*spore_exposure*1000*time)),
                   start=list(beta = 0.000001), data=dsub, control=list(parscale = c(beta = 0.000001)),
                   skip.hessian=F,method="L-BFGS-B", lower=.00000001, upper=0.0001)
  beta.summary$beta.est[i] <- coef(beta.est)
}
  
warnings()  # these are fine. 
beta.summary  
plot(beta.summary$prev, beta.summary$beta.est) # make sure that beta and prevalence are 
# positively correlated. yup, checks out. 
# note about units: units for time in the spreadsheet were already in day; exposure was per ml,
# but after multiplying by 1000, now per L. Therefore, units on beta end up being L/day. 


# okay, next, I'll bootstrap confidence intervals around each of those. 


```


Some stuff we need for estimating R0

```{r, R0}
#parameters used
#d = death rate (taken from bootstrap estimate)
#b = birth rate (taken from bootstrap estimate)
#K = algal carrying capacity (assumed constant)
#r = resource growth rate (assumed constant)
#f = foraging rate (assumed constant)

#parameters used for R0 include
#S = susceptible host density (estimated from bootstrap data)
#B = transmission parameter (estimated from bootstrap)
#A = spore yield
#M = degradation rate


r <- 0.9
K <- .250
f <- 20
M <- 0.2
```




```{r, loop, warning=F}
#########################################################
# 4) loop through clones and calculate for each one:

lt.summary=data.frame(trt=treatments) # will fill out this summary spreadsheet as
# we loop through each clone
iterations = 1000 # how many samples to use in bootstrap
# i would recommend 1,000 or even 10,000 to be really confident on the confidence intervals


for (j in 1:length(treatments)){
  print(j) # ask R to tell you where it is in the loop 
  #j=1   # if something is broken in your loop in can be helpful to set the value 
  # of j and go through the inside of the loop line by line to figure out what is wrong

### used for little r start###
  
  clonedata <- dataset[dataset$trt==treatments[j],]
  # subset the data so you are just looking at clone j. this will get copied over each time
  S.data <- clonedata #[clonedata$infected==0,] # just looking at uninfected (for now)... 
  
  
  S.U.data <- S.data[S.data$inf_status==0,] #filter for only uninfected individuals

  ### little r for uninfected individuals
  little.r.calculator(rdat=S.U.data) # this function saves r to global environment
    lt.summary$S.r.U[j] <- little.r # add it to the summary spreadsheet
  
    ddata <- S.U.data[!is.na(S.U.data$dead),] # for death data, we need to remove observations 
    # where we don't know whether host died or not (in practice, user error during experiment)
    d <- ifelse(mean(ddata$dead) == 0, 0,   #this in case nothing died..
             exp(coef(mle2(minuslogl=d.NLL, start=list(d=log(0.05)), 
                            data=list(ddata=ddata), skip.hessian=T))))
  lt.summary$S.d.U[j] = as.numeric(d) # save to summary
  lt.summary$S.b.U[j] = lt.summary$S.r.U[j] + lt.summary$S.d.U[j] # and calculate b as b = r+d

### little r for infected individuals
  S.I.data <- S.data[S.data$inf_status==1,] #filter for only infected individuals

  little.r.calculator(rdat=S.I.data) # this function saves r to global environment
    lt.summary$S.r.I[j] <- little.r # add it to the summary spreadsheet
  
    ddata <- S.I.data[!is.na(S.I.data$dead),] # for death data, we need to remove observations 
    # where we don't know whether host died or not (in practice, user error during experiment)
    d <- ifelse(mean(ddata$dead) == 0, 0,   #this in case nothing died..
             exp(coef(mle2(minuslogl=d.NLL, start=list(d=log(0.05)), 
                            data=list(ddata=ddata), skip.hessian=T))))
  lt.summary$S.d.I[j] = as.numeric(d) # save to summary
  lt.summary$S.b.I[j] = lt.summary$S.r.I[j] + lt.summary$S.d.I[j] # and calculate b as b = r+d
  
  
### used for little r end###

  
#### used for beta start####
  
  dsub <- dataset[dataset$trt==treatments[j],]
  beta.list <- data.frame(beta=numeric(iterations)) #create empty list to fill in w bootstrap  
  
#### used for beta end####
  
### used for S* start###
    
    lt.summary$S.S.U[j] <- r*(1-((lt.summary$S.d.U[j]/lt.summary$S.b.U[j])/K))/f 

### used for S* end###

### used for fora start###
  
  fora_data <- foraging[foraging$ID==treatments[j],]
  lt.summary$fora[j] <- mean(fora_data$rate)
  
### used for fora end###
  

### used for susc start###
  if (!is.na(lt.summary$fora[j] & lt.summary$fora[j]>0)){
  lt.summary$susc[j] <- beta.summary$beta.est[j]/lt.summary$fora[j]
  }
  else {
  lt.summary$susc[j] <- NA
  }
### used for susc end###
  

### used for spore yield start ###

    yield_data <- S.data[!is.na(S.data$spore_yield),]
    lt.summary$S.yield[j] <- mean(yield_data$spore_yield)
    
### used for spore yield start ###
    
    
### used for R0 start###

if (!is.na(lt.summary$fora[j]) & lt.summary$fora[j]>0) {
  lt.summary$S.R_naught[j] <- (lt.summary$S.S.U[j]*lt.summary$fora[j]*lt.summary$susc[j]*lt.summary$S.yield[j])/M
} 
else {
  lt.summary$S.R_naught[j] <- (lt.summary$S.S.U[j]*beta.summary$beta.est[j]*lt.summary$S.yield[j])/M
}
    
### used for R0 end###


  # now create another summary sheet where we'll save all of the bootstrapped
  # parameter estimates.. make it as long as # iterations you decided earlier
  boot.summary <- data.frame(iterations=1:iterations)

### start of bootstrap loop ###
  for(k in 1:iterations){

### stratify bootstraps to always include both infected and uninfected individuals

    boot.rows <- sample(1:nrow(S.data), size=nrow(S.data), replace=TRUE)
    

### used for little r start###
    S.boot.data <- S.data[boot.rows,]
    
    
### little r for uninfected individuals
    S.U.boot.data <- S.boot.data[S.boot.data$inf_status==0,] #filter for only uninfected individuals
    little.r.calculator(rdat=S.U.boot.data)
    boot.summary$r.U.boot[k] <- little.r
    ddata <- S.U.boot.data #[!is.na(S.boot.data$dead),]
    d <- ifelse(mean(ddata$dead) == 0, 0,   #this in case nothing died..
                exp(coef(mle2(minuslogl=d.NLL, start=list(d=log(0.05)),
                              data=list(ddata=ddata), skip.hessian=T))))
    boot.summary$d.U.boot[k] <- as.numeric(d)
    boot.summary$b.U.boot[k] <- boot.summary$d.U.boot[k] + boot.summary$r.U.boot[k]
    
    
#I can fix this later by stratifying bootstraps to always include at least 1 infected individual but for now we will just ignore infected individuals
    
### little r for infected individuals    
    # S.I.boot.data <- S.boot.data[S.boot.data$inf_status==1,] #filter for only infected individuals
    # little.r.calculator(rdat=S.I.boot.data)
    # boot.summary$r.I.boot[k] <- little.r
    # ddata <- S.I.boot.data #[!is.na(S.boot.data$dead),]
    # d <- ifelse(mean(ddata$dead) == 0, 0,   #this in case nothing died..
    #             exp(coef(mle2(minuslogl=d.NLL, start=list(d=log(0.05)),
    #                           data=list(ddata=ddata), skip.hessian=T))))
    # boot.summary$d.I.boot[k] <- as.numeric(d)
    # boot.summary$b.I.boot[k] <- boot.summary$d.I.boot[k] + boot.summary$r.I.boot[k]
### used for little r end###

    
    
    
    
#### used for beta start####
    
    beta.boot <- mle2(uninf ~ dbinom(size=1, prob=exp(-beta*spore_exposure*1000*time)),
                      start=list(beta = 0.000001), data=S.boot.data, control=list(parscale = c(beta = 0.000001)),
                      skip.hessian=F,method="L-BFGS-B", lower=.00000001, upper=0.0001)
    #this produces a warning: NaNs produced - not sure if this is an issue since beta is estimating properly
    beta.list$beta[k] <- coef(beta.boot)[1]
    
#### used for beta end####
    
    
    

### used for S* start###
    
    boot.summary$S.U.boot[k] <- r*(1-((boot.summary$d.U.boot[k]/boot.summary$b.U.boot[k])/K))/f

### used for S* end###
    
### used for fora start###
    fora.boot.rows <- sample(1:nrow(fora_data), size=nrow(fora_data), replace=TRUE)
    fora.boot.data <- fora_data[fora.boot.rows,]
    boot.summary$fora.boot[k] <- mean(fora.boot.data$rate)
### used for fora end###
    
### used for susc start###
    if (!is.na(boot.summary$fora.boot[k] & boot.summary$fora.boot[k]>0)){
    boot.summary$susc.boot[k] <- beta.list$beta[k]/boot.summary$fora.boot[k]
    }    
    else {
    boot.summary$susc.boot[k] <- NA
    }
    
### used for susc end###


### used for spore yield start ###

    yield_data <- S.boot.data[!is.na(S.boot.data$spore_yield),]
    boot.summary$yield[k] <- mean(yield_data$spore_yield)
    
### used for spore yield start ###
    
    
### used for R0 start###

if (!is.na(boot.summary$fora.boot[k]) & boot.summary$fora.boot[k]>0) {
boot.summary$R_naught.boot[k] <- (boot.summary$S.U.boot[k]*boot.summary$fora.boot[k]*boot.summary$susc.boot[k]*boot.summary$yield[k])/M
}
else {
boot.summary$R_naught.boot[k] <- (boot.summary$S.U.boot[k]*beta.list$beta[k]*boot.summary$yield[k])/M
}
    
### used for R0 end###
    
    
### end of bootstrap loop ###
  }

  
  

  beta.summary$beta.025[j] <- quantile(beta.list$beta, probs=seq(0.025, 0.975, 0.95))[1] # lower 95% confidence interval
  beta.summary$beta.975[j] <- quantile(beta.list$beta, probs=seq(0.025, 0.975, 0.95))[2] # upper 95% confidence interval

  
  # save upper and lower 95% CI's from bootstrapped params:
  lt.summary$S.r.U.975[j] <- quantile(boot.summary$r.U.boot, probs=seq(0.025, 0.975, 0.95))[2]  
  lt.summary$S.r.U.025[j] <- quantile(boot.summary$r.U.boot, probs=seq(0.025, 0.975, 0.95))[1]  
  lt.summary$S.d.U.975[j] <- quantile(boot.summary$d.U.boot, probs=seq(0.025, 0.975, 0.95))[2]  
  lt.summary$S.d.U.025[j] <- quantile(boot.summary$d.U.boot, probs=seq(0.025, 0.975, 0.95))[1]  
  lt.summary$S.b.U.975[j] <- quantile(boot.summary$b.U.boot, probs=seq(0.025, 0.975, 0.95))[2]  
  lt.summary$S.b.U.025[j] <- quantile(boot.summary$b.U.boot, probs=seq(0.025, 0.975, 0.95))[1]  
  
  # lt.summary$S.r.I.975[j] <- quantile(boot.summary$r.I.boot, probs=seq(0.025, 0.975, 0.95))[2]  
  # lt.summary$S.r.I.025[j] <- quantile(boot.summary$r.I.boot, probs=seq(0.025, 0.975, 0.95))[1]  
  # lt.summary$S.d.I.975[j] <- quantile(boot.summary$d.I.boot, probs=seq(0.025, 0.975, 0.95))[2]  
  # lt.summary$S.d.I.025[j] <- quantile(boot.summary$d.I.boot, probs=seq(0.025, 0.975, 0.95))[1]  
  # lt.summary$S.b.I.975[j] <- quantile(boot.summary$b.I.boot, probs=seq(0.025, 0.975, 0.95))[2]  
  # lt.summary$S.b.I.025[j] <- quantile(boot.summary$b.I.boot, probs=seq(0.025, 0.975, 0.95))[1]  

  
  lt.summary$S.S.975[j] <- quantile(boot.summary$S.U.boot, probs=seq(0.025, 0.975, 0.95))[2]  
  lt.summary$S.S.025[j] <- quantile(boot.summary$S.U.boot, probs=seq(0.025, 0.975, 0.95))[1]

  lt.summary$fora.975[j] <- quantile(boot.summary$fora.boot, probs=seq(0.025, 0.975, 0.95),na.rm = T)[2]
  lt.summary$fora.025[j] <- quantile(boot.summary$fora.boot, probs=seq(0.025, 0.975, 0.95),na.rm = T)[1]
  
  lt.summary$susc.975[j] <- quantile(boot.summary$susc.boot, probs=seq(0.025, 0.975, 0.95),na.rm = T)[2]
  lt.summary$susc.025[j] <- quantile(boot.summary$susc.boot, probs=seq(0.025, 0.975, 0.95),na.rm = T)[1]
  
  lt.summary$S.yield[j] <- boot.summary$yield[k]
  
  lt.summary$S.R_naught.975[j] <- quantile(boot.summary$R_naught.boot, probs=seq(0.025, 0.975, 0.95), na.rm=T)[2]  
  lt.summary$S.R_naught.025[j] <- quantile(boot.summary$R_naught.boot, probs=seq(0.025, 0.975, 0.95), na.rm=T)[1]  
  
}











# # take a look at the results!  (you can save as csv if you want)
# lt.summary
# 
# lt.summary_factors <- left_join(lt.summary, treatment_factors, by = "ID")
# 
# lt.summary_factors$ID <- factor(lt.summary_factors$ID, levels = c(   "daphnia_15_0.1_0", "daphnia_15_0.1_1", 
#                                                                      "daphnia_15_0.5_0", "daphnia_15_0.5_1", 
#                                                                      "daphnia_15_1_0",   "daphnia_15_1_1",
#                                                                      "cerio_15_1_0",     "cerio_15_1_1", 
#                                                                      "daphnia_20_0.1_0", "daphnia_20_0.1_1", 
#                                                                      "daphnia_20_0.5_0", "daphnia_20_0.5_1",
#                                                                      "daphnia_20_1_0",   "daphnia_20_1_1",
#                                                                      "cerio_20_1_0",     "cerio_20_1_1",
#                                                                      "daphnia_2V_1_0",   "daphnia_2V_1_1",  
#                                                                      "daphnia_6V_1_0",   "daphnia_6V_1_1",   
#                                                                      "daphnia_14V_1_0",  "daphnia_14V_1_1",     
#                                                                      "daphnia_25_0.1_0", "daphnia_25_0.1_1", 
#                                                                      "daphnia_25_0.5_0", "daphnia_25_0.5_1", 
#                                                                      "daphnia_25_1_0",   "daphnia_25_1_1",     
#                                                                      "cerio_25_1_0",     "cerio_25_1_1"))
# lt.summary_factors$inf_status <- ifelse(lt.summary_factors$inf_status==1,"I","U")

```

```{r}

treatment_factors <- dataset %>% select(species, temp_id, mean_temp, temp_var, resource, trt) %>% distinct()

lt.summary_factors <- left_join(lt.summary, treatment_factors)

saveRDS(lt.summary_factors, file = here("processed_data","lt_full_summary.rds"))


lt.summary_factors %>% filter(species=="D", temp_id %in% c(15, 20, 25)) %>% ggplot(.,aes(x=trt, y=S.R_naught)) + geom_point() + geom_linerange(aes(ymin=S.R_naught.025, ymax=S.R_naught.975)) + theme(axis.text.x = element_text(angle=90))

```



# Some notes

