---
title: "model results"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = F}
library(here)
source(here("base","src.R"))
```


# Models

Iterative models
```{r, AIC}
m0 <- readRDS(here("mle","m0_f_fit.rds"))
m1 <- readRDS(here("mle","m1_f_fit.rds"))
m2 <- readRDS(here("mle","m2_f_fit.rds"))
m3 <- readRDS(here("mle","m3_f_fit.rds")) # handling time method
# m3a <- readRDS(here("mle","m3a_f_fit.rds")) # half-saturation method
m4 <- readRDS(here("mle","m4_f_fit.rds")) # handling time method
# m4a <- readRDS(here("mle","m4a_f_fit.rds")) # half-saturation method
```

Interaction models
```{r}
#all versions use handling time method
# m5 <- readRDS(here("mle","m5_f_fit.rds")) #treament-specific coefficients method
# m5a <- readRDS(here("mle","m5a_f_fit.rds")) #no interaction coefficient method
# m5b <- readRDS(here("mle","m5b_f_fit.rds")) #resource-dependent arrhenius coefficient - LINEAR
# m5c <- readRDS(here("mle","m5c_f_fit.rds")) #resource-dependent arrhenius coefficient - EXP
# m6 <- readRDS(here("mle","m6_f_fit.rds")) #treament-specific coefficients method
# m6a <- readRDS(here("mle","m6a_f_fit.rds")) #no interaction coefficient method
#m6b <- readRDS(here("mle","m6b_f_fit.rds")) #temperature-dependent handling time - LINEAR
m6c <- readRDS(here("mle","m6c_f_fit.rds")) #temperature-dependent handling time - EXP
# m7 <- readRDS(here("mle","m7_f_fit.rds")) #treament-specific coefficients method
# m7a <- readRDS(here("mle","m7a_f_fit.rds")) #no interaction coefficient method

# resource-dependent arrhenius coefficient and temperature-dependent handling time, respectively
# m7b <- readRDS(here("mle","m7b_f_fit.rds")) # LINEAR-LINEAR
# m7c <- readRDS(here("mle","m7c_f_fit.rds")) # EXP-EXP
# m7d <- readRDS(here("mle","m7d_f_fit.rds")) # LINEAR-EXP
# m7e <- readRDS(here("mle","m7e_f_fit.rds")) # EXP-LINEAR
```

# Coefficients

```{r}
m0@coef
m1@coef
m2@coef
m3@coef
# m3a@coef
m4@coef
# m4a@coef
```


```{r}
# m5@coef
# m5a@coef
# m5b@coef
# m5c@coef
```


```{r}
# m6@coef
# m6a@coef
#m6b@coef
m6c@coef
```


```{r}
# m7@coef
# m7a@coef
# m7b@coef
# m7c@coef
# m7d@coef
# m7e@coef
```



# get AIC

```{r}
getAIC <- function(model){
  return(2*length(coef(model))-(2*summary(model)@m2logL/-2))
}
```


```{r}
getAIC(m0)
getAIC(m1)
getAIC(m2)
getAIC(m3)
# getAIC(m3a)
getAIC(m4)
# getAIC(m4a)

getAIC(m6c)
```


# AIC table

```{r, eval=F}
model_list <- list(m0, m1, m2, m3, m4, m5b, m5c, m6b, m6c, m7b, m7c, m7d, m7e)
mod_names <- c("m0", "m1", "m2", "m3", "m4", "m5b", "m5c", "m6b", "m6c", "m7b", "m7c", "m7d", "m7e")
mod_names_descriptive <- c("base", "size", "temp", "rsc", "full", "arr(R)~LIN", "arr(R)~EXP", "h(T)~LIN", "h(T)~EXP", "LIN-LIN", "EXP_EXP", "LIN_EXP", "EXP_LIN")
mod_names_full <- paste(mod_names, mod_names_descriptive, sep="_")
#tibble(mod_names, mod_names_descriptive) #check to make sure names line up

aic_table <- AICtab(model_list, logLik=T, base=T, mnames=mod_names_full, weights=T)

saveRDS(aic_table, file=here("mle/aic_table.rds"))
```


```{r}
model_list <- list(m1, m2, m3, m4, m6c)
mod_names <- c("m1", "m2", "m3", "m4", "m5")
mod_names_descriptive <- c("size", "temp", "rsc", "add", "inter")
mod_names_full <- paste(mod_names, mod_names_descriptive, sep="_")
#tibble(mod_names, mod_names_descriptive) #check to make sure names line up

aic_table_final <- AICtab(model_list, logLik=T, base=T, mnames=mod_names_full, weights=T)

aic_table_final

saveRDS(aic_table_final, file=here("mle/aic_table_f_final.rds"))
```


# get corrected AIC

```{r}
data <- readRDS(here("processed_data","foraging_raw.rds"))
```



```{r}
n <- nrow(data)

getAIC_c <- function(model){
  return((2*length(coef(model))-(summary(model)@m2logL)) + 
           (2*length(coef(model))^2 + 2*length(coef(model)))/(n-length(coef(model))-1))
}
```

```{r}
getAIC_c(m0)
getAIC_c(m1)
getAIC_c(m2)
getAIC_c(m3)
getAIC_c(m4)
getAIC_c(m6c)
```

```{r}
aic_c_table_final <- AICctab(model_list, logLik=T, base=T, mnames=mod_names_full, weights=T, nobs=n)
aic_c_table_final
```





