---
title: "Exploration"
author: "Daniel Suh"
date: "11/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=50),tidy=TRUE)
```

```{r, message = F}
library(tidyverse)
library(magrittr)
library(lubridate)
library(here)
```


Read in pilot data
```{r, message=F}
treatments <- read_csv(here("data/treatments.csv"))
fitness <- read_csv(here("data/fitness.csv"))
mort <- read_csv(here("data/mortality.csv"))
```


View
```{r}
head(treatments)
head(mort)
head(fitness)
```

Summarize prevalence
```{r}
prevalence <- mort %>% group_by(ID) %>% summarize(n = n(), prev = sum(infection_status, na.rm = T)/n()) #NA's removed from numerator but still in denominator
prevalence %>% ggplot(.,aes(x=ID,y=prev)) +
  geom_col() + 
  labs(title = "Prevalence")
```

Summarize fitness
```{r}
fit_by_ID_replicate <- fitness %>% group_by(ID, replicate) %>% summarize(total_fit = sum(fitness, na.rm = T)) # removed NAs
fit_average <- fit_by_ID_replicate %>% group_by(ID) %>% 
  summarize(n = n(), mean_fit = mean(total_fit, na.rm = T), var = var(total_fit, na.rm = T), se = sqrt(var(total_fit, na.rm = T)/n())) # remove NAs
fit_average %>% ggplot(., aes(x=ID, y=mean_fit)) +
  geom_col() + 
  geom_errorbar(aes(ymin = mean_fit-se, ymax = mean_fit+se)) +
  labs(title = "Average Total Fitness")
```

Summarize spore yield
```{r}
spores <- mort %>% filter(spore_yield>0) %>% group_by(ID) %>% 
  summarize(mean_yield = mean(spore_yield, na.rm=T), # NAs removed but there should be no NAs after the filter
            var = var(spore_yield, na.rm = T), 
            se = sqrt(var(spore_yield, na.rm = T)/n()))
spores %>% ggplot(., aes(x=ID, y=mean_yield)) + 
  geom_col() + 
  geom_errorbar(aes(ymin = mean_yield-se, ymax = mean_yield+se)) +
  labs(title = "Average Spore Yield")
spores %>% ggplot(., aes(x=ID, y=log(mean_yield))) + 
  geom_col() + 
  labs(title = "Average Spore Yield log-transformed")
```

Summarize lifespan for all
```{r}
lifespan <- left_join(mort, treatments, by = "ID")
lifespan %<>% select(ID, replicate, birth_date, date)
mdy(lifespan$birth_date)
lifespan %<>% transmute(ID=ID, replicate=replicate, birthday=mdy(birth_date), deathday=mdy(date))
lifespan %<>% mutate(span = deathday - birthday)

mean_span <- lifespan %>% group_by(ID) %>% summarize(mean_span = mean(span, na.rm=T))

mean_span %>% ggplot(.,aes(x=ID, y=mean_span)) +
  geom_col() + 
  geom_text(aes(label=round(mean_span, digits = 2)), vjust = -0.5)
```

```{r}
#rmarkdown::render('exploration.Rmd', output_format = "pdf_document",output_file = here("pilot.pdf"))
```

