---
title: "ANOVA"
author: "Daniel Suh"
date: "8/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=50),tidy=TRUE)
```

Load packages and any necessary functions
```{r}
library(here)

source(here("base","src.R"))
```

Read in data and clean up
```{r, message = F}
fitness <- read_csv(here("raw_data/main_fitness_data.csv"))
mort <- readRDS(here("raw_data/main_mort_edit.rds"))

#change classes as necessary
mort$resource <- as.factor(mort$resource)
fitness$resource <- as.factor(fitness$resource)


#remove males, missing, removed, and killed by pipette
mort %<>% filter(!male %in% c(1) & !missing %in% c(1) & species == "D")
```

Prep infection probability data
```{r}
prevalence <- mort %>% drop_na(inf) %>% filter(exposed==1 & temp %in% const_temp) #remove observations with NA for infection status
```

```{r}
inf_prob_glm <- glm(inf ~ temp * resource, data = prevalence, family = binomial)

summary(inf_prob_glm)
```

Everything after this uses the most filtered dataset
```{r}
mort %<>% filter(!male %in% c(1) & !missing %in% c(1) & !removed %in% c(1) & !KBP %in% c(1) & species == "D")
```


Prep lifespan data
```{r}
lifespan <- mort
lifespan %<>% mutate(birth_day = ifelse(species == "D","4/5/22","4/6/22"))
lifespan %<>% mutate(span = mdy(mortality_day) - mdy(birth_day))
```

lifespan ANOVA
span ~ resource * temperature * infection
```{r}
lifespan_aov <- aov((as.numeric(span)) ~ temp * resource * inf, data = lifespan)

summary(lifespan_aov)

ggqqplot(residuals(lifespan_aov))
shapiro_test(residuals(lifespan_aov))
```

Prep body size data
```{r}
length <- mort
```

body size ANOVA
```{r}
body_size_aov <- aov((length) ~ temp * resource * inf, data = length)

summary(body_size_aov)

ggqqplot(residuals(body_size_aov))
shapiro_test(residuals(body_size_aov))
```

Prep data for spore yield
```{r}
spores <- mort %>% drop_na(inf) %>% filter(exposed==1 & inf==1) %>%
  mutate(spore_conc = ((spore_RAW/8)*10000))
#this doubles the spore count if the water was added because that would make it twice as dilute
#spore yield is calculated by dividing total counted spores by 8 (number of cells used in hemocytomer) and then multiplying by 10000 to get spores/mL
spores %<>% mutate(spore_yield = ifelse(spore_water_added==1,spore_conc*0.5,spore_conc*0.25))
spores %<>% mutate(log_yield = log(spore_yield))

spores %<>% inner_join(.,lifespan)
```

spore yield anova
```{r}
spores_lm <- lm(spore_yield ~ span * length, data = spores)

summary(spores_lm)

ggqqplot(residuals(spores_lm))
shapiro_test(residuals(spores_lm))
```

